activemq-cpp-3.9.0: decaf::util::PriorityQueue< E > Class Template Reference
decaf::util::PriorityQueue< E > Class Template Reference
An unbounded priority queue based on a binary heap algorithm.
#include <src/main/decaf/util/PriorityQueue.h>
Public Member Functions
PriorityQueue ()
Creates a Priority Queue with the default initial capacity.
PriorityQueue (int initialCapacity)
Creates a Priority Queue with the capacity value supplied.
PriorityQueue (int initialCapacity, Comparator< E > *comparator)
Creates a Priority Queue with the default initial capacity.
PriorityQueue (const Collection< E > &source)
Creates a PriorityQueue containing the elements in the specified Collection.
PriorityQueue (const PriorityQueue< E > &source)
Creates a PriorityQueue containing the elements in the specified priority queue.
virtual ~PriorityQueue ()
PriorityQueue< E > & operator= (const Collection< E > &source)
Assignment operator, assign another Collection to this one.
PriorityQueue< E > & operator= (const PriorityQueue< E > &source)
Assignment operator, assign another PriorityQueue to this one.
virtual decaf::util::Iterator
< E > * iterator ()
virtual decaf::util::Iterator
< E > * iterator () const
virtual int size () const
Returns the number of elements in this collection.
virtual void clear ()
Removes all of the elements from this collection (optional operation).The collection will be empty after this method returns.This implementation iterates over this collection, removing each element using the Iterator.remove operation. Most implementations will probably choose to override this method for efficiency.Note that this implementation will throw an UnsupportedOperationException if the iterator returned by this collection's iterator method does not implement the remove method and this collection is non-empty.
Exceptions
UnsupportedOperationException if the clear operation is not supported by this collection
This implementation repeatedly invokes poll until it returns false.
virtual bool offer (const E &value)
Inserts the specified element into the queue provided that the condition allows such an operation.
virtual bool poll (E &result)
Gets and removes the element in the head of the queue.
virtual bool peek (E &result) const
Gets but not removes the element in the head of the queue.
virtual E remove ()
Gets and removes the element in the head of the queue.Throws a NoSuchElementException if there is no element in the queue.
Returns
the element in the head of the queue.
Exceptions
NoSuchElementException if there is no element in the queue.
This implementation returns the result of poll unless the queue is empty.
virtual bool remove (const E &value)
Removes a single instance of the specified element from the collection.More formally, removes an element e such that (value == NULL ? e == NULL : value == e), if this collection contains one or more such elements. Returns true if this collection contained the specified element (or equivalently, if this collection changed as a result of the call).
Parameters
value The reference to the element to remove from this Collection.
Returns
true if the collection was changed, false otherwise.
Exceptions
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
This implementation iterates over the collection looking for the specified element. If it finds the element, it removes the element from the collection using the iterator's remove method.Note that this implementation throws an UnsupportedOperationException if the iterator returned by this collection's iterator method does not implement the remove method and this collection contains the specified object.
virtual bool add (const E &value)
Returns true if this collection changed as a result of the call.(Returns false if this collection does not permit duplicates and already contains the specified element.)Collections that support this operation may place limitations on what elements may be added to this collection. In particular, some collections will refuse to add null elements, and others will impose restrictions on the type of elements that may be added. Collection classes should clearly specify in their documentation any restrictions on what elements may be added.If a collection refuses to add a particular element for any reason other than that it already contains the element, it must throw an exception (rather than returning false). This preserves the invariant that a collection always contains the specified element after this call returns.For non-pointer values, i.e. class instances or string's the object will be copied into the collection, thus the object must support being copied, must not hide the copy constructor and assignment operator.
Parameters
value The reference to the element to add to this Collection.
Returns
true if the element was added to this Collection.
Exceptions
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
IllegalArgumentException if some property of the element prevents it from being added to this collection
IllegalStateException if the element cannot be added at this time due to insertion restrictions.
This implementation returns true if offer succeeds, else throws an IllegalStateException.
decaf::lang::Pointer
< Comparator< E > > comparator () const
obtains a Copy of the Pointer instance that this PriorityQueue is using to compare the elements in the queue with.
Public Member Functions inherited from decaf::util::AbstractQueue< E >
AbstractQueue ()
virtual ~AbstractQueue ()
virtual bool addAll (const Collection< E > &collection)
Adds all of the elements in the specified collection to this collection.The behavior of this operation is undefined if the specified collection is modified while the operation is in progress. (This implies that the behavior of this call is undefined if the specified collection is this collection, and this collection is nonempty.)
Parameters
collection The Collection whose elements are added to this one.
Returns
true if this collection changed as a result of the call
Exceptions
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
IllegalArgumentException if some property of an element prevents it from being added to this collection
IllegalStateException if an element cannot be added at this time due to insertion restrictions.
This implementation iterates over the specified collection, and adds each object returned by the iterator to this collection, in turn.Note that this implementation will throw an UnsupportedOperationException unless add is overridden (assuming the specified collection is non-empty).
virtual E element () const
Gets but not removes the element in the head of the queue.Throws a NoSuchElementException if there is no element in the queue.
Returns
the element in the head of the queue.
Exceptions
NoSuchElementException if there is no element in the queue.
Public Member Functions inherited from decaf::util::Queue< E >
virtual ~Queue ()
Public Member Functions inherited from decaf::util::Collection< E >
virtual ~Collection ()
Public Member Functions inherited from decaf::lang::Iterable< E >
virtual ~Iterable ()
Public Member Functions inherited from decaf::util::concurrent::Synchronizable
virtual ~Synchronizable ()
Public Member Functions inherited from decaf::util::AbstractCollection< E >
AbstractCollection ()
AbstractCollection (const AbstractCollection &other)
Copy Constructor, copy element from the source collection to this collection after clearing any element stored in this collection.
virtual ~AbstractCollection ()
AbstractCollection< E > & operator= (const AbstractCollection< E > &collection)
Assignment Operator, copy element from the source collection to this collection after clearing any element stored in this collection.
virtual bool contains (const E &value) const
Returns true if this collection contains the specified element.More formally, returns true if and only if this collection contains at least one element e such that (value == NULL ? e == NULL : value == e).
Parameters
value The value to check for presence in the collection.
Returns
true if there is at least one of the elements in the collection
Exceptions
NullPointerException if the Collection contains pointers and the Collection does not allow for NULL elements (optional check).
virtual bool containsAll (const Collection< E > &collection) const
Returns true if this collection contains all of the elements in the specified collection.
Parameters
collection The Collection to compare to this one.
Exceptions
NullPointerException if the Collection contains pointers and the Collection does not allow for NULL elements (optional check).
virtual bool equals (const Collection< E > &collection) const
Answers true if this Collection and the one given are the same size and if each element contained in the Collection given is equal to an element contained in this collection.
virtual void copy (const Collection< E > &collection)
Renders this Collection as a Copy of the given Collection.
virtual bool isEmpty () const
Returns true if this collection contains no elements.
virtual bool add (const E &value DECAF_UNUSED)
virtual bool removeAll (const Collection< E > &collection)
Removes all this collection's elements that are also contained in the specified collection (optional operation).After this call returns, this collection will contain no elements in common with the specified collection.
Parameters
collection The Collection whose elements are to be removed from this one.
Returns
true if the collection changed as a result of this call.
Exceptions
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
virtual bool retainAll (const Collection< E > &collection)
Retains only the elements in this collection that are contained in the specified collection (optional operation).In other words, removes from this collection all of its elements that are not contained in the specified collection.
Parameters
collection The Collection whose elements are to be retained.
Returns
true if the collection changed as a result of this call.
Exceptions
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
virtual std::vector< E > toArray () const
Answers an STL vector containing copies of all elements contained in this Collection.
virtual void lock ()
Locks the object.
virtual bool tryLock ()
Attempts to Lock the object, if the lock is already held by another thread than this method returns false.
virtual void unlock ()
Unlocks the object.
virtual void wait ()
Waits on a signal from this object, which is generated by a call to Notify.
virtual void wait (long long millisecs)
Waits on a signal from this object, which is generated by a call to Notify.
virtual void wait (long long millisecs, int nanos)
Waits on a signal from this object, which is generated by a call to Notify.
virtual void notify ()
Signals a waiter on this object that it can now wake up and continue.
virtual void notifyAll ()
Signals the waiters on this object that it can now wake up and continue.
Friends
class PriorityQueueIterator
Additional Inherited Members
Protected Attributes inherited from decaf::util::AbstractCollection< E >
util::concurrent::Mutex mutex
Detailed Description
template<typename E>
class decaf::util::PriorityQueue< E >
An unbounded priority queue based on a binary heap algorithm.
The elements of the priority queue are ordered according to their natural ordering, or by a Comparator provided to one of the constructors that accepts Comparators. A priority queue relying on natural ordering also does not permit insertion of non-comparable objects (doing so may result in a compiler error).
The head of this queue is the least element with respect to the specified ordering. If multiple elements are tied for least value, the head is one of those elements – ties are broken arbitrarily. The queue retrieval operations poll, remove, peek, and element access the element at the head of the queue.
A priority queue is unbounded, but has an internal capacity governing the size of an array used to store the elements on the queue. It is always at least as large as the queue size. As elements are added to a priority queue, its capacity grows automatically. The details of the growth policy are not specified.
This class and its iterator implement all of the optional methods of the Collection and Iterator interfaces. The Iterator provided in method iterator() is not guaranteed to traverse the elements of the priority queue in any particular order. If you need ordered traversal, consider using Arrays::sort(pq.toArray()).
Note that this implementation is not synchronized. Multiple threads should not access a PriorityQueue instance concurrently if any of the threads modifies the queue. Instead, use the thread-safe PriorityBlockingQueue class.
Implementation note: this implementation provides O(log(n)) time for the enqueing and dequeing methods (offer, poll, remove() and add); linear time for the remove(Object) and contains(Object) methods; and constant time for the retrieval methods (peek, element, and size).
Since
1.0
Constructor & Destructor Documentation
template<typename E> decaf::util::PriorityQueue< E >::PriorityQueue () inline
Creates a Priority Queue with the default initial capacity.
References decaf::util::PriorityQueueBase::DEFAULT_CAPACITY.
template<typename E> decaf::util::PriorityQueue< E >::PriorityQueue (int initialCapacity) inline
Creates a Priority Queue with the capacity value supplied.
Parameters
initialCapacity The initial number of elements allocated to this PriorityQueue.
template<typename E> decaf::util::PriorityQueue< E >::PriorityQueue (int initialCapacity, Comparator< E > * comparator) inline
Creates a Priority Queue with the default initial capacity.
This new PriorityQueue takes ownership of the passed Comparator instance and uses that to determine the ordering of the elements in the Queue.
Parameters
initialCapacity The initial number of elements allocated to this PriorityQueue.
comparator The Comparator instance to use in sorting the elements in the Queue.
Exceptions
NullPointerException if the passed Comparator is NULL.
References NULL.
template<typename E> decaf::util::PriorityQueue< E >::PriorityQueue (const Collection< E > & source) inline
Creates a PriorityQueue containing the elements in the specified Collection.
Parameters
source the Collection whose elements are to be placed into this priority queue
template<typename E> decaf::util::PriorityQueue< E >::PriorityQueue (const PriorityQueue< E > & source) inline
Creates a PriorityQueue containing the elements in the specified priority queue.
This priority queue will be ordered according to the same ordering as the given priority queue.
Parameters
source the priority queue whose elements are to be placed into this priority queue
template<typename E> virtual decaf::util::PriorityQueue< E >::~PriorityQueue () inline virtual
Member Function Documentation
template<typename E> virtual bool decaf::util::PriorityQueue< E >::add (const E & value) inline virtual
Returns true if this collection changed as a result of the call.(Returns false if this collection does not permit duplicates and already contains the specified element.)Collections that support this operation may place limitations on what elements may be added to this collection. In particular, some collections will refuse to add null elements, and others will impose restrictions on the type of elements that may be added. Collection classes should clearly specify in their documentation any restrictions on what elements may be added.If a collection refuses to add a particular element for any reason other than that it already contains the element, it must throw an exception (rather than returning false). This preserves the invariant that a collection always contains the specified element after this call returns.For non-pointer values, i.e. class instances or string's the object will be copied into the collection, thus the object must support being copied, must not hide the copy constructor and assignment operator.
Parameters
value The reference to the element to add to this Collection.
Returns
true if the element was added to this Collection.
Exceptions
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
IllegalArgumentException if some property of the element prevents it from being added to this collection
IllegalStateException if the element cannot be added at this time due to insertion restrictions.
This implementation returns true if offer succeeds, else throws an IllegalStateException.
This implementation returns true if offer succeeds, else throws an IllegalStateException.
Reimplemented from decaf::util::AbstractQueue< E >.
References DECAF_CATCH_EXCEPTION_CONVERT, DECAF_CATCH_RETHROW, DECAF_CATCHALL_THROW, and decaf::util::PriorityQueue< E >::offer().
template<typename E> virtual void decaf::util::PriorityQueue< E >::clear () inline virtual
Removes all of the elements from this collection (optional operation).The collection will be empty after this method returns.This implementation iterates over this collection, removing each element using the Iterator.remove operation. Most implementations will probably choose to override this method for efficiency.Note that this implementation will throw an UnsupportedOperationException if the iterator returned by this collection's iterator method does not implement the remove method and this collection is non-empty.
Exceptions
UnsupportedOperationException if the clear operation is not supported by this collection
This implementation repeatedly invokes poll until it returns false.
This implementation repeatedly invokes poll until it returns false.
Reimplemented from decaf::util::AbstractQueue< E >.
References decaf::util::PriorityQueueBase::DEFAULT_CAPACITY.
template<typename E> decaf::lang::Pointer<Comparator<E> > decaf::util::PriorityQueue< E >::comparator () const inline
obtains a Copy of the Pointer instance that this PriorityQueue is using to compare the elements in the queue with.
The returned value is a copy, the caller cannot change the value if the internal Pointer value.
Returns
a copy of the Comparator Pointer being used by this Queue.
template<typename E> virtual decaf::util::Iterator<E>* decaf::util::PriorityQueue< E >::iterator () inline virtual
Returns
an iterator over a set of elements of type T.
Implements decaf::lang::Iterable< E >.
References decaf::util::PriorityQueue< E >::PriorityQueueIterator.
template<typename E> virtual decaf::util::Iterator<E>* decaf::util::PriorityQueue< E >::iterator () const inline virtual
Implements decaf::lang::Iterable< E >.
template<typename E> virtual bool decaf::util::PriorityQueue< E >::offer (const E & value) inline virtual
Inserts the specified element into the queue provided that the condition allows such an operation.
The method is generally preferable to the collection.add(E), since the latter might throw an exception if the operation fails.
Parameters
value the specified element to insert into the queue.
Returns
true if the operation succeeds and false if it fails.
Exceptions
NullPointerException if the Queue implementation does not allow Null values to be inserted into the Queue.
IllegalArgumentException if some property of the specified element prevents it from being added to this queue
Implements decaf::util::Queue< E >.
Referenced by decaf::util::PriorityQueue< E >::add().
template<typename E> PriorityQueue<E>& decaf::util::PriorityQueue< E >::operator= (const Collection< E > & source) inline
Assignment operator, assign another Collection to this one.
Parameters
source The Collection to copy to this one.
template<typename E> PriorityQueue<E>& decaf::util::PriorityQueue< E >::operator= (const PriorityQueue< E > & source) inline
Assignment operator, assign another PriorityQueue to this one.
Parameters
source The PriorityQueue to copy to this one.
template<typename E> virtual bool decaf::util::PriorityQueue< E >::peek (E & result) const inline virtual
Gets but not removes the element in the head of the queue.
The result if successful is assigned to the result parameter.
Parameters
result Reference to an instance of the contained type to assigned the removed value to.
Returns
true if the element at the head of the queue was removed and assigned to the result parameter.
Implements decaf::util::Queue< E >.
References decaf::util::AbstractCollection< E >::isEmpty().
template<typename E> virtual bool decaf::util::PriorityQueue< E >::poll (E & result) inline virtual
Gets and removes the element in the head of the queue.
If the operation succeeds the value of the element at the head of the Queue is assigned to the result parameter and the method returns true. If the operation fails the method returns false and the value of the result parameter is undefined.
Parameters
result Reference to an instance of the contained type to assigned the removed value to.
Returns
true if the element at the head of the queue was removed and assigned to the result parameter.
Implements decaf::util::Queue< E >.
References decaf::util::AbstractCollection< E >::isEmpty().
template<typename E> virtual E decaf::util::PriorityQueue< E >::remove () inline virtual
Gets and removes the element in the head of the queue.Throws a NoSuchElementException if there is no element in the queue.
Returns
the element in the head of the queue.
Exceptions
NoSuchElementException if there is no element in the queue.
This implementation returns the result of poll unless the queue is empty.
This implementation returns the result of poll unless the queue is empty.
Reimplemented from decaf::util::AbstractQueue< E >.
References decaf::util::AbstractCollection< E >::isEmpty().
template<typename E> virtual bool decaf::util::PriorityQueue< E >::remove (const E & value) inline virtual
Removes a single instance of the specified element from the collection.More formally, removes an element e such that (value == NULL ? e == NULL : value == e), if this collection contains one or more such elements. Returns true if this collection contained the specified element (or equivalently, if this collection changed as a result of the call).
Parameters
value The reference to the element to remove from this Collection.
Returns
true if the collection was changed, false otherwise.
Exceptions
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
This implementation iterates over the collection looking for the specified element. If it finds the element, it removes the element from the collection using the iterator's remove method.Note that this implementation throws an UnsupportedOperationException if the iterator returned by this collection's iterator method does not implement the remove method and this collection contains the specified object.
This implementation iterates over the collection looking for the specified element. If it finds the element, it removes the element from the collection using the iterator's remove method.
Note that this implementation throws an UnsupportedOperationException if the iterator returned by this collection's iterator method does not implement the remove method and this collection contains the specified object.
Reimplemented from decaf::util::AbstractCollection< E >.
template<typename E> virtual int decaf::util::PriorityQueue< E >::size () const inline virtual
Returns the number of elements in this collection.
If this collection contains more than Integer::MAX_VALUE elements, returns Integer::MAX_VALUE.
Returns
the number of elements in this collection
Implements decaf::util::Collection< E >.
Friends And Related Function Documentation
template<typename E> friend class PriorityQueueIterator friend
Referenced by decaf::util::PriorityQueue< E >::iterator().
The documentation for this class was generated from the following file:
src/main/decaf/util/PriorityQueue.h