activemq-cpp-3.9.0: decaf::util::Map< K, V > Class Template Reference
decaf::util::Map< K, V > Class Template Reference abstract
An object that maps keys to values.
#include <src/main/decaf/util/Map.h>
Public Member Functions
Map ()
Default constructor - does nothing.
virtual ~Map ()
virtual bool equals (const Map &source) const =0
Compares the specified object with this map for equality.
virtual void copy (const Map &source)=0
Copies the content of the source map into this map.
virtual void clear ()=0
Removes all of the mappings from this map (optional operation).
virtual bool containsKey (const K &key) const =0
Returns true if this map contains a mapping for the specified key.
virtual bool containsValue (const V &value) const =0
Returns true if this map maps one or more keys to the specified value.
virtual bool isEmpty () const =0
virtual int size () const =0
virtual V & get (const K &key)=0
Gets the value mapped to the specified key in the Map.
virtual const V & get (const K &key) const =0
Gets the value mapped to the specified key in the Map.
virtual bool put (const K &key, const V &value)=0
Associates the specified value with the specified key in this map (optional operation).
virtual bool put (const K &key, const V &value, V &oldValue)=0
Associates the specified value with the specified key in this map (optional operation).
virtual void putAll (const Map< K, V > &other)=0
Copies all of the mappings from the specified map to this map (optional operation).
virtual V remove (const K &key)=0
Removes the value (key/value pair) for the specified key from the map, returns a copy of the value that was mapped to the key.
virtual Set< MapEntry< K, V > > & entrySet ()=0
Returns a Set view of the mappings contained in this map.
virtual const Set< MapEntry< K,
V > > & entrySet () const =0
virtual Set< K > & keySet ()=0
Returns a Set view of the keys contained in this map.
virtual const Set< K > & keySet () const =0
virtual Collection< V > & values ()=0
Returns a Collection view of the values contained in this map.
virtual const Collection< V > & values () const =0
Public Member Functions inherited from decaf::util::concurrent::Synchronizable
virtual ~Synchronizable ()
virtual void lock ()=0
Locks the object.
virtual bool tryLock ()=0
Attempts to Lock the object, if the lock is already held by another thread than this method returns false.
virtual void unlock ()=0
Unlocks the object.
virtual void wait ()=0
Waits on a signal from this object, which is generated by a call to Notify.
virtual void wait (long long millisecs)=0
Waits on a signal from this object, which is generated by a call to Notify.
virtual void wait (long long millisecs, int nanos)=0
Waits on a signal from this object, which is generated by a call to Notify.
virtual void notify ()=0
Signals a waiter on this object that it can now wake up and continue.
virtual void notifyAll ()=0
Signals the waiters on this object that it can now wake up and continue.
Detailed Description
template<typename K, typename V>
class decaf::util::Map< K, V >
An object that maps keys to values.
A map cannot contain duplicate keys; each key can map to at most one value.
The Map interface provides three collection views, which allow a map's contents to be viewed as a set of keys, collection of values, or set of key-value mappings. The order of a map is defined as the order in which the iterators on the map's collection views return their elements. Some map implementations, like the TreeMap class, make specific guarantees as to their order; others, like the HashMap class, do not.
Note: great care must be exercised if mutable objects are used as map keys. The behavior of a map is not specified if the value of an object is changed in a manner that affects equals comparisons while the object is a key in the map. A special case of this prohibition is that it is not permissible for a map to contain itself as a key. While it is permissible for a map to contain itself as a value, extreme caution is advised: the equals and hashCode methods are no longer well defined on such a map.
All general-purpose map implementation classes should provide two "standard" constructors: a void (no arguments) constructor which creates an empty map, and a constructor with a single argument of type Map, which creates a new map with the same key-value mappings as its argument. In effect, the latter constructor allows the user to copy any map, producing an equivalent map of the desired class.
The "destructive" methods contained in this interface, that is, the methods that modify the map on which they operate, are specified to throw UnsupportedOperationException if this map does not support the operation. If this is the case, these methods may, but are not required to, throw an UnsupportedOperationException if the invocation would have no effect on the map. For example, invoking the putAll(Map) method on an unmodifiable map may, but is not required to, throw the exception if the map whose mappings are to be "superimposed" is empty.
Some map implementations have restrictions on the keys and values they may contain. For example, some implementations prohibit NULL keys and values, and some have restrictions on the types of their keys. Attempting to insert an ineligible key or value throws an exception, typically NullPointerException or ClassCastException. Attempting to query the presence of an ineligible key or value may throw an exception, or it may simply return false; some implementations will exhibit the former behavior and some will exhibit the latter. More generally, attempting an operation on an ineligible key or value whose completion would not result in the insertion of an ineligible element into the map may throw an exception or it may succeed, at the option of the implementation. Such exceptions are marked as "optional" in the specification for this interface.
Many methods in Collections Framework interfaces are defined in terms of the equals method. For example, the specification for the containsKey(Object key) method says: "returns true if and only if this map contains a mapping for a key k such that (key == k)." This specification should not be construed to imply that invoking Map.containsKey with a non-null argument key will cause (key == k) to be invoked for any key k. Implementations are free to implement optimizations whereby the equals invocation is avoided, for example, by first comparing the hash codes of the two keys. (The Object.hashCode() specification guarantees that two objects with unequal hash codes cannot be equal.) More generally, implementations of the various Collections Framework interfaces are free to take advantage of the specified behavior of underlying Object methods wherever the implementor deems it appropriate.
Since
1.0
Constructor & Destructor Documentation
template<typename K, typename V> decaf::util::Map< K, V >::Map () inline
Default constructor - does nothing.
template<typename K, typename V> virtual decaf::util::Map< K, V >::~Map () inline virtual
Member Function Documentation
template<typename K, typename V> virtual void decaf::util::Map< K, V >::clear () pure virtual
Removes all of the mappings from this map (optional operation).
The map will be empty after this call returns.
Exceptions
UnsupportedOperationException if the clear operation is not supported by this map.
Implemented in decaf::util::HashMap< K, V, HASHCODE >, decaf::util::HashMap< E, decaf::util::Set< E > *, HASHCODE >, decaf::util::concurrent::ConcurrentStlMap< K, V, COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::ProducerId >, decaf::lang::Pointer< activemq::state::ProducerState >, activemq::commands::ProducerId::COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::ConsumerId >, decaf::lang::Pointer< activemq::state::ConsumerState >, activemq::commands::ConsumerId::COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::LocalTransactionId >, decaf::lang::Pointer< activemq::state::TransactionState >, activemq::commands::LocalTransactionId::COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::SessionId >, decaf::lang::Pointer< activemq::state::SessionState >, activemq::commands::SessionId::COMPARATOR >, decaf::util::LinkedHashMap< K, V, HASHCODE >, decaf::util::StlMap< K, V, COMPARATOR >, decaf::util::StlMap< cms::Session *, SessionResolver * >, decaf::util::StlMap< std::string, activemq::cmsutil::CachedConsumer * >, decaf::util::StlMap< std::string, activemq::cmsutil::CachedProducer * >, decaf::util::StlMap< decaf::lang::Runnable *, decaf::util::TimerTask * >, decaf::util::StlMap< std::string, PrimitiveValueNode >, decaf::util::StlMap< std::string, cms::Queue * >, decaf::util::StlMap< std::string, activemq::transport::TransportFactory * >, decaf::util::StlMap< std::string, activemq::wireformat::WireFormatFactory * >, decaf::util::StlMap< decaf::lang::Pointer< activemq::commands::ConsumerId >, decaf::lang::Pointer< activemq::commands::ConsumerInfo >, activemq::commands::ConsumerId::COMPARATOR >, and decaf::util::StlMap< std::string, cms::Topic * >.
template<typename K, typename V> virtual bool decaf::util::Map< K, V >::containsKey (const K & key) const pure virtual
Returns true if this map contains a mapping for the specified key.
More formally, returns true if and only if this map contains a mapping for a key k such that (key == k). (There can be at most one such mapping.)
Parameters
key The key to look up.
Returns
true if this map contains the key mapping, otherwise false.
Implemented in decaf::util::HashMap< K, V, HASHCODE >, decaf::util::HashMap< E, decaf::util::Set< E > *, HASHCODE >, decaf::util::concurrent::ConcurrentStlMap< K, V, COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::ProducerId >, decaf::lang::Pointer< activemq::state::ProducerState >, activemq::commands::ProducerId::COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::ConsumerId >, decaf::lang::Pointer< activemq::state::ConsumerState >, activemq::commands::ConsumerId::COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::LocalTransactionId >, decaf::lang::Pointer< activemq::state::TransactionState >, activemq::commands::LocalTransactionId::COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::SessionId >, decaf::lang::Pointer< activemq::state::SessionState >, activemq::commands::SessionId::COMPARATOR >, decaf::util::StlMap< K, V, COMPARATOR >, decaf::util::StlMap< cms::Session *, SessionResolver * >, decaf::util::StlMap< std::string, activemq::cmsutil::CachedConsumer * >, decaf::util::StlMap< std::string, activemq::cmsutil::CachedProducer * >, decaf::util::StlMap< decaf::lang::Runnable *, decaf::util::TimerTask * >, decaf::util::StlMap< std::string, PrimitiveValueNode >, decaf::util::StlMap< std::string, cms::Queue * >, decaf::util::StlMap< std::string, activemq::transport::TransportFactory * >, decaf::util::StlMap< std::string, activemq::wireformat::WireFormatFactory * >, decaf::util::StlMap< decaf::lang::Pointer< activemq::commands::ConsumerId >, decaf::lang::Pointer< activemq::commands::ConsumerInfo >, activemq::commands::ConsumerId::COMPARATOR >, and decaf::util::StlMap< std::string, cms::Topic * >.
Referenced by decaf::util::HashMap< E, decaf::util::Set< E > *, HASHCODE >::equals().
template<typename K, typename V> virtual bool decaf::util::Map< K, V >::containsValue (const V & value) const pure virtual
Returns true if this map maps one or more keys to the specified value.
More formally, returns true if and only if this map contains at least one mapping to a value v such that (value==v). This operation will probably require time linear in the map size for most implementations of the Map interface.
Parameters
value The Value to look up in this Map.
Returns
true if this map contains at least one mapping for the value, otherwise false.
Implemented in decaf::util::HashMap< K, V, HASHCODE >, decaf::util::HashMap< E, decaf::util::Set< E > *, HASHCODE >, decaf::util::concurrent::ConcurrentStlMap< K, V, COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::ProducerId >, decaf::lang::Pointer< activemq::state::ProducerState >, activemq::commands::ProducerId::COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::ConsumerId >, decaf::lang::Pointer< activemq::state::ConsumerState >, activemq::commands::ConsumerId::COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::LocalTransactionId >, decaf::lang::Pointer< activemq::state::TransactionState >, activemq::commands::LocalTransactionId::COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::SessionId >, decaf::lang::Pointer< activemq::state::SessionState >, activemq::commands::SessionId::COMPARATOR >, decaf::util::StlMap< K, V, COMPARATOR >, decaf::util::StlMap< cms::Session *, SessionResolver * >, decaf::util::StlMap< std::string, activemq::cmsutil::CachedConsumer * >, decaf::util::StlMap< std::string, activemq::cmsutil::CachedProducer * >, decaf::util::StlMap< decaf::lang::Runnable *, decaf::util::TimerTask * >, decaf::util::StlMap< std::string, PrimitiveValueNode >, decaf::util::StlMap< std::string, cms::Queue * >, decaf::util::StlMap< std::string, activemq::transport::TransportFactory * >, decaf::util::StlMap< std::string, activemq::wireformat::WireFormatFactory * >, decaf::util::StlMap< decaf::lang::Pointer< activemq::commands::ConsumerId >, decaf::lang::Pointer< activemq::commands::ConsumerInfo >, activemq::commands::ConsumerId::COMPARATOR >, decaf::util::StlMap< std::string, cms::Topic * >, and decaf::util::LinkedHashMap< K, V, HASHCODE >.
template<typename K, typename V> virtual void decaf::util::Map< K, V >::copy (const Map< K, V > & source) pure virtual
Copies the content of the source map into this map.
Erases all existing mappings in this map. The copy is performed by using the entrySet of the source Map and iterating over those entries, inserting each into the target.
Parameters
source The source object to copy from.
Implemented in decaf::util::HashMap< K, V, HASHCODE >, decaf::util::concurrent::ConcurrentStlMap< K, V, COMPARATOR >, and decaf::util::StlMap< K, V, COMPARATOR >.
template<typename K, typename V> virtual Set< MapEntry<K,V> >& decaf::util::Map< K, V >::entrySet () pure virtual
Returns a Set view of the mappings contained in this map.
The set is backed by the map, so changes to the map are reflected in the set, and vice-versa. If the map is modified while an iteration over the set is in progress (except through the iterator's own remove operation, or through the setValue operation on a map entry returned by the iterator) the results of the iteration are undefined. The set supports element removal, which removes the corresponding mapping from the map, via the Iterator.remove, Set.remove, removeAll, retainAll and clear operations. It does not support the add or addAll operations.
Returns
a reference to a Set<MapEntry<K,V>> that is backed by this Map.
Implemented in decaf::util::concurrent::ConcurrentStlMap< K, V, COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::ProducerId >, decaf::lang::Pointer< activemq::state::ProducerState >, activemq::commands::ProducerId::COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::ConsumerId >, decaf::lang::Pointer< activemq::state::ConsumerState >, activemq::commands::ConsumerId::COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::LocalTransactionId >, decaf::lang::Pointer< activemq::state::TransactionState >, activemq::commands::LocalTransactionId::COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::SessionId >, decaf::lang::Pointer< activemq::state::SessionState >, activemq::commands::SessionId::COMPARATOR >, decaf::util::HashMap< K, V, HASHCODE >, decaf::util::HashMap< E, decaf::util::Set< E > *, HASHCODE >, decaf::util::StlMap< K, V, COMPARATOR >, decaf::util::StlMap< cms::Session *, SessionResolver * >, decaf::util::StlMap< std::string, activemq::cmsutil::CachedConsumer * >, decaf::util::StlMap< std::string, activemq::cmsutil::CachedProducer * >, decaf::util::StlMap< decaf::lang::Runnable *, decaf::util::TimerTask * >, decaf::util::StlMap< std::string, PrimitiveValueNode >, decaf::util::StlMap< std::string, cms::Queue * >, decaf::util::StlMap< std::string, activemq::transport::TransportFactory * >, decaf::util::StlMap< std::string, activemq::wireformat::WireFormatFactory * >, decaf::util::StlMap< decaf::lang::Pointer< activemq::commands::ConsumerId >, decaf::lang::Pointer< activemq::commands::ConsumerInfo >, activemq::commands::ConsumerId::COMPARATOR >, decaf::util::StlMap< std::string, cms::Topic * >, and decaf::util::LinkedHashMap< K, V, HASHCODE >.
Referenced by decaf::util::HashMap< E, decaf::util::Set< E > *, HASHCODE >::putAllImpl().
template<typename K, typename V> virtual const Set< MapEntry<K,V> >& decaf::util::Map< K, V >::entrySet () const pure virtual
Implemented in decaf::util::concurrent::ConcurrentStlMap< K, V, COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::ProducerId >, decaf::lang::Pointer< activemq::state::ProducerState >, activemq::commands::ProducerId::COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::ConsumerId >, decaf::lang::Pointer< activemq::state::ConsumerState >, activemq::commands::ConsumerId::COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::LocalTransactionId >, decaf::lang::Pointer< activemq::state::TransactionState >, activemq::commands::LocalTransactionId::COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::SessionId >, decaf::lang::Pointer< activemq::state::SessionState >, activemq::commands::SessionId::COMPARATOR >, decaf::util::HashMap< K, V, HASHCODE >, decaf::util::HashMap< E, decaf::util::Set< E > *, HASHCODE >, decaf::util::StlMap< K, V, COMPARATOR >, decaf::util::StlMap< cms::Session *, SessionResolver * >, decaf::util::StlMap< std::string, activemq::cmsutil::CachedConsumer * >, decaf::util::StlMap< std::string, activemq::cmsutil::CachedProducer * >, decaf::util::StlMap< decaf::lang::Runnable *, decaf::util::TimerTask * >, decaf::util::StlMap< std::string, PrimitiveValueNode >, decaf::util::StlMap< std::string, cms::Queue * >, decaf::util::StlMap< std::string, activemq::transport::TransportFactory * >, decaf::util::StlMap< std::string, activemq::wireformat::WireFormatFactory * >, decaf::util::StlMap< decaf::lang::Pointer< activemq::commands::ConsumerId >, decaf::lang::Pointer< activemq::commands::ConsumerInfo >, activemq::commands::ConsumerId::COMPARATOR >, decaf::util::StlMap< std::string, cms::Topic * >, and decaf::util::LinkedHashMap< K, V, HASHCODE >.
template<typename K, typename V> virtual bool decaf::util::Map< K, V >::equals (const Map< K, V > & source) const pure virtual
Compares the specified object with this map for equality.
Returns true if the two maps represent the same mappings. More formally, two maps m1 and m2 represent the same mappings if m1.entrySet().equals(m2.entrySet()). This ensures that the equals method works properly across different implementations of the Map interface.
Parameters
source Map to compare to this one.
Returns
true if the Map passed is equal in value to this one.
Implemented in decaf::util::HashMap< K, V, HASHCODE >, decaf::util::concurrent::ConcurrentStlMap< K, V, COMPARATOR >, and decaf::util::StlMap< K, V, COMPARATOR >.
template<typename K, typename V> virtual V& decaf::util::Map< K, V >::get (const K & key) pure virtual
Gets the value mapped to the specified key in the Map.
If there is no element in the map whose key is equivalent to the key provided then a NoSuchElementException is thrown.
Parameters
key The search key whose value should be returned if present.
Returns
A reference to the value for the given key if present in the Map.
Exceptions
NoSuchElementException if the key requests doesn't exist in the Map.
Implemented in decaf::util::HashMap< K, V, HASHCODE >, decaf::util::HashMap< E, decaf::util::Set< E > *, HASHCODE >, decaf::util::concurrent::ConcurrentStlMap< K, V, COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::ProducerId >, decaf::lang::Pointer< activemq::state::ProducerState >, activemq::commands::ProducerId::COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::ConsumerId >, decaf::lang::Pointer< activemq::state::ConsumerState >, activemq::commands::ConsumerId::COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::LocalTransactionId >, decaf::lang::Pointer< activemq::state::TransactionState >, activemq::commands::LocalTransactionId::COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::SessionId >, decaf::lang::Pointer< activemq::state::SessionState >, activemq::commands::SessionId::COMPARATOR >, decaf::util::StlMap< K, V, COMPARATOR >, decaf::util::StlMap< cms::Session *, SessionResolver * >, decaf::util::StlMap< std::string, activemq::cmsutil::CachedConsumer * >, decaf::util::StlMap< std::string, activemq::cmsutil::CachedProducer * >, decaf::util::StlMap< decaf::lang::Runnable *, decaf::util::TimerTask * >, decaf::util::StlMap< std::string, PrimitiveValueNode >, decaf::util::StlMap< std::string, cms::Queue * >, decaf::util::StlMap< std::string, activemq::transport::TransportFactory * >, decaf::util::StlMap< std::string, activemq::wireformat::WireFormatFactory * >, decaf::util::StlMap< decaf::lang::Pointer< activemq::commands::ConsumerId >, decaf::lang::Pointer< activemq::commands::ConsumerInfo >, activemq::commands::ConsumerId::COMPARATOR >, and decaf::util::StlMap< std::string, cms::Topic * >.
Referenced by decaf::util::StlMap< std::string, cms::Topic * >::equals(), decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::SessionId >, decaf::lang::Pointer< activemq::state::SessionState >, activemq::commands::SessionId::COMPARATOR >::equals(), decaf::util::HashMap< E, decaf::util::Set< E > *, HASHCODE >::equals(), decaf::util::StlMap< std::string, cms::Topic * >::putAll(), and decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::SessionId >, decaf::lang::Pointer< activemq::state::SessionState >, activemq::commands::SessionId::COMPARATOR >::putAll().
template<typename K, typename V> virtual const V& decaf::util::Map< K, V >::get (const K & key) const pure virtual
Gets the value mapped to the specified key in the Map.
If there is no element in the map whose key is equivalent to the key provided then a NoSuchElementException is thrown.
Parameters
key The search key whose value should be returned if present.
Returns
A const reference to the value for the given key if present in the Map.
Exceptions
NoSuchElementException if the key requests doesn't exist in the Map.
Implemented in decaf::util::HashMap< K, V, HASHCODE >, decaf::util::HashMap< E, decaf::util::Set< E > *, HASHCODE >, decaf::util::concurrent::ConcurrentStlMap< K, V, COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::ProducerId >, decaf::lang::Pointer< activemq::state::ProducerState >, activemq::commands::ProducerId::COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::ConsumerId >, decaf::lang::Pointer< activemq::state::ConsumerState >, activemq::commands::ConsumerId::COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::LocalTransactionId >, decaf::lang::Pointer< activemq::state::TransactionState >, activemq::commands::LocalTransactionId::COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::SessionId >, decaf::lang::Pointer< activemq::state::SessionState >, activemq::commands::SessionId::COMPARATOR >, decaf::util::StlMap< K, V, COMPARATOR >, decaf::util::StlMap< cms::Session *, SessionResolver * >, decaf::util::StlMap< std::string, activemq::cmsutil::CachedConsumer * >, decaf::util::StlMap< std::string, activemq::cmsutil::CachedProducer * >, decaf::util::StlMap< decaf::lang::Runnable *, decaf::util::TimerTask * >, decaf::util::StlMap< std::string, PrimitiveValueNode >, decaf::util::StlMap< std::string, cms::Queue * >, decaf::util::StlMap< std::string, activemq::transport::TransportFactory * >, decaf::util::StlMap< std::string, activemq::wireformat::WireFormatFactory * >, decaf::util::StlMap< decaf::lang::Pointer< activemq::commands::ConsumerId >, decaf::lang::Pointer< activemq::commands::ConsumerInfo >, activemq::commands::ConsumerId::COMPARATOR >, and decaf::util::StlMap< std::string, cms::Topic * >.
template<typename K, typename V> virtual bool decaf::util::Map< K, V >::isEmpty () const pure virtual
Returns
if the Map contains any element or not, TRUE or FALSE
Implemented in decaf::util::HashMap< K, V, HASHCODE >, decaf::util::HashMap< E, decaf::util::Set< E > *, HASHCODE >, decaf::util::concurrent::ConcurrentStlMap< K, V, COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::ProducerId >, decaf::lang::Pointer< activemq::state::ProducerState >, activemq::commands::ProducerId::COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::ConsumerId >, decaf::lang::Pointer< activemq::state::ConsumerState >, activemq::commands::ConsumerId::COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::LocalTransactionId >, decaf::lang::Pointer< activemq::state::TransactionState >, activemq::commands::LocalTransactionId::COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::SessionId >, decaf::lang::Pointer< activemq::state::SessionState >, activemq::commands::SessionId::COMPARATOR >, decaf::util::StlMap< K, V, COMPARATOR >, decaf::util::StlMap< cms::Session *, SessionResolver * >, decaf::util::StlMap< std::string, activemq::cmsutil::CachedConsumer * >, decaf::util::StlMap< std::string, activemq::cmsutil::CachedProducer * >, decaf::util::StlMap< decaf::lang::Runnable *, decaf::util::TimerTask * >, decaf::util::StlMap< std::string, PrimitiveValueNode >, decaf::util::StlMap< std::string, cms::Queue * >, decaf::util::StlMap< std::string, activemq::transport::TransportFactory * >, decaf::util::StlMap< std::string, activemq::wireformat::WireFormatFactory * >, decaf::util::StlMap< decaf::lang::Pointer< activemq::commands::ConsumerId >, decaf::lang::Pointer< activemq::commands::ConsumerInfo >, activemq::commands::ConsumerId::COMPARATOR >, and decaf::util::StlMap< std::string, cms::Topic * >.
Referenced by decaf::util::HashMap< E, decaf::util::Set< E > *, HASHCODE >::putAll().
template<typename K, typename V> virtual Set<K>& decaf::util::Map< K, V >::keySet () pure virtual
Returns a Set view of the keys contained in this map.
The set is backed by the map, so changes to the map are reflected in the set, and vice-versa. If the map is modified while an iteration over the set is in progress (except through the iterator's own remove operation), the results of the iteration are undefined. The set supports element removal, which removes the corresponding mapping from the map, via the Iterator.remove, Set.remove, removeAll, retainAll, and clear operations. It does not support the add or addAll operations.
Returns
a set view of the keys contained in this map,
Implemented in decaf::util::concurrent::ConcurrentStlMap< K, V, COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::ProducerId >, decaf::lang::Pointer< activemq::state::ProducerState >, activemq::commands::ProducerId::COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::ConsumerId >, decaf::lang::Pointer< activemq::state::ConsumerState >, activemq::commands::ConsumerId::COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::LocalTransactionId >, decaf::lang::Pointer< activemq::state::TransactionState >, activemq::commands::LocalTransactionId::COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::SessionId >, decaf::lang::Pointer< activemq::state::SessionState >, activemq::commands::SessionId::COMPARATOR >, decaf::util::HashMap< K, V, HASHCODE >, decaf::util::HashMap< E, decaf::util::Set< E > *, HASHCODE >, decaf::util::StlMap< K, V, COMPARATOR >, decaf::util::StlMap< cms::Session *, SessionResolver * >, decaf::util::StlMap< std::string, activemq::cmsutil::CachedConsumer * >, decaf::util::StlMap< std::string, activemq::cmsutil::CachedProducer * >, decaf::util::StlMap< decaf::lang::Runnable *, decaf::util::TimerTask * >, decaf::util::StlMap< std::string, PrimitiveValueNode >, decaf::util::StlMap< std::string, cms::Queue * >, decaf::util::StlMap< std::string, activemq::transport::TransportFactory * >, decaf::util::StlMap< std::string, activemq::wireformat::WireFormatFactory * >, decaf::util::StlMap< decaf::lang::Pointer< activemq::commands::ConsumerId >, decaf::lang::Pointer< activemq::commands::ConsumerInfo >, activemq::commands::ConsumerId::COMPARATOR >, decaf::util::StlMap< std::string, cms::Topic * >, and decaf::util::LinkedHashMap< K, V, HASHCODE >.
Referenced by decaf::util::StlMap< std::string, cms::Topic * >::putAll(), and decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::SessionId >, decaf::lang::Pointer< activemq::state::SessionState >, activemq::commands::SessionId::COMPARATOR >::putAll().
template<typename K, typename V> virtual const Set<K>& decaf::util::Map< K, V >::keySet () const pure virtual
Implemented in decaf::util::concurrent::ConcurrentStlMap< K, V, COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::ProducerId >, decaf::lang::Pointer< activemq::state::ProducerState >, activemq::commands::ProducerId::COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::ConsumerId >, decaf::lang::Pointer< activemq::state::ConsumerState >, activemq::commands::ConsumerId::COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::LocalTransactionId >, decaf::lang::Pointer< activemq::state::TransactionState >, activemq::commands::LocalTransactionId::COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::SessionId >, decaf::lang::Pointer< activemq::state::SessionState >, activemq::commands::SessionId::COMPARATOR >, decaf::util::HashMap< K, V, HASHCODE >, decaf::util::HashMap< E, decaf::util::Set< E > *, HASHCODE >, decaf::util::StlMap< K, V, COMPARATOR >, decaf::util::StlMap< cms::Session *, SessionResolver * >, decaf::util::StlMap< std::string, activemq::cmsutil::CachedConsumer * >, decaf::util::StlMap< std::string, activemq::cmsutil::CachedProducer * >, decaf::util::StlMap< decaf::lang::Runnable *, decaf::util::TimerTask * >, decaf::util::StlMap< std::string, PrimitiveValueNode >, decaf::util::StlMap< std::string, cms::Queue * >, decaf::util::StlMap< std::string, activemq::transport::TransportFactory * >, decaf::util::StlMap< std::string, activemq::wireformat::WireFormatFactory * >, decaf::util::StlMap< decaf::lang::Pointer< activemq::commands::ConsumerId >, decaf::lang::Pointer< activemq::commands::ConsumerInfo >, activemq::commands::ConsumerId::COMPARATOR >, decaf::util::StlMap< std::string, cms::Topic * >, and decaf::util::LinkedHashMap< K, V, HASHCODE >.
template<typename K, typename V> virtual bool decaf::util::Map< K, V >::put (const K & key, const V & value) pure virtual
Associates the specified value with the specified key in this map (optional operation).
If the map previously contained a mapping for the key, the old value is replaced by the specified value. (A map m is said to contain a mapping for a key k if and only if m.containsKey(k) would return true.)
Parameters
key The target key.
value The value to be set.
Returns
true if the put operation replaced a value that was associated with an existing mapping to the given key or false otherwise.
Exceptions
UnsupportedOperationException if this map is unmodifiable.
IllegalArgumentException if some property of the specified key or value prevents it from being stored in this map
Implemented in decaf::util::HashMap< K, V, HASHCODE >, decaf::util::HashMap< E, decaf::util::Set< E > *, HASHCODE >, decaf::util::concurrent::ConcurrentStlMap< K, V, COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::ProducerId >, decaf::lang::Pointer< activemq::state::ProducerState >, activemq::commands::ProducerId::COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::ConsumerId >, decaf::lang::Pointer< activemq::state::ConsumerState >, activemq::commands::ConsumerId::COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::LocalTransactionId >, decaf::lang::Pointer< activemq::state::TransactionState >, activemq::commands::LocalTransactionId::COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::SessionId >, decaf::lang::Pointer< activemq::state::SessionState >, activemq::commands::SessionId::COMPARATOR >, decaf::util::StlMap< K, V, COMPARATOR >, decaf::util::StlMap< cms::Session *, SessionResolver * >, decaf::util::StlMap< std::string, activemq::cmsutil::CachedConsumer * >, decaf::util::StlMap< std::string, activemq::cmsutil::CachedProducer * >, decaf::util::StlMap< decaf::lang::Runnable *, decaf::util::TimerTask * >, decaf::util::StlMap< std::string, PrimitiveValueNode >, decaf::util::StlMap< std::string, cms::Queue * >, decaf::util::StlMap< std::string, activemq::transport::TransportFactory * >, decaf::util::StlMap< std::string, activemq::wireformat::WireFormatFactory * >, decaf::util::StlMap< decaf::lang::Pointer< activemq::commands::ConsumerId >, decaf::lang::Pointer< activemq::commands::ConsumerInfo >, activemq::commands::ConsumerId::COMPARATOR >, decaf::util::StlMap< std::string, cms::Topic * >, and decaf::util::LinkedHashMap< K, V, HASHCODE >.
template<typename K, typename V> virtual bool decaf::util::Map< K, V >::put (const K & key, const V & value, V & oldValue) pure virtual
Associates the specified value with the specified key in this map (optional operation).
If the map previously contained a mapping for the key, the old value is replaced by the specified value. (A map m is said to contain a mapping for a key k if and only if m.containsKey(k) would return true.)
This method accepts a reference to a value which will be assigned the previous value for the given key (if any). If there was no previous mapping for the given key the out value is not written to. A return of true indicates that a value was replaced by this put operation.
Parameters
key The target key.
value The value to be set.
oldValue (out) The value previously held in the mapping for this key. .
Returns
true if the put operation replaced a value that was associated with an existing mapping to the given key or false otherwise.
Exceptions
UnsupportedOperationException if this map is unmodifiable.
IllegalArgumentException if some property of the specified key or value prevents it from being stored in this map
Implemented in decaf::util::HashMap< K, V, HASHCODE >, decaf::util::HashMap< E, decaf::util::Set< E > *, HASHCODE >, decaf::util::concurrent::ConcurrentStlMap< K, V, COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::ProducerId >, decaf::lang::Pointer< activemq::state::ProducerState >, activemq::commands::ProducerId::COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::ConsumerId >, decaf::lang::Pointer< activemq::state::ConsumerState >, activemq::commands::ConsumerId::COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::LocalTransactionId >, decaf::lang::Pointer< activemq::state::TransactionState >, activemq::commands::LocalTransactionId::COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::SessionId >, decaf::lang::Pointer< activemq::state::SessionState >, activemq::commands::SessionId::COMPARATOR >, decaf::util::StlMap< K, V, COMPARATOR >, decaf::util::StlMap< cms::Session *, SessionResolver * >, decaf::util::StlMap< std::string, activemq::cmsutil::CachedConsumer * >, decaf::util::StlMap< std::string, activemq::cmsutil::CachedProducer * >, decaf::util::StlMap< decaf::lang::Runnable *, decaf::util::TimerTask * >, decaf::util::StlMap< std::string, PrimitiveValueNode >, decaf::util::StlMap< std::string, cms::Queue * >, decaf::util::StlMap< std::string, activemq::transport::TransportFactory * >, decaf::util::StlMap< std::string, activemq::wireformat::WireFormatFactory * >, decaf::util::StlMap< decaf::lang::Pointer< activemq::commands::ConsumerId >, decaf::lang::Pointer< activemq::commands::ConsumerInfo >, activemq::commands::ConsumerId::COMPARATOR >, decaf::util::StlMap< std::string, cms::Topic * >, and decaf::util::LinkedHashMap< K, V, HASHCODE >.
template<typename K, typename V> virtual void decaf::util::Map< K, V >::putAll (const Map< K, V > & other) pure virtual
Copies all of the mappings from the specified map to this map (optional operation).
The effect of this call is equivalent to that of calling put(k, v) on this map once for each mapping from key k to value v in the specified map. The behavior of this operation is undefined if the specified map is modified while the operation is in progress.
Parameters
other A Map instance whose elements are to all be inserted in this Map.
Exceptions
UnsupportedOperationException If the implementing class does not support the putAll operation.
Implemented in decaf::util::HashMap< K, V, HASHCODE >, decaf::util::HashMap< E, decaf::util::Set< E > *, HASHCODE >, decaf::util::concurrent::ConcurrentStlMap< K, V, COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::ProducerId >, decaf::lang::Pointer< activemq::state::ProducerState >, activemq::commands::ProducerId::COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::ConsumerId >, decaf::lang::Pointer< activemq::state::ConsumerState >, activemq::commands::ConsumerId::COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::LocalTransactionId >, decaf::lang::Pointer< activemq::state::TransactionState >, activemq::commands::LocalTransactionId::COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::SessionId >, decaf::lang::Pointer< activemq::state::SessionState >, activemq::commands::SessionId::COMPARATOR >, decaf::util::StlMap< K, V, COMPARATOR >, decaf::util::StlMap< cms::Session *, SessionResolver * >, decaf::util::StlMap< std::string, activemq::cmsutil::CachedConsumer * >, decaf::util::StlMap< std::string, activemq::cmsutil::CachedProducer * >, decaf::util::StlMap< decaf::lang::Runnable *, decaf::util::TimerTask * >, decaf::util::StlMap< std::string, PrimitiveValueNode >, decaf::util::StlMap< std::string, cms::Queue * >, decaf::util::StlMap< std::string, activemq::transport::TransportFactory * >, decaf::util::StlMap< std::string, activemq::wireformat::WireFormatFactory * >, decaf::util::StlMap< decaf::lang::Pointer< activemq::commands::ConsumerId >, decaf::lang::Pointer< activemq::commands::ConsumerInfo >, activemq::commands::ConsumerId::COMPARATOR >, and decaf::util::StlMap< std::string, cms::Topic * >.
template<typename K, typename V> virtual V decaf::util::Map< K, V >::remove (const K & key) pure virtual
Removes the value (key/value pair) for the specified key from the map, returns a copy of the value that was mapped to the key.
Care must be taken when using this operation as it will throw an exception if there is no mapping for the given key.
Parameters
key The search key whose mapping is to be removed.
Returns
a copy of the element that was previously mapped to the given key.
Exceptions
NoSuchElementException if this key is not in the Map.
UnsupportedOperationException if this map is unmodifiable.
Implemented in decaf::util::HashMap< K, V, HASHCODE >, decaf::util::HashMap< E, decaf::util::Set< E > *, HASHCODE >, decaf::util::concurrent::ConcurrentStlMap< K, V, COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::ProducerId >, decaf::lang::Pointer< activemq::state::ProducerState >, activemq::commands::ProducerId::COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::ConsumerId >, decaf::lang::Pointer< activemq::state::ConsumerState >, activemq::commands::ConsumerId::COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::LocalTransactionId >, decaf::lang::Pointer< activemq::state::TransactionState >, activemq::commands::LocalTransactionId::COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::SessionId >, decaf::lang::Pointer< activemq::state::SessionState >, activemq::commands::SessionId::COMPARATOR >, decaf::util::StlMap< K, V, COMPARATOR >, decaf::util::StlMap< cms::Session *, SessionResolver * >, decaf::util::StlMap< std::string, activemq::cmsutil::CachedConsumer * >, decaf::util::StlMap< std::string, activemq::cmsutil::CachedProducer * >, decaf::util::StlMap< decaf::lang::Runnable *, decaf::util::TimerTask * >, decaf::util::StlMap< std::string, PrimitiveValueNode >, decaf::util::StlMap< std::string, cms::Queue * >, decaf::util::StlMap< std::string, activemq::transport::TransportFactory * >, decaf::util::StlMap< std::string, activemq::wireformat::WireFormatFactory * >, decaf::util::StlMap< decaf::lang::Pointer< activemq::commands::ConsumerId >, decaf::lang::Pointer< activemq::commands::ConsumerInfo >, activemq::commands::ConsumerId::COMPARATOR >, decaf::util::StlMap< std::string, cms::Topic * >, and decaf::util::LinkedHashMap< K, V, HASHCODE >.
template<typename K, typename V> virtual int decaf::util::Map< K, V >::size () const pure virtual
Returns
The number of elements (key/value pairs) in this map.
Implemented in decaf::util::HashMap< K, V, HASHCODE >, decaf::util::HashMap< E, decaf::util::Set< E > *, HASHCODE >, decaf::util::concurrent::ConcurrentStlMap< K, V, COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::ProducerId >, decaf::lang::Pointer< activemq::state::ProducerState >, activemq::commands::ProducerId::COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::ConsumerId >, decaf::lang::Pointer< activemq::state::ConsumerState >, activemq::commands::ConsumerId::COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::LocalTransactionId >, decaf::lang::Pointer< activemq::state::TransactionState >, activemq::commands::LocalTransactionId::COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::SessionId >, decaf::lang::Pointer< activemq::state::SessionState >, activemq::commands::SessionId::COMPARATOR >, decaf::util::StlMap< K, V, COMPARATOR >, decaf::util::StlMap< cms::Session *, SessionResolver * >, decaf::util::StlMap< std::string, activemq::cmsutil::CachedConsumer * >, decaf::util::StlMap< std::string, activemq::cmsutil::CachedProducer * >, decaf::util::StlMap< decaf::lang::Runnable *, decaf::util::TimerTask * >, decaf::util::StlMap< std::string, PrimitiveValueNode >, decaf::util::StlMap< std::string, cms::Queue * >, decaf::util::StlMap< std::string, activemq::transport::TransportFactory * >, decaf::util::StlMap< std::string, activemq::wireformat::WireFormatFactory * >, decaf::util::StlMap< decaf::lang::Pointer< activemq::commands::ConsumerId >, decaf::lang::Pointer< activemq::commands::ConsumerInfo >, activemq::commands::ConsumerId::COMPARATOR >, and decaf::util::StlMap< std::string, cms::Topic * >.
Referenced by decaf::util::HashMap< E, decaf::util::Set< E > *, HASHCODE >::copy(), decaf::util::HashMap< E, decaf::util::Set< E > *, HASHCODE >::equals(), decaf::util::HashMap< E, decaf::util::Set< E > *, HASHCODE >::HashMap(), and decaf::util::HashMap< E, decaf::util::Set< E > *, HASHCODE >::putAllImpl().
template<typename K, typename V> virtual Collection<V>& decaf::util::Map< K, V >::values () pure virtual
Returns a Collection view of the values contained in this map.
The collection is backed by the map, so changes to the map are reflected in the collection, and vice-versa. If the map is modified while an iteration over the collection is in progress (except through the iterator's own remove operation), the results of the iteration are undefined. The collection supports element removal, which removes the corresponding mapping from the map, via the Iterator.remove, Collection.remove, removeAll, retainAll and clear operations. It does not support the add or addAll operations. For the const version of this method the Collection can only be used as a view into the Map.
Returns
a collection view of the values contained in this map.
Implemented in decaf::util::concurrent::ConcurrentStlMap< K, V, COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::ProducerId >, decaf::lang::Pointer< activemq::state::ProducerState >, activemq::commands::ProducerId::COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::ConsumerId >, decaf::lang::Pointer< activemq::state::ConsumerState >, activemq::commands::ConsumerId::COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::LocalTransactionId >, decaf::lang::Pointer< activemq::state::TransactionState >, activemq::commands::LocalTransactionId::COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::SessionId >, decaf::lang::Pointer< activemq::state::SessionState >, activemq::commands::SessionId::COMPARATOR >, decaf::util::HashMap< K, V, HASHCODE >, decaf::util::HashMap< E, decaf::util::Set< E > *, HASHCODE >, decaf::util::StlMap< K, V, COMPARATOR >, decaf::util::StlMap< cms::Session *, SessionResolver * >, decaf::util::StlMap< std::string, activemq::cmsutil::CachedConsumer * >, decaf::util::StlMap< std::string, activemq::cmsutil::CachedProducer * >, decaf::util::StlMap< decaf::lang::Runnable *, decaf::util::TimerTask * >, decaf::util::StlMap< std::string, PrimitiveValueNode >, decaf::util::StlMap< std::string, cms::Queue * >, decaf::util::StlMap< std::string, activemq::transport::TransportFactory * >, decaf::util::StlMap< std::string, activemq::wireformat::WireFormatFactory * >, decaf::util::StlMap< decaf::lang::Pointer< activemq::commands::ConsumerId >, decaf::lang::Pointer< activemq::commands::ConsumerInfo >, activemq::commands::ConsumerId::COMPARATOR >, decaf::util::StlMap< std::string, cms::Topic * >, and decaf::util::LinkedHashMap< K, V, HASHCODE >.
template<typename K, typename V> virtual const Collection<V>& decaf::util::Map< K, V >::values () const pure virtual
Implemented in decaf::util::concurrent::ConcurrentStlMap< K, V, COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::ProducerId >, decaf::lang::Pointer< activemq::state::ProducerState >, activemq::commands::ProducerId::COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::ConsumerId >, decaf::lang::Pointer< activemq::state::ConsumerState >, activemq::commands::ConsumerId::COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::LocalTransactionId >, decaf::lang::Pointer< activemq::state::TransactionState >, activemq::commands::LocalTransactionId::COMPARATOR >, decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::SessionId >, decaf::lang::Pointer< activemq::state::SessionState >, activemq::commands::SessionId::COMPARATOR >, decaf::util::HashMap< K, V, HASHCODE >, decaf::util::HashMap< E, decaf::util::Set< E > *, HASHCODE >, decaf::util::StlMap< K, V, COMPARATOR >, decaf::util::StlMap< cms::Session *, SessionResolver * >, decaf::util::StlMap< std::string, activemq::cmsutil::CachedConsumer * >, decaf::util::StlMap< std::string, activemq::cmsutil::CachedProducer * >, decaf::util::StlMap< decaf::lang::Runnable *, decaf::util::TimerTask * >, decaf::util::StlMap< std::string, PrimitiveValueNode >, decaf::util::StlMap< std::string, cms::Queue * >, decaf::util::StlMap< std::string, activemq::transport::TransportFactory * >, decaf::util::StlMap< std::string, activemq::wireformat::WireFormatFactory * >, decaf::util::StlMap< decaf::lang::Pointer< activemq::commands::ConsumerId >, decaf::lang::Pointer< activemq::commands::ConsumerInfo >, activemq::commands::ConsumerId::COMPARATOR >, decaf::util::StlMap< std::string, cms::Topic * >, and decaf::util::LinkedHashMap< K, V, HASHCODE >.
The documentation for this class was generated from the following file:
src/main/decaf/util/Map.h