activemq-cpp-3.9.0: decaf::lang::Iterable< E > Class Template Reference
decaf::lang::Iterable< E > Class Template Reference abstract
Implementing this interface allows an object to be cast to an Iterable type for generic collections API calls.
#include <src/main/decaf/lang/Iterable.h>
Public Member Functions
virtual ~Iterable ()
virtual decaf::util::Iterator
< E > * iterator ()=0
virtual decaf::util::Iterator
< E > * iterator () const =0
Detailed Description
template<typename E>
class decaf::lang::Iterable< E >
Implementing this interface allows an object to be cast to an Iterable type for generic collections API calls.
Constructor & Destructor Documentation
template<typename E> virtual decaf::lang::Iterable< E >::~Iterable () inline virtual
Member Function Documentation
template<typename E> virtual decaf::util::Iterator<E>* decaf::lang::Iterable< E >::iterator () pure virtual
Returns
an iterator over a set of elements of type T.
Implemented in decaf::util::concurrent::LinkedBlockingQueue< E >, decaf::util::concurrent::LinkedBlockingQueue< decaf::lang::Pointer< activemq::transport::Transport > >, decaf::util::HashMap< K, V, HASHCODE >::ConstHashMapValueCollection, decaf::util::HashMap< K, V, HASHCODE >::HashMapValueCollection, decaf::util::HashMap< K, V, HASHCODE >::ConstHashMapKeySet, decaf::util::HashMap< K, V, HASHCODE >::HashMapKeySet, decaf::util::HashMap< K, V, HASHCODE >::ConstHashMapEntrySet, decaf::util::concurrent::CopyOnWriteArrayList< E >, decaf::util::HashMap< K, V, HASHCODE >::HashMapEntrySet, decaf::util::AbstractList< E >, decaf::util::AbstractList< activemq::util::ServiceListener * >, decaf::util::AbstractList< decaf::lang::Pointer< activemq::commands::DestinationInfo > >, decaf::util::AbstractList< cms::MessageConsumer * >, decaf::util::AbstractList< PrimitiveValueNode >, decaf::util::AbstractList< decaf::net::URI >, decaf::util::AbstractList< decaf::net::decaf::net::URI >, decaf::util::AbstractList< cms::MessageProducer * >, decaf::util::AbstractList< cms::Destination * >, decaf::util::AbstractList< cms::Session * >, decaf::util::AbstractList< decaf::lang::Pointer< activemq::commands::Command > >, decaf::util::AbstractList< cms::Connection * >, decaf::util::AbstractList< decaf::lang::Pointer< activemq::commands::ActiveMQDestination > >, decaf::util::AbstractList< decaf::lang::Pointer< activemq::commands::MessageDispatch > >, decaf::util::StlList< E >, decaf::util::PriorityQueue< E >, decaf::util::HashSet< E, HASHCODE >, decaf::util::concurrent::SynchronousQueue< E >, decaf::util::StlSet< E >, decaf::util::StlSet< decaf::internal::util::Resource * >, decaf::util::StlSet< decaf::lang::Pointer< activemq::core::Synchronization > >, decaf::util::concurrent::CopyOnWriteArraySet< E >, decaf::util::AbstractSequentialList< E >, decaf::util::AbstractSequentialList< decaf::lang::Pointer< activemq::commands::DestinationInfo > >, decaf::util::AbstractSequentialList< cms::MessageConsumer * >, decaf::util::AbstractSequentialList< PrimitiveValueNode >, decaf::util::AbstractSequentialList< decaf::net::URI >, decaf::util::AbstractSequentialList< decaf::net::decaf::net::URI >, decaf::util::AbstractSequentialList< cms::MessageProducer * >, decaf::util::AbstractSequentialList< cms::Destination * >, decaf::util::AbstractSequentialList< cms::Session * >, decaf::util::AbstractSequentialList< decaf::lang::Pointer< activemq::commands::Command > >, decaf::util::AbstractSequentialList< cms::Connection * >, and decaf::util::AbstractSequentialList< decaf::lang::Pointer< activemq::commands::MessageDispatch > >.
Referenced by decaf::util::AbstractCollection< decaf::lang::Pointer< activemq::commands::MessageDispatch > >::AbstractCollection(), decaf::util::AbstractSequentialList< decaf::lang::Pointer< activemq::commands::MessageDispatch > >::addAll(), decaf::util::AbstractCollection< decaf::lang::Pointer< activemq::commands::MessageDispatch > >::addAll(), decaf::util::concurrent::CopyOnWriteArrayList< E >::addAll(), decaf::util::AbstractList< decaf::lang::Pointer< activemq::commands::MessageDispatch > >::addAll(), decaf::util::concurrent::CopyOnWriteArrayList< E >::addAllAbsent(), decaf::util::ArrayList< decaf::lang::Pointer< activemq::commands::ActiveMQDestination > >::ArrayList(), decaf::util::AbstractCollection< decaf::lang::Pointer< activemq::commands::MessageDispatch > >::clear(), decaf::util::AbstractCollection< decaf::lang::Pointer< activemq::commands::MessageDispatch > >::contains(), decaf::util::AbstractCollection< decaf::lang::Pointer< activemq::commands::MessageDispatch > >::containsAll(), decaf::util::concurrent::CopyOnWriteArrayList< E >::containsAll(), decaf::util::AbstractCollection< decaf::lang::Pointer< activemq::commands::MessageDispatch > >::copy(), decaf::util::concurrent::CopyOnWriteArraySet< E >::equals(), decaf::util::concurrent::CopyOnWriteArrayList< E >::equals(), decaf::util::HashSet< E, HASHCODE >::HashSet(), decaf::util::concurrent::LinkedBlockingQueue< decaf::lang::Pointer< activemq::transport::Transport > >::LinkedBlockingQueue(), decaf::util::LinkedHashSet< E, HASHCODE >::LinkedHashSet(), decaf::util::AbstractCollection< decaf::lang::Pointer< activemq::commands::MessageDispatch > >::operator=(), decaf::util::StlMap< std::string, cms::Topic * >::putAll(), decaf::util::concurrent::ConcurrentStlMap< decaf::lang::Pointer< activemq::commands::SessionId >, decaf::lang::Pointer< activemq::state::SessionState >, activemq::commands::SessionId::COMPARATOR >::putAll(), decaf::util::HashMap< E, decaf::util::Set< E > *, HASHCODE >::putAllImpl(), decaf::util::AbstractCollection< decaf::lang::Pointer< activemq::commands::MessageDispatch > >::remove(), decaf::util::AbstractSet< K >::removeAll(), decaf::util::AbstractCollection< decaf::lang::Pointer< activemq::commands::MessageDispatch > >::removeAll(), decaf::util::AbstractCollection< decaf::lang::Pointer< activemq::commands::MessageDispatch > >::retainAll(), and decaf::util::AbstractCollection< decaf::lang::Pointer< activemq::commands::MessageDispatch > >::toArray().
template<typename E> virtual decaf::util::Iterator<E>* decaf::lang::Iterable< E >::iterator () const pure virtual
Implemented in decaf::util::concurrent::LinkedBlockingQueue< E >, decaf::util::concurrent::LinkedBlockingQueue< decaf::lang::Pointer< activemq::transport::Transport > >, decaf::util::HashMap< K, V, HASHCODE >::ConstHashMapValueCollection, decaf::util::HashMap< K, V, HASHCODE >::HashMapValueCollection, decaf::util::HashMap< K, V, HASHCODE >::ConstHashMapKeySet, decaf::util::HashMap< K, V, HASHCODE >::HashMapKeySet, decaf::util::HashMap< K, V, HASHCODE >::ConstHashMapEntrySet, decaf::util::concurrent::CopyOnWriteArrayList< E >, decaf::util::HashMap< K, V, HASHCODE >::HashMapEntrySet, decaf::util::AbstractList< E >, decaf::util::AbstractList< activemq::util::ServiceListener * >, decaf::util::AbstractList< decaf::lang::Pointer< activemq::commands::DestinationInfo > >, decaf::util::AbstractList< cms::MessageConsumer * >, decaf::util::AbstractList< PrimitiveValueNode >, decaf::util::AbstractList< decaf::net::URI >, decaf::util::AbstractList< decaf::net::decaf::net::URI >, decaf::util::AbstractList< cms::MessageProducer * >, decaf::util::AbstractList< cms::Destination * >, decaf::util::AbstractList< cms::Session * >, decaf::util::AbstractList< decaf::lang::Pointer< activemq::commands::Command > >, decaf::util::AbstractList< cms::Connection * >, decaf::util::AbstractList< decaf::lang::Pointer< activemq::commands::ActiveMQDestination > >, decaf::util::AbstractList< decaf::lang::Pointer< activemq::commands::MessageDispatch > >, decaf::util::StlList< E >, decaf::util::PriorityQueue< E >, decaf::util::HashSet< E, HASHCODE >, decaf::util::concurrent::SynchronousQueue< E >, decaf::util::StlSet< E >, decaf::util::StlSet< decaf::internal::util::Resource * >, decaf::util::StlSet< decaf::lang::Pointer< activemq::core::Synchronization > >, decaf::util::concurrent::CopyOnWriteArraySet< E >, decaf::util::AbstractSequentialList< E >, decaf::util::AbstractSequentialList< decaf::lang::Pointer< activemq::commands::DestinationInfo > >, decaf::util::AbstractSequentialList< cms::MessageConsumer * >, decaf::util::AbstractSequentialList< PrimitiveValueNode >, decaf::util::AbstractSequentialList< decaf::net::URI >, decaf::util::AbstractSequentialList< decaf::net::decaf::net::URI >, decaf::util::AbstractSequentialList< cms::MessageProducer * >, decaf::util::AbstractSequentialList< cms::Destination * >, decaf::util::AbstractSequentialList< cms::Session * >, decaf::util::AbstractSequentialList< decaf::lang::Pointer< activemq::commands::Command > >, decaf::util::AbstractSequentialList< cms::Connection * >, and decaf::util::AbstractSequentialList< decaf::lang::Pointer< activemq::commands::MessageDispatch > >.
The documentation for this class was generated from the following file:
src/main/decaf/lang/Iterable.h