activemq-cpp-3.9.0: decaf::lang Namespace Reference
decaf::lang Namespace Reference
Namespaces
exceptions
Data Structures
class AbstractStringBuilder
A modifiable sequence of characters for use in creating and modifying Strings.
class Appendable
An object to which char sequences and values can be appended.
class ArrayPointer
Decaf's implementation of a Smart Pointer that is a template on a Type and is Thread Safe if the default Reference Counter is used.
class ArrayPointerComparator
This implementation of Comparator is designed to allows objects in a Collection to be sorted or tested for equality based on the value of the value of the actual pointer to the array being contained in this ArrayPointer.
class Boolean
class Byte
class Character
class CharSequence
A CharSequence is a readable sequence of char values.
class Comparable
This interface imposes a total ordering on the objects of each class that implements it.
class Double
struct DYNAMIC_CAST_TOKEN
class Exception
class Float
class Integer
class Iterable
Implementing this interface allows an object to be cast to an Iterable type for generic collections API calls.
class Long
class Math
The class Math contains methods for performing basic numeric operations such as the elementary exponential, logarithm, square root, and trigonometric functions.
class Number
The abstract class Number is the superclass of classes Byte, Double, Float, Integer, Long, and Short.
class Pointer
Decaf's implementation of a Smart Pointer that is a template on a Type and is Thread Safe if the default Reference Counter is used.
class PointerComparator
This implementation of Comparator is designed to allows objects in a Collection to be sorted or tested for equality based on the value of the Object being Pointed to and not the value of the contained pointer in the Pointer instance.
class Readable
A Readable is a source of characters.
class Runnable
Interface for a runnable object - defines a task that can be run by a thread.
class Runtime
class Short
struct STATIC_CAST_TOKEN
class String
An immutable sequence of characters.
class StringBuffer
StringBuffer is a variable size contiguous indexable array of characters.
class StringBuilder
A modifiable sequence of characters for use in creating and modifying Strings.
class System
The System class provides static methods for accessing system level resources and performing some system dependent tasks such as looking up environment values and copying memory and arrays.
class Thread
A Thread is a concurrent unit of execution.
class ThreadGroup
class ThreadLocal
This class provides thread-local variables.
class Throwable
This class represents an error that has occurred.
class Types
Functions
template<typename T , typename U >
bool operator== (const ArrayPointer< T > &left, const U *right)
template<typename T , typename U >
bool operator== (const U *left, const ArrayPointer< T > &right)
template<typename T , typename U >
bool operator!= (const ArrayPointer< T > &left, const U *right)
template<typename T , typename U >
bool operator!= (const U *left, const ArrayPointer< T > &right)
template<typename T , typename R , typename U >
bool operator== (const Pointer< T, R > &left, const U *right)
template<typename T , typename R , typename U >
bool operator== (const U *left, const Pointer< T, R > &right)
template<typename T , typename R , typename U >
bool operator!= (const Pointer< T, R > &left, const U *right)
template<typename T , typename R , typename U >
bool operator!= (const U *left, const Pointer< T, R > &right)
template<typename T , typename R >
std::ostream & operator<< (std::ostream &out, const Pointer< T, R > &pointer)
std::ostream & operator<< (std::ostream &out, const String &target)
bool operator== (const std::string &left, const String &right)
bool operator== (const char *left, const String &right)
bool operator!= (const std::string &left, const String &right)
bool operator!= (const char *left, const String &right)
bool operator<= (const std::string &left, const String &right)
bool operator<= (const char *left, const String &right)
bool operator>= (const std::string &left, const String &right)
bool operator>= (const char *left, const String &right)
bool operator< (const std::string &left, const String &right)
bool operator< (const char *left, const String &right)
bool operator> (const std::string &left, const String &right)
bool operator> (const char *left, const String &right)
Function Documentation
template<typename T , typename R , typename U > bool decaf::lang::operator!= (const Pointer< T, R > & left, const U * right) inline
References decaf::lang::Pointer< T, REFCOUNTER >::get().
template<typename T , typename R , typename U > bool decaf::lang::operator!= (const U * left, const Pointer< T, R > & right) inline
References decaf::lang::Pointer< T, REFCOUNTER >::get().
template<typename T , typename U > bool decaf::lang::operator!= (const ArrayPointer< T > & left, const U * right) inline
References decaf::lang::ArrayPointer< T >::get().
template<typename T , typename U > bool decaf::lang::operator!= (const U * left, const ArrayPointer< T > & right) inline
References decaf::lang::ArrayPointer< T >::get().
bool decaf::lang::operator!= (const std::string & left, const String & right)
bool decaf::lang::operator!= (const char * left, const String & right)
bool decaf::lang::operator< (const std::string & left, const String & right)
bool decaf::lang::operator< (const char * left, const String & right)
template<typename T , typename R > std::ostream& decaf::lang::operator<< (std::ostream & out, const Pointer< T, R > & pointer)
std::ostream& decaf::lang::operator<< (std::ostream & out, const String & target)
bool decaf::lang::operator<= (const std::string & left, const String & right)
bool decaf::lang::operator<= (const char * left, const String & right)
template<typename T , typename R , typename U > bool decaf::lang::operator== (const Pointer< T, R > & left, const U * right) inline
References decaf::lang::Pointer< T, REFCOUNTER >::get().
template<typename T , typename R , typename U > bool decaf::lang::operator== (const U * left, const Pointer< T, R > & right) inline
References decaf::lang::Pointer< T, REFCOUNTER >::get().
template<typename T , typename U > bool decaf::lang::operator== (const ArrayPointer< T > & left, const U * right) inline
References decaf::lang::ArrayPointer< T >::get().
template<typename T , typename U > bool decaf::lang::operator== (const U * left, const ArrayPointer< T > & right) inline
References decaf::lang::ArrayPointer< T >::get().
bool decaf::lang::operator== (const std::string & left, const String & right)
bool decaf::lang::operator== (const char * left, const String & right)
bool decaf::lang::operator> (const std::string & left, const String & right)
bool decaf::lang::operator> (const char * left, const String & right)
bool decaf::lang::operator>= (const std::string & left, const String & right)
bool decaf::lang::operator>= (const char * left, const String & right)