activemq-cpp-3.9.0: decaf::util::HashMap< K, V, HASHCODE >::ConstHashMapEntrySet Class Reference
decaf::util::HashMap< K, V, HASHCODE >::ConstHashMapEntrySet Class Reference
#include <src/main/decaf/util/HashMap.h>
Public Member Functions
ConstHashMapEntrySet (const HashMap *parent)
virtual ~ConstHashMapEntrySet ()
virtual int size () const
Returns the number of elements in this collection.
virtual void clear ()
Removes all of the elements from this collection (optional operation).
virtual bool remove (const MapEntry< K, V > &entry DECAF_UNUSED)
virtual bool contains (const MapEntry< K, V > &entry) const
Returns true if this collection contains the specified element.More formally, returns true if and only if this collection contains at least one element e such that (value == NULL ? e == NULL : value == e).
Parameters
value The value to check for presence in the collection.
Returns
true if there is at least one of the elements in the collection
Exceptions
NullPointerException if the Collection contains pointers and the Collection does not allow for NULL elements (optional check).
This implementation iterates over the elements in the collection, checking each element in turn for equality with the specified element.
virtual Iterator< MapEntry< K,
V > > * iterator ()
virtual Iterator< MapEntry< K,
V > > * iterator () const
Public Member Functions inherited from decaf::util::AbstractSet< MapEntry< K, V > >
AbstractSet ()
virtual ~AbstractSet ()
virtual bool removeAll (const Collection< MapEntry< K, V > > &collection)
Removes all this collection's elements that are also contained in the specified collection (optional operation).After this call returns, this collection will contain no elements in common with the specified collection.
Parameters
collection The Collection whose elements are to be removed from this one.
Returns
true if the collection changed as a result of this call.
Exceptions
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
This implementation iterates over this collection, checking each element returned by the iterator in turn to see if it's contained in the specified collection. If it's so contained, it's removed from this collection with the iterator's remove method.Note that this implementation will throw an UnsupportedOperationException if the iterator returned by the iterator method does not implement the remove method and this collection contains one or more elements in common with the specified collection.
Public Member Functions inherited from decaf::util::Set< MapEntry< K, V > >
virtual ~Set ()
Public Member Functions inherited from decaf::util::Collection< MapEntry< K, V > >
virtual ~Collection ()
virtual bool add (const MapEntry< K, V > &value)=0
Returns true if this collection changed as a result of the call.
Public Member Functions inherited from decaf::lang::Iterable< MapEntry< K, V > >
virtual ~Iterable ()
Public Member Functions inherited from decaf::util::concurrent::Synchronizable
virtual ~Synchronizable ()
Public Member Functions inherited from decaf::util::AbstractCollection< MapEntry< K, V > >
AbstractCollection ()
AbstractCollection (const AbstractCollection &other)
Copy Constructor, copy element from the source collection to this collection after clearing any element stored in this collection.
virtual ~AbstractCollection ()
AbstractCollection< MapEntry
< K, V > > & operator= (const AbstractCollection< MapEntry< K, V > > &collection)
Assignment Operator, copy element from the source collection to this collection after clearing any element stored in this collection.
virtual bool containsAll (const Collection< MapEntry< K, V > > &collection) const
Returns true if this collection contains all of the elements in the specified collection.
Parameters
collection The Collection to compare to this one.
Exceptions
NullPointerException if the Collection contains pointers and the Collection does not allow for NULL elements (optional check).
virtual bool equals (const Collection< MapEntry< K, V > > &collection) const
Answers true if this Collection and the one given are the same size and if each element contained in the Collection given is equal to an element contained in this collection.
virtual void copy (const Collection< MapEntry< K, V > > &collection)
Renders this Collection as a Copy of the given Collection.
virtual bool isEmpty () const
Returns true if this collection contains no elements.
virtual bool add (const MapEntry< K, V > &value DECAF_UNUSED)
virtual bool addAll (const Collection< MapEntry< K, V > > &collection)
Adds all of the elements in the specified collection to this collection.The behavior of this operation is undefined if the specified collection is modified while the operation is in progress. (This implies that the behavior of this call is undefined if the specified collection is this collection, and this collection is nonempty.)
Parameters
collection The Collection whose elements are added to this one.
Returns
true if this collection changed as a result of the call
Exceptions
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
IllegalArgumentException if some property of an element prevents it from being added to this collection
IllegalStateException if an element cannot be added at this time due to insertion restrictions.
virtual bool remove (const MapEntry< K, V > &value)
Removes a single instance of the specified element from the collection.More formally, removes an element e such that (value == NULL ? e == NULL : value == e), if this collection contains one or more such elements. Returns true if this collection contained the specified element (or equivalently, if this collection changed as a result of the call).
Parameters
value The reference to the element to remove from this Collection.
Returns
true if the collection was changed, false otherwise.
Exceptions
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
virtual bool retainAll (const Collection< MapEntry< K, V > > &collection)
Retains only the elements in this collection that are contained in the specified collection (optional operation).In other words, removes from this collection all of its elements that are not contained in the specified collection.
Parameters
collection The Collection whose elements are to be retained.
Returns
true if the collection changed as a result of this call.
Exceptions
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
virtual std::vector< MapEntry
< K, V > > toArray () const
Answers an STL vector containing copies of all elements contained in this Collection.
virtual void lock ()
Locks the object.
virtual bool tryLock ()
Attempts to Lock the object, if the lock is already held by another thread than this method returns false.
virtual void unlock ()
Unlocks the object.
virtual void wait ()
Waits on a signal from this object, which is generated by a call to Notify.
virtual void wait (long long millisecs)
Waits on a signal from this object, which is generated by a call to Notify.
virtual void wait (long long millisecs, int nanos)
Waits on a signal from this object, which is generated by a call to Notify.
virtual void notify ()
Signals a waiter on this object that it can now wake up and continue.
virtual void notifyAll ()
Signals the waiters on this object that it can now wake up and continue.
Additional Inherited Members
Protected Attributes inherited from decaf::util::AbstractCollection< MapEntry< K, V > >
util::concurrent::Mutex mutex
Constructor & Destructor Documentation
template<typename K, typename V, typename HASHCODE = HashCode<K>> decaf::util::HashMap< K, V, HASHCODE >::ConstHashMapEntrySet::ConstHashMapEntrySet (const HashMap * parent) inline
template<typename K, typename V, typename HASHCODE = HashCode<K>> virtual decaf::util::HashMap< K, V, HASHCODE >::ConstHashMapEntrySet::~ConstHashMapEntrySet () inline virtual
Member Function Documentation
template<typename K, typename V, typename HASHCODE = HashCode<K>> virtual void decaf::util::HashMap< K, V, HASHCODE >::ConstHashMapEntrySet::clear () inline virtual
Removes all of the elements from this collection (optional operation).
The collection will be empty after this method returns.
This implementation iterates over this collection, removing each element using the Iterator.remove operation. Most implementations will probably choose to override this method for efficiency.
Note that this implementation will throw an UnsupportedOperationException if the iterator returned by this collection's iterator method does not implement the remove method and this collection is non-empty.
Exceptions
UnsupportedOperationException if the clear operation is not supported by this collection
Reimplemented from decaf::util::AbstractCollection< MapEntry< K, V > >.
template<typename K, typename V, typename HASHCODE = HashCode<K>> virtual bool decaf::util::HashMap< K, V, HASHCODE >::ConstHashMapEntrySet::contains (const MapEntry< K, V > & value) const inline virtual
Returns true if this collection contains the specified element.More formally, returns true if and only if this collection contains at least one element e such that (value == NULL ? e == NULL : value == e).
Parameters
value The value to check for presence in the collection.
Returns
true if there is at least one of the elements in the collection
Exceptions
NullPointerException if the Collection contains pointers and the Collection does not allow for NULL elements (optional check).
This implementation iterates over the elements in the collection, checking each element in turn for equality with the specified element.
This implementation iterates over the elements in the collection, checking each element in turn for equality with the specified element.
Reimplemented from decaf::util::AbstractCollection< MapEntry< K, V > >.
References decaf::util::HashMap< K, V, HASHCODE >::getEntry(), decaf::util::MapEntry< K, V >::getKey(), decaf::util::MapEntry< K, V >::getValue(), and NULL.
template<typename K, typename V, typename HASHCODE = HashCode<K>> virtual Iterator< MapEntry<K, V> >* decaf::util::HashMap< K, V, HASHCODE >::ConstHashMapEntrySet::iterator () inline virtual
Returns
an iterator over a set of elements of type T.
Implements decaf::lang::Iterable< MapEntry< K, V > >.
template<typename K, typename V, typename HASHCODE = HashCode<K>> virtual Iterator< MapEntry<K, V> >* decaf::util::HashMap< K, V, HASHCODE >::ConstHashMapEntrySet::iterator () const inline virtual
Implements decaf::lang::Iterable< MapEntry< K, V > >.
template<typename K, typename V, typename HASHCODE = HashCode<K>> virtual bool decaf::util::HashMap< K, V, HASHCODE >::ConstHashMapEntrySet::remove (const MapEntry< K, V > &entry DECAF_UNUSED) inline virtual
template<typename K, typename V, typename HASHCODE = HashCode<K>> virtual int decaf::util::HashMap< K, V, HASHCODE >::ConstHashMapEntrySet::size () const inline virtual
Returns the number of elements in this collection.
If this collection contains more than Integer::MAX_VALUE elements, returns Integer::MAX_VALUE.
Returns
the number of elements in this collection
Implements decaf::util::Collection< MapEntry< K, V > >.
References decaf::util::HashMap< K, V, HASHCODE >::elementCount.
The documentation for this class was generated from the following file:
src/main/decaf/util/HashMap.h