activemq-cpp-3.9.0: activemq::cmsutil::CachedProducer Class Reference
activemq::cmsutil::CachedProducer Class Reference
A cached message producer contained within a pooled session.
#include <src/main/activemq/cmsutil/CachedProducer.h>
Public Member Functions
CachedProducer (cms::MessageProducer *producer)
virtual ~CachedProducer ()
virtual void close ()
Does nothing - the real producer resource will be closed by the lifecycle manager.
virtual void send (cms::Message *message)
Sends the message to the default producer destination, but does not take ownership of the message, caller must still destroy it.
virtual void send (cms::Message *message, cms::AsyncCallback *onComplete)
Sends the message to the default producer destination, but does not take ownership of the message, caller must still destroy it.
virtual void send (cms::Message *message, int deliveryMode, int priority, long long timeToLive)
Sends the message to the default producer destination, but does not take ownership of the message, caller must still destroy it.
virtual void send (cms::Message *message, int deliveryMode, int priority, long long timeToLive, cms::AsyncCallback *onComplete)
Sends the message to the default producer destination, but does not take ownership of the message, caller must still destroy it.
virtual void send (const cms::Destination *destination, cms::Message *message)
Sends the message to the designated destination, but does not take ownership of the message, caller must still destroy it.
virtual void send (const cms::Destination *destination, cms::Message *message, cms::AsyncCallback *onComplete)
Sends the message to the designated destination, but does not take ownership of the message, caller must still destroy it.
virtual void send (const cms::Destination *destination, cms::Message *message, int deliveryMode, int priority, long long timeToLive)
Sends the message to the designated destination, but does not take ownership of the message, caller must still destroy it.
virtual void send (const cms::Destination *destination, cms::Message *message, int deliveryMode, int priority, long long timeToLive, cms::AsyncCallback *onComplete)
Sends the message to the designated destination, but does not take ownership of the message, caller must still destroy it.
virtual void setDeliveryMode (int mode)
Sets the delivery mode for this Producer.
virtual int getDeliveryMode () const
Gets the delivery mode for this Producer.
virtual void setDisableMessageID (bool value)
Sets if Message Ids are disabled for this Producer.
virtual bool getDisableMessageID () const
Gets if Message Ids are disabled for this Producer.
virtual void setDisableMessageTimeStamp (bool value)
Sets if Message Time Stamps are disabled for this Producer.
virtual bool getDisableMessageTimeStamp () const
Gets if Message Time Stamps are disabled for this Producer.
virtual void setPriority (int priority)
Sets the Priority that this Producers sends messages at.
virtual int getPriority () const
Gets the Priority level that this producer sends messages at.
virtual void setTimeToLive (long long time)
Sets the Time to Live that this Producers sends messages with.
virtual long long getTimeToLive () const
Gets the Time to Live that this producer sends messages with.
virtual void setMessageTransformer (cms::MessageTransformer *transformer)
Set an MessageTransformer instance that is applied to all cms::Message objects before they are sent on to the CMS bus.
virtual cms::MessageTransformer * getMessageTransformer () const
Gets the currently configured MessageTransformer for this MessageProducer.
Public Member Functions inherited from cms::MessageProducer
virtual ~MessageProducer ()
Public Member Functions inherited from cms::Closeable
virtual ~Closeable ()
Detailed Description
A cached message producer contained within a pooled session.
Constructor & Destructor Documentation
activemq::cmsutil::CachedProducer::CachedProducer (cms::MessageProducer * producer)
virtual activemq::cmsutil::CachedProducer::~CachedProducer () virtual
Member Function Documentation
virtual void activemq::cmsutil::CachedProducer::close () inline virtual
Does nothing - the real producer resource will be closed by the lifecycle manager.
Implements cms::Closeable.
virtual int activemq::cmsutil::CachedProducer::getDeliveryMode () const inline virtual
Gets the delivery mode for this Producer.
Returns
The DeliveryMode
Exceptions
CMSException - if an internal error occurs.
Implements cms::MessageProducer.
References cms::MessageProducer::getDeliveryMode().
virtual bool activemq::cmsutil::CachedProducer::getDisableMessageID () const inline virtual
Gets if Message Ids are disabled for this Producer.
Returns
boolean indicating enable / disable (true / false)
Exceptions
CMSException - if an internal error occurs.
Implements cms::MessageProducer.
References cms::MessageProducer::getDisableMessageID().
virtual bool activemq::cmsutil::CachedProducer::getDisableMessageTimeStamp () const inline virtual
Gets if Message Time Stamps are disabled for this Producer.
Returns
boolean indicating enable / disable (true / false)
Exceptions
CMSException - if an internal error occurs.
Implements cms::MessageProducer.
References cms::MessageProducer::getDisableMessageTimeStamp().
virtual cms::MessageTransformer* activemq::cmsutil::CachedProducer::getMessageTransformer () const inline virtual
Gets the currently configured MessageTransformer for this MessageProducer.
Returns
the pointer to the currently set cms::MessageTransformer.
Implements cms::MessageProducer.
References cms::MessageProducer::getMessageTransformer().
virtual int activemq::cmsutil::CachedProducer::getPriority () const inline virtual
Gets the Priority level that this producer sends messages at.
Returns
int based priority level
Exceptions
CMSException - if an internal error occurs.
Implements cms::MessageProducer.
References cms::MessageProducer::getPriority().
virtual long long activemq::cmsutil::CachedProducer::getTimeToLive () const inline virtual
Gets the Time to Live that this producer sends messages with.
Returns
Time to live value in milliseconds
Exceptions
CMSException - if an internal error occurs.
Implements cms::MessageProducer.
References cms::MessageProducer::getTimeToLive().
virtual void activemq::cmsutil::CachedProducer::send (cms::Message * message) inline virtual
Sends the message to the default producer destination, but does not take ownership of the message, caller must still destroy it.
Uses default values for deliveryMode, priority, and time to live.
Parameters
message The message to be sent.
Exceptions
CMSException - if an internal error occurs while sending the message.
MessageFormatException - if an Invalid Message is given.
InvalidDestinationException - if a client uses this method with a MessageProducer with an invalid destination.
UnsupportedOperationException - if a client uses this method with a MessageProducer that did not specify a destination at creation time.
Implements cms::MessageProducer.
References cms::MessageProducer::send().
virtual void activemq::cmsutil::CachedProducer::send (cms::Message * message, cms::AsyncCallback * onComplete) inline virtual
Sends the message to the default producer destination, but does not take ownership of the message, caller must still destroy it.
Uses default values for deliveryMode, priority, and time to live. If the AsyncCallback parameter is set this method will return immediately and the call-back will be notified once the CMS Provider as acknowledge receipt of the Message or an Error occurs.
Parameters
message The message to be sent.
onComplete The AsyncCallback instance to notify on send complete or error, caller retains ownership of this pointer and must destroy it only after the send completes or the connection is closed.
Exceptions
CMSException - if an internal error occurs while sending the message.
MessageFormatException - if an Invalid Message is given.
InvalidDestinationException - if a client uses this method with a MessageProducer with an invalid destination.
UnsupportedOperationException - if a client uses this method with a MessageProducer that did not specify a destination at creation time.
Implements cms::MessageProducer.
References cms::MessageProducer::send().
virtual void activemq::cmsutil::CachedProducer::send (cms::Message * message, int deliveryMode, int priority, long long timeToLive) inline virtual
Sends the message to the default producer destination, but does not take ownership of the message, caller must still destroy it.
Parameters
message The message to be sent.
deliveryMode The delivery mode to be used.
priority The priority for this message.
timeToLive The time to live value for this message in milliseconds.
Exceptions
CMSException - if an internal error occurs while sending the message.
MessageFormatException - if an Invalid Message is given.
InvalidDestinationException - if a client uses this method with a MessageProducer with an invalid destination.
UnsupportedOperationException - if a client uses this method with a MessageProducer that did not specify a destination at creation time.
Implements cms::MessageProducer.
References cms::MessageProducer::send().
virtual void activemq::cmsutil::CachedProducer::send (cms::Message * message, int deliveryMode, int priority, long long timeToLive, cms::AsyncCallback * onComplete) inline virtual
Sends the message to the default producer destination, but does not take ownership of the message, caller must still destroy it.
If the AsyncCallback parameter is set this method will return immediately and the call-back will be notified once the CMS Provider as acknowledge receipt of the Message or an Error occurs.
Parameters
message The message to be sent.
deliveryMode The delivery mode to be used.
priority The priority for this message.
timeToLive The time to live value for this message in milliseconds.
onComplete The AsyncCallback instance to notify on send complete or error, caller retains ownership of this pointer and must destroy it only after the send completes or the connection is closed.
Exceptions
CMSException - if an internal error occurs while sending the message.
MessageFormatException - if an Invalid Message is given.
InvalidDestinationException - if a client uses this method with a MessageProducer with an invalid destination.
UnsupportedOperationException - if a client uses this method with a MessageProducer that did not specify a destination at creation time.
Implements cms::MessageProducer.
References cms::MessageProducer::send().
virtual void activemq::cmsutil::CachedProducer::send (const cms::Destination * destination, cms::Message * message) inline virtual
Sends the message to the designated destination, but does not take ownership of the message, caller must still destroy it.
Uses default values for deliveryMode, priority, and time to live.
Parameters
destination The destination on which to send the message
message the message to be sent.
Exceptions
CMSException - if an internal error occurs while sending the message.
MessageFormatException - if an Invalid Message is given.
InvalidDestinationException - if a client uses this method with a MessageProducer with an invalid destination.
UnsupportedOperationException - if a client uses this method with a MessageProducer that did not specify a destination at creation time.
Implements cms::MessageProducer.
References cms::MessageProducer::send().
virtual void activemq::cmsutil::CachedProducer::send (const cms::Destination * destination, cms::Message * message, cms::AsyncCallback * onComplete) inline virtual
Sends the message to the designated destination, but does not take ownership of the message, caller must still destroy it.
Uses default values for deliveryMode, priority, and time to live. If the AsyncCallback parameter is set this method will return immediately and the call-back will be notified once the CMS Provider as acknowledge receipt of the Message or an Error occurs.
Parameters
destination The destination on which to send the message
message the message to be sent.
onComplete The AsyncCallback instance to notify on send complete or error, caller retains ownership of this pointer and must destroy it only after the send completes or the connection is closed.
Exceptions
CMSException - if an internal error occurs while sending the message.
MessageFormatException - if an Invalid Message is given.
InvalidDestinationException - if a client uses this method with a MessageProducer with an invalid destination.
UnsupportedOperationException - if a client uses this method with a MessageProducer that did not specify a destination at creation time.
Implements cms::MessageProducer.
References cms::MessageProducer::send().
virtual void activemq::cmsutil::CachedProducer::send (const cms::Destination * destination, cms::Message * message, int deliveryMode, int priority, long long timeToLive) inline virtual
Sends the message to the designated destination, but does not take ownership of the message, caller must still destroy it.
Parameters
destination The destination on which to send the message
message The message to be sent.
deliveryMode The delivery mode to be used.
priority The priority for this message.
timeToLive The time to live value for this message in milliseconds.
Exceptions
CMSException - if an internal error occurs while sending the message.
MessageFormatException - if an Invalid Message is given.
InvalidDestinationException - if a client uses this method with a MessageProducer with an invalid destination.
UnsupportedOperationException - if a client uses this method with a MessageProducer that did not specify a destination at creation time.
Implements cms::MessageProducer.
References cms::MessageProducer::send().
virtual void activemq::cmsutil::CachedProducer::send (const cms::Destination * destination, cms::Message * message, int deliveryMode, int priority, long long timeToLive, cms::AsyncCallback * onComplete) inline virtual
Sends the message to the designated destination, but does not take ownership of the message, caller must still destroy it.
If the AsyncCallback parameter is set this method will return immediately and the call-back will be notified once the CMS Provider as acknowledge receipt of the Message or an Error occurs.
Parameters
destination The destination on which to send the message
message The message to be sent.
deliveryMode The delivery mode to be used.
priority The priority for this message.
timeToLive The time to live value for this message in milliseconds.
onComplete The AsyncCallback instance to notify on send complete or error, caller retains ownership of this pointer and must destroy it only after the send completes or the connection is closed.
Exceptions
CMSException - if an internal error occurs while sending the message.
MessageFormatException - if an Invalid Message is given.
InvalidDestinationException - if a client uses this method with a MessageProducer with an invalid destination.
UnsupportedOperationException - if a client uses this method with a MessageProducer that did not specify a destination at creation time.
Implements cms::MessageProducer.
References cms::MessageProducer::send().
virtual void activemq::cmsutil::CachedProducer::setDeliveryMode (int mode) inline virtual
Sets the delivery mode for this Producer.
Parameters
mode The DeliveryMode
Exceptions
CMSException - if an internal error occurs.
Implements cms::MessageProducer.
References cms::MessageProducer::setDeliveryMode().
virtual void activemq::cmsutil::CachedProducer::setDisableMessageID (bool value) inline virtual
Sets if Message Ids are disabled for this Producer.
Parameters
value boolean indicating enable / disable (true / false)
Exceptions
CMSException - if an internal error occurs.
Implements cms::MessageProducer.
References cms::MessageProducer::setDisableMessageID().
virtual void activemq::cmsutil::CachedProducer::setDisableMessageTimeStamp (bool value) inline virtual
Sets if Message Time Stamps are disabled for this Producer.
Parameters
value - boolean indicating enable / disable (true / false)
Exceptions
CMSException - if an internal error occurs.
Implements cms::MessageProducer.
References cms::MessageProducer::setDisableMessageTimeStamp().
virtual void activemq::cmsutil::CachedProducer::setMessageTransformer (cms::MessageTransformer * transformer) inline virtual
Set an MessageTransformer instance that is applied to all cms::Message objects before they are sent on to the CMS bus.
The CMS code never takes ownership of the MessageTransformer pointer which implies that the client code must ensure that the object remains valid for the lifetime of the CMS object to which the MessageTransformer has been assigned.
Parameters
transformer Pointer to the cms::MessageTransformer to apply on each cms:;MessageSend.
Implements cms::MessageProducer.
References cms::MessageProducer::setMessageTransformer().
virtual void activemq::cmsutil::CachedProducer::setPriority (int priority) inline virtual
Sets the Priority that this Producers sends messages at.
Parameters
priority int value for Priority level
Exceptions
CMSException - if an internal error occurs.
Implements cms::MessageProducer.
References cms::MessageProducer::setPriority().
virtual void activemq::cmsutil::CachedProducer::setTimeToLive (long long time) inline virtual
Sets the Time to Live that this Producers sends messages with.
This value will be used if the time to live is not specified via the send method.
Parameters
time default time to live value in milliseconds
Exceptions
CMSException - if an internal error occurs.
Implements cms::MessageProducer.
References cms::MessageProducer::setTimeToLive().
The documentation for this class was generated from the following file:
src/main/activemq/cmsutil/CachedProducer.h