activemq-cpp-3.9.0: decaf::util::concurrent::CopyOnWriteArrayList< E > Class Template Reference
decaf::util::concurrent::CopyOnWriteArrayList< E > Class Template Reference
#include <src/main/decaf/util/concurrent/CopyOnWriteArrayList.h>
Data Structures
class ArrayListIterator
Public Member Functions
CopyOnWriteArrayList ()
CopyOnWriteArrayList (const Collection< E > &collection)
CopyOnWriteArrayList (const CopyOnWriteArrayList< E > &collection)
CopyOnWriteArrayList (const E *array, int size)
virtual ~CopyOnWriteArrayList ()
CopyOnWriteArrayList< E > & operator= (const CopyOnWriteArrayList< E > &list)
CopyOnWriteArrayList< E > & operator= (const Collection< E > &list)
virtual void copy (const Collection< E > &collection)
Renders this Collection as a Copy of the given Collection.
virtual bool add (const E &value)
Returns true if this collection changed as a result of the call.
virtual bool addAll (const Collection< E > &collection)
Adds all of the elements in the specified collection to this collection.
virtual void clear ()
Removes all of the elements from this collection (optional operation).
virtual bool contains (const E &value) const
Returns true if this collection contains the specified element.
virtual bool containsAll (const Collection< E > &collection) const
Returns true if this collection contains all of the elements in the specified collection.
virtual bool equals (const Collection< E > &collection) const
Compares the passed collection to this one, if they contain the same elements, i.e.
virtual bool isEmpty () const
virtual bool remove (const E &value)
Removes a single instance of the specified element from the collection.
virtual bool removeAll (const Collection< E > &collection)
Removes all this collection's elements that are also contained in the specified collection (optional operation).
virtual bool retainAll (const Collection< E > &collection)
Retains only the elements in this collection that are contained in the specified collection (optional operation).
virtual int size () const
Returns the number of elements in this collection.
virtual std::vector< E > toArray () const
Returns an array containing all of the elements in this collection.
virtual decaf::util::Iterator
< E > * iterator ()
virtual decaf::util::Iterator
< E > * iterator () const
virtual ListIterator< E > * listIterator ()
virtual ListIterator< E > * listIterator () const
virtual ListIterator< E > * listIterator (int index)
virtual ListIterator< E > * listIterator (int index) const
virtual int indexOf (const E &value) const
Returns the index of the first occurrence of the specified element in this list, or -1 if this list does not contain the element.
virtual int lastIndexOf (const E &value) const
Returns the index of the last occurrence of the specified element in this list, or -1 if this list does not contain the element.
virtual E get (int index) const
Gets the element contained at position passed.
virtual E set (int index, const E &element)
Replaces the element at the specified position in this list with the specified element.
virtual void add (int index, const E &element)
Inserts the specified element at the specified position in this list.
virtual bool addAll (int index, const Collection< E > &collection)
Inserts all of the elements in the specified collection into this list at the specified position (optional operation).
virtual E removeAt (int index)
Removes the element at the specified position in this list.
virtual std::string toString () const
bool addIfAbsent (const E &value)
Adds the given value to the end of this List if it is not already contained in this List.
int addAllAbsent (const Collection< E > &collection)
Every element in the given collection that is not already contained in this Collection is added to the end of this collection.
int lastIndexOf (const E &value, int index)
Searches backwards through the List for the given element starting at the index specified.
int indexOf (const E &value, int index) const
Searches the List starting from the specified index and returns the index of the first item in the list that is equal to the given value.
virtual void lock ()
Locks the object.
virtual bool tryLock ()
Attempts to Lock the object, if the lock is already held by another thread than this method returns false.
virtual void unlock ()
Unlocks the object.
virtual void wait ()
Waits on a signal from this object, which is generated by a call to Notify.
virtual void wait (long long millisecs)
Waits on a signal from this object, which is generated by a call to Notify.
virtual void wait (long long millisecs, int nanos)
Waits on a signal from this object, which is generated by a call to Notify.
virtual void notify ()
Signals a waiter on this object that it can now wake up and continue.
virtual void notifyAll ()
Signals the waiters on this object that it can now wake up and continue.
Public Member Functions inherited from decaf::util::List< E >
List ()
virtual ~List ()
Public Member Functions inherited from decaf::util::Collection< E >
virtual ~Collection ()
Public Member Functions inherited from decaf::lang::Iterable< E >
virtual ~Iterable ()
Public Member Functions inherited from decaf::util::concurrent::Synchronizable
virtual ~Synchronizable ()
Constructor & Destructor Documentation
template<typename E> decaf::util::concurrent::CopyOnWriteArrayList< E >::CopyOnWriteArrayList () inline
References decaf::util::concurrent::locks::Lock::newCondition(), decaf::lang::Pointer< T, REFCOUNTER >::reset(), and decaf::util::concurrent::locks::ReentrantReadWriteLock::writeLock().
template<typename E> decaf::util::concurrent::CopyOnWriteArrayList< E >::CopyOnWriteArrayList (const Collection< E > & collection) inline
References decaf::util::concurrent::locks::Lock::newCondition(), decaf::lang::Pointer< T, REFCOUNTER >::reset(), and decaf::util::concurrent::locks::ReentrantReadWriteLock::writeLock().
template<typename E> decaf::util::concurrent::CopyOnWriteArrayList< E >::CopyOnWriteArrayList (const CopyOnWriteArrayList< E > & collection) inline
References decaf::util::concurrent::locks::Lock::newCondition(), decaf::lang::Pointer< T, REFCOUNTER >::reset(), and decaf::util::concurrent::locks::ReentrantReadWriteLock::writeLock().
template<typename E> decaf::util::concurrent::CopyOnWriteArrayList< E >::CopyOnWriteArrayList (const E * array, int size) inline
References decaf::util::concurrent::locks::Lock::newCondition(), decaf::lang::Pointer< T, REFCOUNTER >::reset(), decaf::util::concurrent::CopyOnWriteArrayList< E >::size(), decaf::lang::Pointer< T, REFCOUNTER >::swap(), and decaf::util::concurrent::locks::ReentrantReadWriteLock::writeLock().
template<typename E> virtual decaf::util::concurrent::CopyOnWriteArrayList< E >::~CopyOnWriteArrayList () inline virtual
References NULL, and decaf::lang::Pointer< T, REFCOUNTER >::reset().
Member Function Documentation
template<typename E> virtual bool decaf::util::concurrent::CopyOnWriteArrayList< E >::add (const E & value) inline virtual
Returns true if this collection changed as a result of the call.
(Returns false if this collection does not permit duplicates and already contains the specified element.)
Collections that support this operation may place limitations on what elements may be added to this collection. In particular, some collections will refuse to add null elements, and others will impose restrictions on the type of elements that may be added. Collection classes should clearly specify in their documentation any restrictions on what elements may be added.
If a collection refuses to add a particular element for any reason other than that it already contains the element, it must throw an exception (rather than returning false). This preserves the invariant that a collection always contains the specified element after this call returns.
For non-pointer values, i.e. class instances or string's the object will be copied into the collection, thus the object must support being copied, must not hide the copy constructor and assignment operator.
Parameters
value The reference to the element to add to this Collection.
Returns
true if the element was added to this Collection.
Exceptions
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
IllegalArgumentException if some property of the element prevents it from being added to this collection
IllegalStateException if the element cannot be added at this time due to insertion restrictions.
Implements decaf::util::Collection< E >.
References decaf::util::concurrent::locks::Lock::lock(), decaf::util::concurrent::CopyOnWriteArrayList< E >::size(), decaf::lang::Pointer< T, REFCOUNTER >::swap(), decaf::util::concurrent::locks::Lock::unlock(), and decaf::util::concurrent::locks::ReentrantReadWriteLock::writeLock().
template<typename E> virtual void decaf::util::concurrent::CopyOnWriteArrayList< E >::add (int index, const E & element) inline virtual
Inserts the specified element at the specified position in this list.
Shifts the element currently at that position (if any) and any subsequent elements to the right (adds one to their indices).
Parameters
index The index at which the specified element is to be inserted.
element The element to be inserted in this List.
Exceptions
IndexOutOfBoundsException if the index is greater than size of the List.
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
IllegalArgumentException if some property of the element prevents it from being added to this collection
IllegalStateException if the element cannot be added at this time due to insertion restrictions.
Implements decaf::util::List< E >.
References decaf::util::concurrent::locks::Lock::lock(), decaf::util::concurrent::CopyOnWriteArrayList< E >::size(), decaf::lang::Pointer< T, REFCOUNTER >::swap(), decaf::util::concurrent::locks::Lock::unlock(), and decaf::util::concurrent::locks::ReentrantReadWriteLock::writeLock().
template<typename E> virtual bool decaf::util::concurrent::CopyOnWriteArrayList< E >::addAll (const Collection< E > & collection) inline virtual
Adds all of the elements in the specified collection to this collection.
The behavior of this operation is undefined if the specified collection is modified while the operation is in progress. (This implies that the behavior of this call is undefined if the specified collection is this collection, and this collection is nonempty.)
Parameters
collection The Collection whose elements are added to this one.
Returns
true if this collection changed as a result of the call
Exceptions
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
IllegalArgumentException if some property of an element prevents it from being added to this collection
IllegalStateException if an element cannot be added at this time due to insertion restrictions.
Implements decaf::util::Collection< E >.
References decaf::lang::Iterable< E >::iterator(), decaf::util::concurrent::locks::Lock::lock(), decaf::util::Collection< E >::size(), decaf::util::concurrent::CopyOnWriteArrayList< E >::size(), decaf::lang::Pointer< T, REFCOUNTER >::swap(), decaf::util::concurrent::locks::Lock::unlock(), and decaf::util::concurrent::locks::ReentrantReadWriteLock::writeLock().
template<typename E> virtual bool decaf::util::concurrent::CopyOnWriteArrayList< E >::addAll (int index, const Collection< E > & source) inline virtual
Inserts all of the elements in the specified collection into this list at the specified position (optional operation).
Shifts the element currently at that position (if any) and any subsequent elements to the right (increases their indices). The new elements will appear in this list in the order that they are returned by the specified collection's iterator. The behavior of this operation is undefined if the specified collection is modified while the operation is in progress. (Note that this will occur if the specified collection is this list, and it's nonempty.)
Parameters
index The index at which to insert the first element from the specified collection
source The Collection containing elements to be added to this list
Returns
true if this list changed as a result of the call
Exceptions
IndexOutOfBoundsException if the index given is less than zero or greater than the List size.
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
IllegalArgumentException if some property of the element prevents it from being added to this collection
IllegalStateException if the element cannot be added at this time due to insertion restrictions.
Implements decaf::util::List< E >.
References decaf::lang::System::arraycopy(), decaf::lang::Iterable< E >::iterator(), decaf::util::concurrent::locks::Lock::lock(), decaf::util::Collection< E >::size(), decaf::util::concurrent::CopyOnWriteArrayList< E >::size(), decaf::lang::Pointer< T, REFCOUNTER >::swap(), decaf::util::concurrent::locks::Lock::unlock(), and decaf::util::concurrent::locks::ReentrantReadWriteLock::writeLock().
template<typename E> int decaf::util::concurrent::CopyOnWriteArrayList< E >::addAllAbsent (const Collection< E > & collection) inline
Every element in the given collection that is not already contained in this Collection is added to the end of this collection.
The order that the elements are added is ditacted by the order that the collection's iterator returns them.
Parameters
collection The collection whose elements are to be added if not already in this List.
Returns
the number of elements that are added to this List.
References decaf::lang::System::arraycopy(), decaf::util::concurrent::CopyOnWriteArrayList< E >::indexOf(), decaf::lang::Iterable< E >::iterator(), decaf::util::concurrent::locks::Lock::lock(), decaf::util::Collection< E >::size(), decaf::util::concurrent::CopyOnWriteArrayList< E >::size(), decaf::lang::Pointer< T, REFCOUNTER >::swap(), decaf::util::concurrent::locks::Lock::unlock(), and decaf::util::concurrent::locks::ReentrantReadWriteLock::writeLock().
template<typename E> bool decaf::util::concurrent::CopyOnWriteArrayList< E >::addIfAbsent (const E & value) inline
Adds the given value to the end of this List if it is not already contained in this List.
Parameters
value The element to be added if not already contained in this List.
Returns
true if the element is added to this List.
References decaf::util::concurrent::CopyOnWriteArrayList< E >::indexOf(), decaf::util::concurrent::locks::Lock::lock(), decaf::util::concurrent::CopyOnWriteArrayList< E >::size(), decaf::lang::Pointer< T, REFCOUNTER >::swap(), decaf::util::concurrent::locks::Lock::unlock(), and decaf::util::concurrent::locks::ReentrantReadWriteLock::writeLock().
template<typename E> virtual void decaf::util::concurrent::CopyOnWriteArrayList< E >::clear () inline virtual
Removes all of the elements from this collection (optional operation).
This collection will be empty after this method returns unless it throws an exception.
Exceptions
UnsupportedOperationExceptio if this is an unmodifiable collection.
Implements decaf::util::Collection< E >.
References decaf::util::concurrent::locks::Lock::lock(), decaf::lang::Pointer< T, REFCOUNTER >::swap(), decaf::util::concurrent::locks::Lock::unlock(), and decaf::util::concurrent::locks::ReentrantReadWriteLock::writeLock().
Referenced by decaf::util::concurrent::CopyOnWriteArrayList< E >::copy(), and decaf::util::concurrent::CopyOnWriteArrayList< E >::operator=().
template<typename E> virtual bool decaf::util::concurrent::CopyOnWriteArrayList< E >::contains (const E & value) const inline virtual
Returns true if this collection contains the specified element.
More formally, returns true if and only if this collection contains at least one element e such that (value == NULL ? e == NULL : value == e).
Parameters
value The value to check for presence in the collection.
Returns
true if there is at least one of the elements in the collection
Exceptions
NullPointerException if the Collection contains pointers and the Collection does not allow for NULL elements (optional check).
Implements decaf::util::Collection< E >.
References decaf::util::concurrent::locks::Lock::lock(), decaf::util::concurrent::locks::ReentrantReadWriteLock::readLock(), and decaf::util::concurrent::locks::Lock::unlock().
Referenced by decaf::util::concurrent::CopyOnWriteArrayList< E >::containsAll().
template<typename E> virtual bool decaf::util::concurrent::CopyOnWriteArrayList< E >::containsAll (const Collection< E > & collection) const inline virtual
Returns true if this collection contains all of the elements in the specified collection.
Parameters
collection The Collection to compare to this one.
Exceptions
NullPointerException if the Collection contains pointers and the Collection does not allow for NULL elements (optional check).
Implements decaf::util::Collection< E >.
References decaf::util::concurrent::CopyOnWriteArrayList< E >::contains(), and decaf::lang::Iterable< E >::iterator().
template<typename E> virtual void decaf::util::concurrent::CopyOnWriteArrayList< E >::copy (const Collection< E > & collection) inline virtual
Renders this Collection as a Copy of the given Collection.
Parameters
collection The collection to mirror.
Exceptions
UnsupportedOperationExceptio if this is an unmodifiable collection.
IllegalStateException if the elements cannot be added at this time due to insertion restrictions.
Implements decaf::util::Collection< E >.
References decaf::util::concurrent::CopyOnWriteArrayList< E >::clear(), decaf::util::concurrent::locks::Lock::lock(), decaf::util::concurrent::locks::Lock::unlock(), and decaf::util::concurrent::locks::ReentrantReadWriteLock::writeLock().
template<typename E> virtual bool decaf::util::concurrent::CopyOnWriteArrayList< E >::equals (const Collection< E > & value) const inline virtual
Compares the passed collection to this one, if they contain the same elements, i.e.
all their elements are equivalent, then it returns true.
Returns
true if the Collections contain the same elements.
Implements decaf::util::Collection< E >.
References decaf::lang::Iterable< E >::iterator(), decaf::util::concurrent::CopyOnWriteArrayList< E >::iterator(), NULL, decaf::util::Collection< E >::size(), and decaf::util::concurrent::CopyOnWriteArrayList< E >::size().
template<typename E> virtual E decaf::util::concurrent::CopyOnWriteArrayList< E >::get (int index) const inline virtual
Gets the element contained at position passed.
Parameters
index The position to get.
Returns
value at index specified.
Exceptions
IndexOutOfBoundsException if the index given is less than zero or greater than the List size.
Implements decaf::util::List< E >.
References decaf::util::concurrent::locks::Lock::lock(), decaf::util::concurrent::locks::ReentrantReadWriteLock::readLock(), and decaf::util::concurrent::locks::Lock::unlock().
template<typename E> virtual int decaf::util::concurrent::CopyOnWriteArrayList< E >::indexOf (const E & value) const inline virtual
Returns the index of the first occurrence of the specified element in this list, or -1 if this list does not contain the element.
More formally, returns the lowest index i such that get(i) == value, or -1 if there is no such index.
Parameters
value The element to search for in this List.
Returns
the index of the first occurrence of the specified element in this list,
Exceptions
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
Implements decaf::util::List< E >.
References decaf::util::concurrent::locks::Lock::lock(), decaf::util::concurrent::locks::ReentrantReadWriteLock::readLock(), and decaf::util::concurrent::locks::Lock::unlock().
Referenced by decaf::util::concurrent::CopyOnWriteArrayList< E >::addAllAbsent(), decaf::util::concurrent::CopyOnWriteArrayList< E >::addIfAbsent(), and decaf::util::concurrent::CopyOnWriteArrayList< E >::remove().
template<typename E> int decaf::util::concurrent::CopyOnWriteArrayList< E >::indexOf (const E & value, int index) const inline
Searches the List starting from the specified index and returns the index of the first item in the list that is equal to the given value.
Parameters
value The value to search for in the List.
index The index in the List to begin the search from.
Returns
the index in the List that matches the given element or -1 if not found.
Exceptions
IndexOutOfBoundsException if the given index is negative.
References decaf::util::concurrent::locks::Lock::lock(), decaf::util::concurrent::locks::ReentrantReadWriteLock::readLock(), and decaf::util::concurrent::locks::Lock::unlock().
template<typename E> virtual bool decaf::util::concurrent::CopyOnWriteArrayList< E >::isEmpty () const inline virtual
Returns
true if this collection contains no elements.
Implements decaf::util::Collection< E >.
References decaf::util::concurrent::locks::Lock::lock(), decaf::util::concurrent::locks::ReentrantReadWriteLock::readLock(), and decaf::util::concurrent::locks::Lock::unlock().
template<typename E> virtual decaf::util::Iterator<E>* decaf::util::concurrent::CopyOnWriteArrayList< E >::iterator () inline virtual
Returns
an iterator over a set of elements of type T.
Implements decaf::lang::Iterable< E >.
References decaf::util::concurrent::locks::Lock::lock(), decaf::util::concurrent::locks::ReentrantReadWriteLock::readLock(), and decaf::util::concurrent::locks::Lock::unlock().
Referenced by decaf::util::concurrent::CopyOnWriteArrayList< E >::equals().
template<typename E> virtual decaf::util::Iterator<E>* decaf::util::concurrent::CopyOnWriteArrayList< E >::iterator () const inline virtual
Implements decaf::lang::Iterable< E >.
References decaf::util::concurrent::locks::Lock::lock(), decaf::util::concurrent::locks::ReentrantReadWriteLock::readLock(), and decaf::util::concurrent::locks::Lock::unlock().
template<typename E> virtual int decaf::util::concurrent::CopyOnWriteArrayList< E >::lastIndexOf (const E & value) const inline virtual
Returns the index of the last occurrence of the specified element in this list, or -1 if this list does not contain the element.
More formally, returns the highest index i such that get(i) == value or -1 if there is no such index.
Parameters
value The element to search for in this List.
Returns
the index of the last occurrence of the specified element in this list.
Exceptions
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
Implements decaf::util::List< E >.
References decaf::util::concurrent::locks::Lock::lock(), decaf::util::concurrent::locks::ReentrantReadWriteLock::readLock(), and decaf::util::concurrent::locks::Lock::unlock().
template<typename E> int decaf::util::concurrent::CopyOnWriteArrayList< E >::lastIndexOf (const E & value, int index) inline
Searches backwards through the List for the given element starting at the index specified.
Parameters
value The value to search for in the List.
index The index in the list to begin the search from.
Returns
the index in the list that matches the value given, or -1 if not found.
Exceptions
IndexOutOfBoundsException if the given index is greater than or equal to the List size.
References decaf::util::concurrent::locks::Lock::lock(), decaf::util::concurrent::locks::ReentrantReadWriteLock::readLock(), and decaf::util::concurrent::locks::Lock::unlock().
template<typename E> virtual ListIterator<E>* decaf::util::concurrent::CopyOnWriteArrayList< E >::listIterator () inline virtual
Returns
a list iterator over the elements in this list (in proper sequence).
Implements decaf::util::List< E >.
References decaf::util::concurrent::locks::Lock::lock(), decaf::util::concurrent::locks::ReentrantReadWriteLock::readLock(), and decaf::util::concurrent::locks::Lock::unlock().
template<typename E> virtual ListIterator<E>* decaf::util::concurrent::CopyOnWriteArrayList< E >::listIterator () const inline virtual
Implements decaf::util::List< E >.
References decaf::util::concurrent::locks::Lock::lock(), decaf::util::concurrent::locks::ReentrantReadWriteLock::readLock(), and decaf::util::concurrent::locks::Lock::unlock().
template<typename E> virtual ListIterator<E>* decaf::util::concurrent::CopyOnWriteArrayList< E >::listIterator (int index) inline virtual
Parameters
index index of first element to be returned from the list iterator (by a call to the next method).
Returns
a list iterator of the elements in this list (in proper sequence), starting at the specified position in this list. The specified index indicates the first element that would be returned by an initial call to next. An initial call to previous would return the element with the specified index minus one.
Exceptions
IndexOutOfBoundsException if the index is out of range (index < 0 || index > size())
Implements decaf::util::List< E >.
References decaf::util::concurrent::locks::Lock::lock(), decaf::util::concurrent::locks::ReentrantReadWriteLock::readLock(), and decaf::util::concurrent::locks::Lock::unlock().
template<typename E> virtual ListIterator<E>* decaf::util::concurrent::CopyOnWriteArrayList< E >::listIterator (int index) const inline virtual
Implements decaf::util::List< E >.
References decaf::util::concurrent::locks::Lock::lock(), decaf::util::concurrent::locks::ReentrantReadWriteLock::readLock(), and decaf::util::concurrent::locks::Lock::unlock().
template<typename E> virtual void decaf::util::concurrent::CopyOnWriteArrayList< E >::lock () inline virtual
Locks the object.
Exceptions
RuntimeException if an error occurs while locking the object.
Implements decaf::util::concurrent::Synchronizable.
References decaf::util::concurrent::locks::Lock::lock(), and decaf::util::concurrent::locks::ReentrantReadWriteLock::writeLock().
template<typename E> virtual void decaf::util::concurrent::CopyOnWriteArrayList< E >::notify () inline virtual
Signals a waiter on this object that it can now wake up and continue.
Must have this object locked before calling.
Exceptions
IllegalMonitorStateException - if the current thread is not the owner of the the Synchronizable Object.
RuntimeException if an error occurs while notifying one of the waiting threads.
Implements decaf::util::concurrent::Synchronizable.
References decaf::util::concurrent::locks::Condition::signal().
template<typename E> virtual void decaf::util::concurrent::CopyOnWriteArrayList< E >::notifyAll () inline virtual
Signals the waiters on this object that it can now wake up and continue.
Must have this object locked before calling.
Exceptions
IllegalMonitorStateException - if the current thread is not the owner of the the Synchronizable Object.
RuntimeException if an error occurs while notifying the waiting threads.
Implements decaf::util::concurrent::Synchronizable.
References decaf::util::concurrent::locks::Condition::signalAll().
template<typename E> CopyOnWriteArrayList<E>& decaf::util::concurrent::CopyOnWriteArrayList< E >::operator= (const CopyOnWriteArrayList< E > & list) inline
References decaf::util::concurrent::CopyOnWriteArrayList< E >::clear(), decaf::util::concurrent::locks::Lock::lock(), decaf::util::concurrent::locks::Lock::unlock(), and decaf::util::concurrent::locks::ReentrantReadWriteLock::writeLock().
template<typename E> CopyOnWriteArrayList<E>& decaf::util::concurrent::CopyOnWriteArrayList< E >::operator= (const Collection< E > & list) inline
References decaf::util::concurrent::CopyOnWriteArrayList< E >::clear(), decaf::util::concurrent::locks::Lock::lock(), decaf::util::concurrent::locks::Lock::unlock(), and decaf::util::concurrent::locks::ReentrantReadWriteLock::writeLock().
template<typename E> virtual bool decaf::util::concurrent::CopyOnWriteArrayList< E >::remove (const E & value) inline virtual
Removes a single instance of the specified element from the collection.
More formally, removes an element e such that (value == NULL ? e == NULL : value == e), if this collection contains one or more such elements. Returns true if this collection contained the specified element (or equivalently, if this collection changed as a result of the call).
Parameters
value The reference to the element to remove from this Collection.
Returns
true if the collection was changed, false otherwise.
Exceptions
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
Implements decaf::util::Collection< E >.
References decaf::util::concurrent::CopyOnWriteArrayList< E >::indexOf(), decaf::util::concurrent::locks::Lock::lock(), decaf::util::concurrent::CopyOnWriteArrayList< E >::removeAt(), decaf::util::concurrent::locks::Lock::unlock(), and decaf::util::concurrent::locks::ReentrantReadWriteLock::writeLock().
template<typename E> virtual bool decaf::util::concurrent::CopyOnWriteArrayList< E >::removeAll (const Collection< E > & collection) inline virtual
Removes all this collection's elements that are also contained in the specified collection (optional operation).
After this call returns, this collection will contain no elements in common with the specified collection.
Parameters
collection The Collection whose elements are to be removed from this one.
Returns
true if the collection changed as a result of this call.
Exceptions
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
Implements decaf::util::Collection< E >.
References decaf::util::Collection< E >::contains(), decaf::util::Collection< E >::isEmpty(), decaf::util::concurrent::locks::Lock::lock(), decaf::lang::Pointer< T, REFCOUNTER >::reset(), decaf::util::concurrent::CopyOnWriteArrayList< E >::size(), decaf::lang::Pointer< T, REFCOUNTER >::swap(), decaf::util::concurrent::locks::Lock::unlock(), and decaf::util::concurrent::locks::ReentrantReadWriteLock::writeLock().
template<typename E> virtual E decaf::util::concurrent::CopyOnWriteArrayList< E >::removeAt (int index) inline virtual
Removes the element at the specified position in this list.
Shifts any subsequent elements to the left (subtracts one from their indices). Returns the element that was removed from the list.
Parameters
index - the index of the element to be removed.
Returns
the element previously at the specified position.
Exceptions
IndexOutOfBoundsException if the index given is less than zero or greater than the List size.
UnsupportedOperationExceptio if this is an unmodifiable collection.
Implements decaf::util::List< E >.
References decaf::util::concurrent::locks::Lock::lock(), decaf::lang::Pointer< T, REFCOUNTER >::reset(), decaf::util::concurrent::CopyOnWriteArrayList< E >::size(), decaf::lang::Pointer< T, REFCOUNTER >::swap(), decaf::util::concurrent::locks::Lock::unlock(), and decaf::util::concurrent::locks::ReentrantReadWriteLock::writeLock().
Referenced by decaf::util::concurrent::CopyOnWriteArrayList< E >::remove().
template<typename E> virtual bool decaf::util::concurrent::CopyOnWriteArrayList< E >::retainAll (const Collection< E > & collection) inline virtual
Retains only the elements in this collection that are contained in the specified collection (optional operation).
In other words, removes from this collection all of its elements that are not contained in the specified collection.
Parameters
collection The Collection whose elements are to be retained.
Returns
true if the collection changed as a result of this call.
Exceptions
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
Implements decaf::util::Collection< E >.
References decaf::util::Collection< E >::contains(), decaf::util::Collection< E >::isEmpty(), decaf::util::concurrent::locks::Lock::lock(), decaf::lang::Pointer< T, REFCOUNTER >::reset(), decaf::util::concurrent::CopyOnWriteArrayList< E >::size(), decaf::lang::Pointer< T, REFCOUNTER >::swap(), decaf::util::concurrent::locks::Lock::unlock(), and decaf::util::concurrent::locks::ReentrantReadWriteLock::writeLock().
template<typename E> virtual E decaf::util::concurrent::CopyOnWriteArrayList< E >::set (int index, const E & element) inline virtual
Replaces the element at the specified position in this list with the specified element.
Parameters
index The index of the element to replace.
element The element to be stored at the specified position.
Returns
the element previously at the specified position.
Exceptions
IndexOutOfBoundsException if the index given is less than zero or greater than the List size.
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
IllegalArgumentException if some property of the element prevents it from being added to this collection
IllegalStateException if the element cannot be added at this time due to insertion restrictions.
Implements decaf::util::List< E >.
References decaf::util::concurrent::locks::Lock::lock(), decaf::util::concurrent::CopyOnWriteArrayList< E >::size(), decaf::lang::Pointer< T, REFCOUNTER >::swap(), decaf::util::concurrent::locks::Lock::unlock(), and decaf::util::concurrent::locks::ReentrantReadWriteLock::writeLock().
template<typename E> virtual int decaf::util::concurrent::CopyOnWriteArrayList< E >::size () const inline virtual
Returns the number of elements in this collection.
If this collection contains more than Integer::MAX_VALUE elements, returns Integer::MAX_VALUE.
Returns
the number of elements in this collection
Implements decaf::util::Collection< E >.
References decaf::util::concurrent::locks::Lock::lock(), decaf::util::concurrent::locks::ReentrantReadWriteLock::readLock(), and decaf::util::concurrent::locks::Lock::unlock().
Referenced by decaf::util::concurrent::CopyOnWriteArrayList< E >::add(), decaf::util::concurrent::CopyOnWriteArrayList< E >::addAll(), decaf::util::concurrent::CopyOnWriteArrayList< E >::addAllAbsent(), decaf::util::concurrent::CopyOnWriteArrayList< E >::addIfAbsent(), decaf::util::concurrent::CopyOnWriteArrayList< E >::CopyOnWriteArrayList(), decaf::util::concurrent::CopyOnWriteArrayList< E >::equals(), decaf::util::concurrent::CopyOnWriteArrayList< E >::removeAll(), decaf::util::concurrent::CopyOnWriteArrayList< E >::removeAt(), decaf::util::concurrent::CopyOnWriteArrayList< E >::retainAll(), and decaf::util::concurrent::CopyOnWriteArrayList< E >::set().
template<typename E> virtual std::vector<E> decaf::util::concurrent::CopyOnWriteArrayList< E >::toArray () const inline virtual
Returns an array containing all of the elements in this collection.
If the collection makes any guarantees as to what order its elements are returned by its iterator, this method must return the elements in the same order.
This method acts as bridge between array-based and collection-based APIs.
Returns
an array of the elements in this collection in the form of an STL vector.
Implements decaf::util::Collection< E >.
References decaf::util::concurrent::locks::Lock::lock(), decaf::util::concurrent::locks::ReentrantReadWriteLock::readLock(), and decaf::util::concurrent::locks::Lock::unlock().
template<typename E> virtual std::string decaf::util::concurrent::CopyOnWriteArrayList< E >::toString () const inline virtual
References decaf::util::concurrent::locks::Lock::lock(), decaf::util::concurrent::locks::ReentrantReadWriteLock::readLock(), and decaf::util::concurrent::locks::Lock::unlock().
template<typename E> virtual bool decaf::util::concurrent::CopyOnWriteArrayList< E >::tryLock () inline virtual
Attempts to Lock the object, if the lock is already held by another thread than this method returns false.
Returns
true if the lock was acquired, false if it is already held by another thread.
Exceptions
RuntimeException if an error occurs while locking the object.
Implements decaf::util::concurrent::Synchronizable.
References decaf::util::concurrent::locks::Lock::tryLock(), and decaf::util::concurrent::locks::ReentrantReadWriteLock::writeLock().
template<typename E> virtual void decaf::util::concurrent::CopyOnWriteArrayList< E >::unlock () inline virtual
Unlocks the object.
Exceptions
RuntimeException if an error occurs while unlocking the object.
Implements decaf::util::concurrent::Synchronizable.
References decaf::util::concurrent::locks::Lock::unlock(), and decaf::util::concurrent::locks::ReentrantReadWriteLock::writeLock().
template<typename E> virtual void decaf::util::concurrent::CopyOnWriteArrayList< E >::wait () inline virtual
Waits on a signal from this object, which is generated by a call to Notify.
Must have this object locked before calling.
Exceptions
RuntimeException if an error occurs while waiting on the object.
InterruptedException if the wait is interrupted before it completes.
IllegalMonitorStateException - if the current thread is not the owner of the the Synchronizable Object.
Implements decaf::util::concurrent::Synchronizable.
References decaf::util::concurrent::locks::Condition::await().
template<typename E> virtual void decaf::util::concurrent::CopyOnWriteArrayList< E >::wait (long long millisecs) inline virtual
Waits on a signal from this object, which is generated by a call to Notify.
Must have this object locked before calling. This wait will timeout after the specified time interval.
Parameters
millisecs the time in milliseconds to wait, or WAIT_INIFINITE
Exceptions
RuntimeException if an error occurs while waiting on the object.
InterruptedException if the wait is interrupted before it completes.
IllegalMonitorStateException - if the current thread is not the owner of the the Synchronizable Object.
Implements decaf::util::concurrent::Synchronizable.
References decaf::util::concurrent::locks::Condition::await(), and decaf::util::concurrent::TimeUnit::MILLISECONDS.
template<typename E> virtual void decaf::util::concurrent::CopyOnWriteArrayList< E >::wait (long long millisecs, int nanos) inline virtual
Waits on a signal from this object, which is generated by a call to Notify.
Must have this object locked before calling. This wait will timeout after the specified time interval. This method is similar to the one argument wait function except that it add a finer grained control over the amount of time that it waits by adding in the additional nanosecond argument.
NOTE: The ability to wait accurately at a nanosecond scale depends on the platform and OS that the Decaf API is running on, some systems do not provide an accurate enough clock to provide this level of granularity.
Parameters
millisecs the time in milliseconds to wait, or WAIT_INIFINITE
nanos additional time in nanoseconds with a range of 0-999999
Exceptions
IllegalArgumentException if an error occurs or the nanos argument is not in the range of [0-999999]
RuntimeException if an error occurs while waiting on the object.
InterruptedException if the wait is interrupted before it completes.
IllegalMonitorStateException - if the current thread is not the owner of the the Synchronizable Object.
Implements decaf::util::concurrent::Synchronizable.
References decaf::util::concurrent::locks::Condition::awaitNanos(), decaf::util::concurrent::TimeUnit::MILLISECONDS, and decaf::util::concurrent::TimeUnit::toNanos().
The documentation for this class was generated from the following file:
src/main/decaf/util/concurrent/CopyOnWriteArrayList.h