activemq-cpp-3.9.0: activemq::commands::BaseDataStructure Class Reference
activemq::commands::BaseDataStructure Class Reference
#include <src/main/activemq/commands/BaseDataStructure.h>
Public Member Functions
virtual ~BaseDataStructure ()
virtual bool isMarshalAware () const
Determine if the class implementing this interface is really wanting to be told about marshaling.
virtual void beforeMarshal (wireformat::WireFormat *wireFormat AMQCPP_UNUSED)
virtual void afterMarshal (wireformat::WireFormat *wireFormat AMQCPP_UNUSED)
virtual void beforeUnmarshal (wireformat::WireFormat *wireFormat AMQCPP_UNUSED)
virtual void afterUnmarshal (wireformat::WireFormat *wireFormat AMQCPP_UNUSED)
virtual void setMarshaledForm (wireformat::WireFormat *wireFormat AMQCPP_UNUSED, const std::vector< char > &data AMQCPP_UNUSED)
virtual std::vector< unsigned
char > getMarshaledForm (wireformat::WireFormat *wireFormat AMQCPP_UNUSED)
virtual void copyDataStructure (const DataStructure *src AMQCPP_UNUSED)
virtual std::string toString () const
Returns a string containing the information for this DataStructure such as its type and value of its elements.
virtual bool equals (const DataStructure *value AMQCPP_UNUSED) const
Public Member Functions inherited from activemq::commands::DataStructure
virtual ~DataStructure ()
virtual unsigned char getDataStructureType () const =0
Get the DataStructure Type as defined in CommandTypes.h.
virtual DataStructure * cloneDataStructure () const =0
Clone this obbject and return a new instance that the caller now owns, this will be an exact copy of this one.
virtual void copyDataStructure (const DataStructure *src)=0
Copy the contents of the passed object into this objects members, overwriting any existing data.
virtual bool equals (const DataStructure *value) const =0
Compares the DataStructure passed in to this one, and returns if they are equivalent.
Public Member Functions inherited from activemq::wireformat::MarshalAware
virtual ~MarshalAware ()
virtual void beforeMarshal (WireFormat *wireFormat)=0
Called before marshaling is started to prepare the object to be marshaled.
virtual void afterMarshal (WireFormat *wireFormat)=0
Called after marshaling is started to cleanup the object being marshaled.
virtual void beforeUnmarshal (WireFormat *wireFormat)=0
Called before unmarshaling is started to prepare the object to be unmarshaled.
virtual void afterUnmarshal (WireFormat *wireFormat)=0
Called after unmarshaling is started to cleanup the object being unmarshaled.
virtual void setMarshaledForm (WireFormat *wireFormat, const std::vector< char > &data)=0
Called to set the data to this object that will contain the objects marshaled form.
virtual std::vector< unsigned
char > getMarshaledForm (WireFormat *wireFormat)=0
Called to get the data to this object that will contain the objects marshaled form.
Constructor & Destructor Documentation
virtual activemq::commands::BaseDataStructure::~BaseDataStructure () inline virtual
Member Function Documentation
virtual void activemq::commands::BaseDataStructure::afterMarshal (wireformat::WireFormat *wireFormat AMQCPP_UNUSED) inline virtual
virtual void activemq::commands::BaseDataStructure::afterUnmarshal (wireformat::WireFormat *wireFormat AMQCPP_UNUSED) inline virtual
Reimplemented in activemq::commands::WireFormatInfo, and activemq::commands::Message.
virtual void activemq::commands::BaseDataStructure::beforeMarshal (wireformat::WireFormat *wireFormat AMQCPP_UNUSED) inline virtual
Reimplemented in activemq::commands::WireFormatInfo, and activemq::commands::Message.
virtual void activemq::commands::BaseDataStructure::beforeUnmarshal (wireformat::WireFormat *wireFormat AMQCPP_UNUSED) inline virtual
virtual void activemq::commands::BaseDataStructure::copyDataStructure (const DataStructure *src AMQCPP_UNUSED) inline virtual
Reimplemented in activemq::commands::BooleanExpression.
virtual bool activemq::commands::BaseDataStructure::equals (const DataStructure *value AMQCPP_UNUSED) const inline virtual
Referenced by activemq::commands::BooleanExpression::equals(), and activemq::commands::BaseCommand::equals().
virtual std::vector<unsigned char> activemq::commands::BaseDataStructure::getMarshaledForm (wireformat::WireFormat *wireFormat AMQCPP_UNUSED) inline virtual
virtual bool activemq::commands::BaseDataStructure::isMarshalAware () const inline virtual
Determine if the class implementing this interface is really wanting to be told about marshaling.
Normally if you didn't want to be marshal aware you just wouldn't implement this interface but since this is C++ and we don't have true interfaces we need a flat inheritance hierarchy, so we always implement this.
Returns
true if this class cares about marshaling.
Implements activemq::wireformat::MarshalAware.
Reimplemented in activemq::commands::Message, activemq::commands::WireFormatInfo, and activemq::commands::ActiveMQMapMessage.
virtual void activemq::commands::BaseDataStructure::setMarshaledForm (wireformat::WireFormat *wireFormat AMQCPP_UNUSED, const std::vector< char > &data AMQCPP_UNUSED) inline virtual
virtual std::string activemq::commands::BaseDataStructure::toString () const inline virtual
Returns a string containing the information for this DataStructure such as its type and value of its elements.
Returns
formatted string useful for debugging.
Implements activemq::commands::DataStructure.
Reimplemented in activemq::commands::Message, activemq::commands::ActiveMQDestination, activemq::commands::ConsumerInfo, activemq::commands::MessageAck, activemq::commands::MessageId, activemq::commands::SessionId, activemq::commands::BrokerInfo, activemq::commands::ConnectionInfo, activemq::commands::ActiveMQTempDestination, activemq::commands::XATransactionId, activemq::commands::MessageDispatch, activemq::commands::ProducerId, activemq::commands::ConnectionId, activemq::commands::ConsumerId, activemq::commands::LocalTransactionId, activemq::commands::ConnectionControl, activemq::commands::ConsumerControl, activemq::commands::JournalTopicAck, activemq::commands::ProducerInfo, activemq::commands::ActiveMQBytesMessage, activemq::commands::DestinationInfo, activemq::commands::MessagePull, activemq::commands::SessionInfo, activemq::commands::MessageDispatchNotification, activemq::commands::SubscriptionInfo, activemq::commands::TransactionInfo, activemq::commands::ConnectionError, activemq::commands::JournalQueueAck, activemq::commands::JournalTransaction, activemq::commands::NetworkBridgeFilter, activemq::commands::RemoveSubscriptionInfo, activemq::commands::ProducerAck, activemq::commands::RemoveInfo, activemq::commands::DataArrayResponse, activemq::commands::DataResponse, activemq::commands::DiscoveryEvent, activemq::commands::ExceptionResponse, activemq::commands::PartialCommand, activemq::commands::ReplayCommand, activemq::commands::BrokerId, activemq::commands::ControlCommand, activemq::commands::IntegerResponse, activemq::commands::JournalTrace, activemq::commands::Response, activemq::commands::FlushCommand, activemq::commands::KeepAliveInfo, activemq::commands::LastPartialCommand, activemq::commands::ShutdownInfo, activemq::commands::TransactionId, activemq::commands::ActiveMQQueue, activemq::commands::ActiveMQStreamMessage, activemq::commands::BaseCommand, activemq::commands::ActiveMQMapMessage, activemq::commands::Command, activemq::commands::WireFormatInfo, activemq::commands::ActiveMQTopic, activemq::commands::ActiveMQBlobMessage, activemq::commands::ActiveMQTempQueue, activemq::commands::ActiveMQTempTopic, activemq::commands::ActiveMQTextMessage, activemq::commands::ActiveMQObjectMessage, activemq::commands::ActiveMQMessage, and activemq::commands::BooleanExpression.
Referenced by activemq::commands::BooleanExpression::toString(), and activemq::commands::BaseCommand::toString().
The documentation for this class was generated from the following file:
src/main/activemq/commands/BaseDataStructure.h