activemq-cpp-3.3.0: activemq::state::CommandVisitorAdapter Class Reference
activemq::state::CommandVisitorAdapter Class Reference
Default Implementation of a CommandVisitor that returns NULL for all calls.
#include <src/main/activemq/state/CommandVisitorAdapter.h>
Public Member Functions
virtual ~CommandVisitorAdapter ()
virtual decaf::lang::Pointer
< commands::Command > processRemoveConnection (commands::ConnectionId *id AMQCPP_UNUSED)
virtual decaf::lang::Pointer
< commands::Command > processRemoveSession (commands::SessionId *id AMQCPP_UNUSED)
virtual decaf::lang::Pointer
< commands::Command > processRemoveProducer (commands::ProducerId *id AMQCPP_UNUSED)
virtual decaf::lang::Pointer
< commands::Command > processRemoveConsumer (commands::ConsumerId *id AMQCPP_UNUSED)
virtual decaf::lang::Pointer
< commands::Command > processDestinationInfo (commands::DestinationInfo *info AMQCPP_UNUSED)
virtual decaf::lang::Pointer
< commands::Command > processRemoveDestination (commands::DestinationInfo *info AMQCPP_UNUSED)
virtual decaf::lang::Pointer
< commands::Command > processRemoveSubscriptionInfo (commands::RemoveSubscriptionInfo *info AMQCPP_UNUSED)
virtual decaf::lang::Pointer
< commands::Command > processMessage (commands::Message *send AMQCPP_UNUSED)
virtual decaf::lang::Pointer
< commands::Command > processMessageAck (commands::MessageAck *ack AMQCPP_UNUSED)
virtual decaf::lang::Pointer
< commands::Command > processMessagePull (commands::MessagePull *pull AMQCPP_UNUSED)
virtual decaf::lang::Pointer
< commands::Command > processBeginTransaction (commands::TransactionInfo *info AMQCPP_UNUSED)
virtual decaf::lang::Pointer
< commands::Command > processPrepareTransaction (commands::TransactionInfo *info AMQCPP_UNUSED)
virtual decaf::lang::Pointer
< commands::Command > processCommitTransactionOnePhase (commands::TransactionInfo *info AMQCPP_UNUSED)
virtual decaf::lang::Pointer
< commands::Command > processCommitTransactionTwoPhase (commands::TransactionInfo *info AMQCPP_UNUSED)
virtual decaf::lang::Pointer
< commands::Command > processRollbackTransaction (commands::TransactionInfo *info AMQCPP_UNUSED)
virtual decaf::lang::Pointer
< commands::Command > processWireFormat (commands::WireFormatInfo *info AMQCPP_UNUSED)
virtual decaf::lang::Pointer
< commands::Command > processKeepAliveInfo (commands::KeepAliveInfo *info AMQCPP_UNUSED)
virtual decaf::lang::Pointer
< commands::Command > processShutdownInfo (commands::ShutdownInfo *info AMQCPP_UNUSED)
virtual decaf::lang::Pointer
< commands::Command > processFlushCommand (commands::FlushCommand *command AMQCPP_UNUSED)
virtual decaf::lang::Pointer
< commands::Command > processBrokerInfo (commands::BrokerInfo *info AMQCPP_UNUSED)
virtual decaf::lang::Pointer
< commands::Command > processRecoverTransactions (commands::TransactionInfo *info AMQCPP_UNUSED)
virtual decaf::lang::Pointer
< commands::Command > processForgetTransaction (commands::TransactionInfo *info AMQCPP_UNUSED)
virtual decaf::lang::Pointer
< commands::Command > processEndTransaction (commands::TransactionInfo *info AMQCPP_UNUSED)
virtual decaf::lang::Pointer
< commands::Command > processMessageDispatchNotification (commands::MessageDispatchNotification *notification AMQCPP_UNUSED)
virtual decaf::lang::Pointer
< commands::Command > processProducerAck (commands::ProducerAck *ack AMQCPP_UNUSED)
virtual decaf::lang::Pointer
< commands::Command > processMessageDispatch (commands::MessageDispatch *dispatch AMQCPP_UNUSED)
virtual decaf::lang::Pointer
< commands::Command > processControlCommand (commands::ControlCommand *command AMQCPP_UNUSED)
virtual decaf::lang::Pointer
< commands::Command > processConnectionError (commands::ConnectionError *error AMQCPP_UNUSED)
virtual decaf::lang::Pointer
< commands::Command > processConnectionControl (commands::ConnectionControl *control AMQCPP_UNUSED)
virtual decaf::lang::Pointer
< commands::Command > processConsumerControl (commands::ConsumerControl *control AMQCPP_UNUSED)
virtual decaf::lang::Pointer
< commands::Command > processBrokerError (commands::BrokerError *error AMQCPP_UNUSED)
virtual decaf::lang::Pointer
< commands::Command > processReplayCommand (commands::ReplayCommand *replay AMQCPP_UNUSED)
virtual decaf::lang::Pointer
< commands::Command > processResponse (commands::Response *response AMQCPP_UNUSED)
virtual decaf::lang::Pointer
< commands::Command > processConnectionInfo (commands::ConnectionInfo *info AMQCPP_UNUSED)
virtual decaf::lang::Pointer
< commands::Command > processSessionInfo (commands::SessionInfo *info AMQCPP_UNUSED)
virtual decaf::lang::Pointer
< commands::Command > processProducerInfo (commands::ProducerInfo *info AMQCPP_UNUSED)
virtual decaf::lang::Pointer
< commands::Command > processConsumerInfo (commands::ConsumerInfo *info AMQCPP_UNUSED)
virtual decaf::lang::Pointer
< commands::Command > processTransactionInfo (commands::TransactionInfo *info)
virtual decaf::lang::Pointer
< commands::Command > processRemoveInfo (commands::RemoveInfo *info)
Detailed Description
Default Implementation of a CommandVisitor that returns NULL for all calls.
Since:
3.0
Constructor & Destructor Documentation
virtual activemq::state::CommandVisitorAdapter::~CommandVisitorAdapter () [inline, virtual]
Member Function Documentation
virtual decaf::lang::Pointer<commands::Command> activemq::state::CommandVisitorAdapter::processBeginTransaction (commands::TransactionInfo *info AMQCPP_UNUSED) [inline, virtual]
virtual decaf::lang::Pointer<commands::Command> activemq::state::CommandVisitorAdapter::processBrokerError (commands::BrokerError *error AMQCPP_UNUSED) [inline, virtual]
virtual decaf::lang::Pointer<commands::Command> activemq::state::CommandVisitorAdapter::processBrokerInfo (commands::BrokerInfo *info AMQCPP_UNUSED) [inline, virtual]
virtual decaf::lang::Pointer<commands::Command> activemq::state::CommandVisitorAdapter::processCommitTransactionOnePhase (commands::TransactionInfo *info AMQCPP_UNUSED) [inline, virtual]
virtual decaf::lang::Pointer<commands::Command> activemq::state::CommandVisitorAdapter::processCommitTransactionTwoPhase (commands::TransactionInfo *info AMQCPP_UNUSED) [inline, virtual]
virtual decaf::lang::Pointer<commands::Command> activemq::state::CommandVisitorAdapter::processConnectionControl (commands::ConnectionControl *control AMQCPP_UNUSED) [inline, virtual]
virtual decaf::lang::Pointer<commands::Command> activemq::state::CommandVisitorAdapter::processConnectionError (commands::ConnectionError *error AMQCPP_UNUSED) [inline, virtual]
virtual decaf::lang::Pointer<commands::Command> activemq::state::CommandVisitorAdapter::processConnectionInfo (commands::ConnectionInfo *info AMQCPP_UNUSED) [inline, virtual]
virtual decaf::lang::Pointer<commands::Command> activemq::state::CommandVisitorAdapter::processConsumerControl (commands::ConsumerControl *control AMQCPP_UNUSED) [inline, virtual]
virtual decaf::lang::Pointer<commands::Command> activemq::state::CommandVisitorAdapter::processConsumerInfo (commands::ConsumerInfo *info AMQCPP_UNUSED) [inline, virtual]
virtual decaf::lang::Pointer<commands::Command> activemq::state::CommandVisitorAdapter::processControlCommand (commands::ControlCommand *command AMQCPP_UNUSED) [inline, virtual]
virtual decaf::lang::Pointer<commands::Command> activemq::state::CommandVisitorAdapter::processDestinationInfo (commands::DestinationInfo *info AMQCPP_UNUSED) [inline, virtual]
virtual decaf::lang::Pointer<commands::Command> activemq::state::CommandVisitorAdapter::processEndTransaction (commands::TransactionInfo *info AMQCPP_UNUSED) [inline, virtual]
virtual decaf::lang::Pointer<commands::Command> activemq::state::CommandVisitorAdapter::processFlushCommand (commands::FlushCommand *command AMQCPP_UNUSED) [inline, virtual]
virtual decaf::lang::Pointer<commands::Command> activemq::state::CommandVisitorAdapter::processForgetTransaction (commands::TransactionInfo *info AMQCPP_UNUSED) [inline, virtual]
virtual decaf::lang::Pointer<commands::Command> activemq::state::CommandVisitorAdapter::processKeepAliveInfo (commands::KeepAliveInfo *info AMQCPP_UNUSED) [inline, virtual]
virtual decaf::lang::Pointer<commands::Command> activemq::state::CommandVisitorAdapter::processMessage (commands::Message *send AMQCPP_UNUSED) [inline, virtual]
virtual decaf::lang::Pointer<commands::Command> activemq::state::CommandVisitorAdapter::processMessageAck (commands::MessageAck *ack AMQCPP_UNUSED) [inline, virtual]
virtual decaf::lang::Pointer<commands::Command> activemq::state::CommandVisitorAdapter::processMessageDispatch (commands::MessageDispatch *dispatch AMQCPP_UNUSED) [inline, virtual]
virtual decaf::lang::Pointer<commands::Command> activemq::state::CommandVisitorAdapter::processMessageDispatchNotification (commands::MessageDispatchNotification *notification AMQCPP_UNUSED) [inline, virtual]
virtual decaf::lang::Pointer<commands::Command> activemq::state::CommandVisitorAdapter::processMessagePull (commands::MessagePull *pull AMQCPP_UNUSED) [inline, virtual]
virtual decaf::lang::Pointer<commands::Command> activemq::state::CommandVisitorAdapter::processPrepareTransaction (commands::TransactionInfo *info AMQCPP_UNUSED) [inline, virtual]
virtual decaf::lang::Pointer<commands::Command> activemq::state::CommandVisitorAdapter::processProducerAck (commands::ProducerAck *ack AMQCPP_UNUSED) [inline, virtual]
virtual decaf::lang::Pointer<commands::Command> activemq::state::CommandVisitorAdapter::processProducerInfo (commands::ProducerInfo *info AMQCPP_UNUSED) [inline, virtual]
virtual decaf::lang::Pointer<commands::Command> activemq::state::CommandVisitorAdapter::processRecoverTransactions (commands::TransactionInfo *info AMQCPP_UNUSED) [inline, virtual]
virtual decaf::lang::Pointer<commands::Command> activemq::state::CommandVisitorAdapter::processRemoveConnection (commands::ConnectionId *id AMQCPP_UNUSED) [inline, virtual]
virtual decaf::lang::Pointer<commands::Command> activemq::state::CommandVisitorAdapter::processRemoveConsumer (commands::ConsumerId *id AMQCPP_UNUSED) [inline, virtual]
virtual decaf::lang::Pointer<commands::Command> activemq::state::CommandVisitorAdapter::processRemoveDestination (commands::DestinationInfo *info AMQCPP_UNUSED) [inline, virtual]
virtual decaf::lang::Pointer<commands::Command> activemq::state::CommandVisitorAdapter::processRemoveInfo (commands::RemoveInfo * info) [inline, virtual]
Implements activemq::state::CommandVisitor.
References decaf::lang::Pointer< T, REFCOUNTER >::get(), activemq::commands::RemoveInfo::getObjectId(), activemq::commands::ConnectionId::ID_CONNECTIONID, activemq::commands::ConsumerId::ID_CONSUMERID, activemq::commands::ProducerId::ID_PRODUCERID, and activemq::commands::SessionId::ID_SESSIONID.
virtual decaf::lang::Pointer<commands::Command> activemq::state::CommandVisitorAdapter::processRemoveProducer (commands::ProducerId *id AMQCPP_UNUSED) [inline, virtual]
virtual decaf::lang::Pointer<commands::Command> activemq::state::CommandVisitorAdapter::processRemoveSession (commands::SessionId *id AMQCPP_UNUSED) [inline, virtual]
virtual decaf::lang::Pointer<commands::Command> activemq::state::CommandVisitorAdapter::processRemoveSubscriptionInfo (commands::RemoveSubscriptionInfo *info AMQCPP_UNUSED) [inline, virtual]
virtual decaf::lang::Pointer<commands::Command> activemq::state::CommandVisitorAdapter::processReplayCommand (commands::ReplayCommand *replay AMQCPP_UNUSED) [inline, virtual]
virtual decaf::lang::Pointer<commands::Command> activemq::state::CommandVisitorAdapter::processResponse (commands::Response *response AMQCPP_UNUSED) [inline, virtual]
virtual decaf::lang::Pointer<commands::Command> activemq::state::CommandVisitorAdapter::processRollbackTransaction (commands::TransactionInfo *info AMQCPP_UNUSED) [inline, virtual]
virtual decaf::lang::Pointer<commands::Command> activemq::state::CommandVisitorAdapter::processSessionInfo (commands::SessionInfo *info AMQCPP_UNUSED) [inline, virtual]
virtual decaf::lang::Pointer<commands::Command> activemq::state::CommandVisitorAdapter::processShutdownInfo (commands::ShutdownInfo *info AMQCPP_UNUSED) [inline, virtual]
virtual decaf::lang::Pointer<commands::Command> activemq::state::CommandVisitorAdapter::processTransactionInfo (commands::TransactionInfo * info) [inline, virtual]
Implements activemq::state::CommandVisitor.
References activemq::commands::TransactionInfo::getType(), activemq::core::ActiveMQConstants::TRANSACTION_STATE_BEGIN, activemq::core::ActiveMQConstants::TRANSACTION_STATE_COMMITONEPHASE, activemq::core::ActiveMQConstants::TRANSACTION_STATE_COMMITTWOPHASE, activemq::core::ActiveMQConstants::TRANSACTION_STATE_END, activemq::core::ActiveMQConstants::TRANSACTION_STATE_FORGET, activemq::core::ActiveMQConstants::TRANSACTION_STATE_PREPARE, activemq::core::ActiveMQConstants::TRANSACTION_STATE_RECOVER, and activemq::core::ActiveMQConstants::TRANSACTION_STATE_ROLLBACK.
virtual decaf::lang::Pointer<commands::Command> activemq::state::CommandVisitorAdapter::processWireFormat (commands::WireFormatInfo *info AMQCPP_UNUSED) [inline, virtual]
The documentation for this class was generated from the following file:
src/main/activemq/state/CommandVisitorAdapter.h