activemq-cpp-3.6.0: decaf::util::MapEntry< K, V > Class Template Reference
decaf::util::MapEntry< K, V > Class Template Reference
#include <src/main/decaf/util/MapEntry.h>
Public Member Functions
MapEntry ()
MapEntry (const MapEntry &other)
MapEntry (const K &key, const V &value)
MapEntry & operator= (const MapEntry &other)
virtual ~MapEntry ()
virtual void setKey (K key)
virtual K & getKey ()
virtual const K & getKey () const
virtual void setValue (const V &value)
virtual V & getValue ()
virtual const V & getValue () const
virtual bool equals (const MapEntry< K, V > &entry) const
virtual bool operator== (const MapEntry< K, V > &other) const
Constructor & Destructor Documentation
template<typename K, typename V> decaf::util::MapEntry< K, V >::MapEntry () inline
template<typename K, typename V> decaf::util::MapEntry< K, V >::MapEntry (const MapEntry< K, V > & other) inline
template<typename K, typename V> decaf::util::MapEntry< K, V >::MapEntry (const K & key, const V & value) inline
template<typename K, typename V> virtual decaf::util::MapEntry< K, V >::~MapEntry () inline virtual
Member Function Documentation
template<typename K, typename V> virtual bool decaf::util::MapEntry< K, V >::equals (const MapEntry< K, V > & entry) const inline virtual
References decaf::util::MapEntry< K, V >::getKey(), and decaf::util::MapEntry< K, V >::getValue().
Referenced by decaf::util::MapEntry< K, V >::operator==().
template<typename K, typename V> virtual K& decaf::util::MapEntry< K, V >::getKey () inline virtual
Referenced by decaf::util::MapEntry< K, V >::equals(), decaf::util::MapEntry< K, V >::operator=(), and decaf::util::HashMap< K, V, HASHCODE >::putAllImpl().
template<typename K, typename V> virtual const K& decaf::util::MapEntry< K, V >::getKey () const inline virtual
template<typename K, typename V> virtual V& decaf::util::MapEntry< K, V >::getValue () inline virtual
Referenced by decaf::util::MapEntry< K, V >::equals(), decaf::util::MapEntry< K, V >::operator=(), and decaf::util::HashMap< K, V, HASHCODE >::putAllImpl().
template<typename K, typename V> virtual const V& decaf::util::MapEntry< K, V >::getValue () const inline virtual
template<typename K, typename V> MapEntry& decaf::util::MapEntry< K, V >::operator= (const MapEntry< K, V > & other) inline
References decaf::util::MapEntry< K, V >::getKey(), and decaf::util::MapEntry< K, V >::getValue().
template<typename K, typename V> virtual bool decaf::util::MapEntry< K, V >::operator== (const MapEntry< K, V > & other) const inline virtual
References decaf::util::MapEntry< K, V >::equals().
template<typename K, typename V> virtual void decaf::util::MapEntry< K, V >::setKey (K key) inline virtual
template<typename K, typename V> virtual void decaf::util::MapEntry< K, V >::setValue (const V & value) inline virtual
The documentation for this class was generated from the following file:
src/main/decaf/util/MapEntry.h