activemq-cpp-3.6.0: activemq::commands::Message Class Reference
activemq::commands::Message Class Reference
#include <src/main/activemq/commands/Message.h>
Public Member Functions
Message ()
virtual ~Message ()
virtual unsigned char getDataStructureType () const
Get the DataStructure Type as defined in CommandTypes.h.
virtual Message * cloneDataStructure () const
Clone this obbject and return a new instance that the caller now owns, this will be an exact copy of this one.
virtual void copyDataStructure (const DataStructure *src)
Copy the contents of the passed object into this objects members, overwriting any existing data.
virtual std::string toString () const
Returns a string containing the information for this DataStructure such as its type and value of its elements.
virtual bool equals (const DataStructure *value) const
Compares the DataStructure passed in to this one, and returns if they are equivalent.
Pointer< Message > copy () const
Create a Pointer based copy of this message.
virtual void beforeMarshal (wireformat::WireFormat *wireFormat AMQCPP_UNUSED)
Handles the marshaling of the objects properties into the internal byte array before the object is marshaled to the wire.
virtual void afterUnmarshal (wireformat::WireFormat *wireFormat AMQCPP_UNUSED)
Called after unmarshaling is started to cleanup the object being unmarshaled.
virtual bool isMarshalAware () const
Indicates that this command is aware of Marshaling, and needs to have its Marshaling methods invoked.
virtual void setAckHandler (const Pointer< core::ActiveMQAckHandler > &handler)
Sets the Acknowledgment Handler that this Message will use when the Acknowledge method is called.
virtual Pointer
< core::ActiveMQAckHandler > getAckHandler () const
Gets the Acknowledgment Handler that this Message will use when the Acknowledge method is called.
void setConnection (core::ActiveMQConnection *connection)
Sets the ActiveMQConnection instance that this Command was created from when the session create methods are called to create a Message.
core::ActiveMQConnection * getConnection () const
Gets the ActiveMQConnection instance that this Command was created from when the session create methods are called to create a Message.
virtual unsigned int getSize () const
Returns the Size of this message in Bytes.
virtual bool isExpired () const
Returns if this message has expired, meaning that its Expiration time has elapsed.
virtual void onSend ()
Allows derived Message classes to perform tasks before a message is sent.
util::PrimitiveMap & getMessageProperties ()
Gets a reference to the Message's Properties object, allows the derived classes to get and set their own specific properties.
const util::PrimitiveMap & getMessageProperties () const
bool isReadOnlyProperties () const
Returns if the Message Properties Are Read Only.
void setReadOnlyProperties (bool value)
Set the Read Only State of the Message Properties.
bool isReadOnlyBody () const
Returns if the Message Body is Read Only.
void setReadOnlyBody (bool value)
Set the Read Only State of the Message Content.
virtual const Pointer
< ProducerId > & getProducerId () const
virtual Pointer< ProducerId > & getProducerId ()
virtual void setProducerId (const Pointer< ProducerId > &producerId)
virtual const Pointer
< ActiveMQDestination > & getDestination () const
virtual Pointer
< ActiveMQDestination > & getDestination ()
virtual void setDestination (const Pointer< ActiveMQDestination > &destination)
virtual const Pointer
< TransactionId > & getTransactionId () const
virtual Pointer< TransactionId > & getTransactionId ()
virtual void setTransactionId (const Pointer< TransactionId > &transactionId)
virtual const Pointer
< ActiveMQDestination > & getOriginalDestination () const
virtual Pointer
< ActiveMQDestination > & getOriginalDestination ()
virtual void setOriginalDestination (const Pointer< ActiveMQDestination > &originalDestination)
virtual const Pointer
< MessageId > & getMessageId () const
virtual Pointer< MessageId > & getMessageId ()
virtual void setMessageId (const Pointer< MessageId > &messageId)
virtual const Pointer
< TransactionId > & getOriginalTransactionId () const
virtual Pointer< TransactionId > & getOriginalTransactionId ()
virtual void setOriginalTransactionId (const Pointer< TransactionId > &originalTransactionId)
virtual const std::string & getGroupID () const
virtual std::string & getGroupID ()
virtual void setGroupID (const std::string &groupID)
virtual int getGroupSequence () const
virtual void setGroupSequence (int groupSequence)
virtual const std::string & getCorrelationId () const
virtual std::string & getCorrelationId ()
virtual void setCorrelationId (const std::string &correlationId)
virtual bool isPersistent () const
virtual void setPersistent (bool persistent)
virtual long long getExpiration () const
virtual void setExpiration (long long expiration)
virtual unsigned char getPriority () const
virtual void setPriority (unsigned char priority)
virtual const Pointer
< ActiveMQDestination > & getReplyTo () const
virtual Pointer
< ActiveMQDestination > & getReplyTo ()
virtual void setReplyTo (const Pointer< ActiveMQDestination > &replyTo)
virtual long long getTimestamp () const
virtual void setTimestamp (long long timestamp)
virtual const std::string & getType () const
virtual std::string & getType ()
virtual void setType (const std::string &type)
virtual const std::vector
< unsigned char > & getContent () const
virtual std::vector< unsigned
char > & getContent ()
virtual void setContent (const std::vector< unsigned char > &content)
virtual const std::vector
< unsigned char > & getMarshalledProperties () const
virtual std::vector< unsigned
char > & getMarshalledProperties ()
virtual void setMarshalledProperties (const std::vector< unsigned char > &marshalledProperties)
virtual const Pointer
< DataStructure > & getDataStructure () const
virtual Pointer< DataStructure > & getDataStructure ()
virtual void setDataStructure (const Pointer< DataStructure > &dataStructure)
virtual const Pointer
< ConsumerId > & getTargetConsumerId () const
virtual Pointer< ConsumerId > & getTargetConsumerId ()
virtual void setTargetConsumerId (const Pointer< ConsumerId > &targetConsumerId)
virtual bool isCompressed () const
virtual void setCompressed (bool compressed)
virtual int getRedeliveryCounter () const
virtual void setRedeliveryCounter (int redeliveryCounter)
virtual const std::vector
< decaf::lang::Pointer
< BrokerId > > & getBrokerPath () const
virtual std::vector
< decaf::lang::Pointer
< BrokerId > > & getBrokerPath ()
virtual void setBrokerPath (const std::vector< decaf::lang::Pointer< BrokerId > > &brokerPath)
virtual long long getArrival () const
virtual void setArrival (long long arrival)
virtual const std::string & getUserID () const
virtual std::string & getUserID ()
virtual void setUserID (const std::string &userID)
virtual bool isRecievedByDFBridge () const
virtual void setRecievedByDFBridge (bool recievedByDFBridge)
virtual bool isDroppable () const
virtual void setDroppable (bool droppable)
virtual const std::vector
< decaf::lang::Pointer
< BrokerId > > & getCluster () const
virtual std::vector
< decaf::lang::Pointer
< BrokerId > > & getCluster ()
virtual void setCluster (const std::vector< decaf::lang::Pointer< BrokerId > > &cluster)
virtual long long getBrokerInTime () const
virtual void setBrokerInTime (long long brokerInTime)
virtual long long getBrokerOutTime () const
virtual void setBrokerOutTime (long long brokerOutTime)
virtual bool isMessage () const
virtual Pointer< Command > visit (activemq::state::CommandVisitor *visitor)
Allows a Visitor to visit this command and return a response to the command based on the command type being visited.
Public Member Functions inherited from activemq::commands::BaseCommand
BaseCommand ()
virtual ~BaseCommand ()
virtual void setCommandId (int id)
Sets the Command Id of this Message.
virtual int getCommandId () const
Gets the Command Id of this Message.
virtual void setResponseRequired (const bool required)
Set if this Message requires a Response.
virtual bool isResponseRequired () const
Is a Response required for this Command.
virtual bool isBrokerInfo () const
virtual bool isControlCommand () const
virtual bool isConnectionControl () const
virtual bool isConnectionError () const
virtual bool isConnectionInfo () const
virtual bool isConsumerInfo () const
virtual bool isConsumerControl () const
virtual bool isDestinationInfo () const
virtual bool isFlushCommand () const
virtual bool isMessageAck () const
virtual bool isMessagePull () const
virtual bool isKeepAliveInfo () const
virtual bool isMessageDispatch () const
virtual bool isMessageDispatchNotification () const
virtual bool isProducerAck () const
virtual bool isProducerInfo () const
virtual bool isResponse () const
virtual bool isRemoveInfo () const
virtual bool isRemoveSubscriptionInfo () const
virtual bool isReplayCommand () const
virtual bool isSessionInfo () const
virtual bool isShutdownInfo () const
virtual bool isTransactionInfo () const
virtual bool isWireFormatInfo () const
Public Member Functions inherited from activemq::commands::Command
virtual ~Command ()
Public Member Functions inherited from activemq::commands::BaseDataStructure
virtual ~BaseDataStructure ()
virtual void afterMarshal (wireformat::WireFormat *wireFormat AMQCPP_UNUSED)
virtual void beforeUnmarshal (wireformat::WireFormat *wireFormat AMQCPP_UNUSED)
virtual void setMarshaledForm (wireformat::WireFormat *wireFormat AMQCPP_UNUSED, const std::vector< char > &data AMQCPP_UNUSED)
virtual std::vector< unsigned
char > getMarshaledForm (wireformat::WireFormat *wireFormat AMQCPP_UNUSED)
virtual void copyDataStructure (const DataStructure *src AMQCPP_UNUSED)
virtual bool equals (const DataStructure *value AMQCPP_UNUSED) const
Public Member Functions inherited from activemq::commands::DataStructure
virtual ~DataStructure ()
Public Member Functions inherited from activemq::wireformat::MarshalAware
virtual ~MarshalAware ()
virtual void beforeMarshal (WireFormat *wireFormat)=0
Called before marshaling is started to prepare the object to be marshaled.
virtual void afterMarshal (WireFormat *wireFormat)=0
Called after marshaling is started to cleanup the object being marshaled.
virtual void beforeUnmarshal (WireFormat *wireFormat)=0
Called before unmarshaling is started to prepare the object to be unmarshaled.
virtual void afterUnmarshal (WireFormat *wireFormat)=0
Called after unmarshaling is started to cleanup the object being unmarshaled.
virtual void setMarshaledForm (WireFormat *wireFormat, const std::vector< char > &data)=0
Called to set the data to this object that will contain the objects marshaled form.
virtual std::vector< unsigned
char > getMarshaledForm (WireFormat *wireFormat)=0
Called to get the data to this object that will contain the objects marshaled form.
Static Public Attributes
static const unsigned char ID_MESSAGE = 0
Protected Attributes
Pointer< ProducerId > producerId
Pointer< ActiveMQDestination > destination
Pointer< TransactionId > transactionId
Pointer< ActiveMQDestination > originalDestination
Pointer< MessageId > messageId
Pointer< TransactionId > originalTransactionId
std::string groupID
int groupSequence
std::string correlationId
bool persistent
long long expiration
unsigned char priority
Pointer< ActiveMQDestination > replyTo
long long timestamp
std::string type
std::vector< unsigned char > content
std::vector< unsigned char > marshalledProperties
Pointer< DataStructure > dataStructure
Pointer< ConsumerId > targetConsumerId
bool compressed
int redeliveryCounter
std::vector
< decaf::lang::Pointer
< BrokerId > > brokerPath
long long arrival
std::string userID
bool recievedByDFBridge
bool droppable
std::vector
< decaf::lang::Pointer
< BrokerId > > cluster
long long brokerInTime
long long brokerOutTime
core::ActiveMQConnection * connection
Static Protected Attributes
static const unsigned int DEFAULT_MESSAGE_SIZE = 1024
Constructor & Destructor Documentation
activemq::commands::Message::Message ()
virtual activemq::commands::Message::~Message () virtual
Member Function Documentation
virtual void activemq::commands::Message::afterUnmarshal (wireformat::WireFormat *wireFormat AMQCPP_UNUSED) virtual
Called after unmarshaling is started to cleanup the object being unmarshaled.
Parameters
wireFormat - the wireformat object to control unmarshaling
Reimplemented from activemq::commands::BaseDataStructure.
virtual void activemq::commands::Message::beforeMarshal (wireformat::WireFormat *wireFormat AMQCPP_UNUSED) virtual
Handles the marshaling of the objects properties into the internal byte array before the object is marshaled to the wire.
Parameters
wireFormat - the wireformat controller
Reimplemented from activemq::commands::BaseDataStructure.
virtual Message* activemq::commands::Message::cloneDataStructure () const virtual
Clone this obbject and return a new instance that the caller now owns, this will be an exact copy of this one.
Returns
new copy of this object.
Implements activemq::commands::DataStructure.
Reimplemented in activemq::commands::ActiveMQBytesMessage, activemq::commands::ActiveMQStreamMessage, activemq::commands::ActiveMQMapMessage, activemq::commands::ActiveMQBlobMessage, activemq::commands::ActiveMQTextMessage, activemq::commands::ActiveMQMessage, and activemq::commands::ActiveMQObjectMessage.
Pointer<Message> activemq::commands::Message::copy () const inline
Create a Pointer based copy of this message.
Useful for chaining a clone operation with other operation such as casting to a cms Message type.
Pointer<cms::Message> cmsMsg = message->copy().dynamic_cast<cms::Message>();
Returns
a Pointer<Message> which is a duplicate of this object.
virtual void activemq::commands::Message::copyDataStructure (const DataStructure * src) virtual
Copy the contents of the passed object into this objects members, overwriting any existing data.
Returns
src - Source Object
Reimplemented from activemq::commands::BaseCommand.
Reimplemented in activemq::commands::ActiveMQBytesMessage, activemq::commands::ActiveMQStreamMessage, activemq::commands::ActiveMQMapMessage, activemq::commands::ActiveMQBlobMessage, activemq::commands::ActiveMQTextMessage, activemq::commands::ActiveMQObjectMessage, and activemq::commands::ActiveMQMessage.
virtual bool activemq::commands::Message::equals (const DataStructure * value) const virtual
Compares the DataStructure passed in to this one, and returns if they are equivalent.
Equivalent here means that they are of the same type, and that each element of the objects are the same.
Returns
true if DataStructure's are Equal.
Reimplemented from activemq::commands::BaseCommand.
Reimplemented in activemq::commands::ActiveMQBytesMessage, activemq::commands::ActiveMQMapMessage, activemq::commands::ActiveMQStreamMessage, activemq::commands::ActiveMQMessageTemplate< T >, activemq::commands::ActiveMQMessageTemplate< cms::BytesMessage >, activemq::commands::ActiveMQMessageTemplate< cms::MapMessage >, activemq::commands::ActiveMQMessageTemplate< cms::Message >, activemq::commands::ActiveMQMessageTemplate< cms::StreamMessage >, activemq::commands::ActiveMQMessageTemplate< cms::TextMessage >, activemq::commands::ActiveMQMessageTemplate< cms::ObjectMessage >, activemq::commands::ActiveMQBlobMessage, activemq::commands::ActiveMQTextMessage, activemq::commands::ActiveMQObjectMessage, and activemq::commands::ActiveMQMessage.
virtual Pointer<core::ActiveMQAckHandler> activemq::commands::Message::getAckHandler () const inline virtual
Gets the Acknowledgment Handler that this Message will use when the Acknowledge method is called.
Returns
handler ActiveMQAckHandler to call or NULL if not set
virtual long long activemq::commands::Message::getArrival () const virtual
virtual long long activemq::commands::Message::getBrokerInTime () const virtual
virtual long long activemq::commands::Message::getBrokerOutTime () const virtual
virtual const std::vector< decaf::lang::Pointer<BrokerId> >& activemq::commands::Message::getBrokerPath () const virtual
virtual std::vector< decaf::lang::Pointer<BrokerId> >& activemq::commands::Message::getBrokerPath () virtual
virtual const std::vector< decaf::lang::Pointer<BrokerId> >& activemq::commands::Message::getCluster () const virtual
virtual std::vector< decaf::lang::Pointer<BrokerId> >& activemq::commands::Message::getCluster () virtual
core::ActiveMQConnection* activemq::commands::Message::getConnection () const inline
Gets the ActiveMQConnection instance that this Command was created from when the session create methods are called to create a Message.
Returns
the ActiveMQConnection parent for this Message or NULL if not set.
virtual const std::vector<unsigned char>& activemq::commands::Message::getContent () const virtual
virtual std::vector<unsigned char>& activemq::commands::Message::getContent () virtual
virtual const std::string& activemq::commands::Message::getCorrelationId () const virtual
virtual std::string& activemq::commands::Message::getCorrelationId () virtual
virtual const Pointer<DataStructure>& activemq::commands::Message::getDataStructure () const virtual
virtual Pointer<DataStructure>& activemq::commands::Message::getDataStructure () virtual
virtual unsigned char activemq::commands::Message::getDataStructureType () const virtual
Get the DataStructure Type as defined in CommandTypes.h.
Returns
The type of the data structure
Implements activemq::commands::DataStructure.
Reimplemented in activemq::commands::ActiveMQBytesMessage, activemq::commands::ActiveMQStreamMessage, activemq::commands::ActiveMQMapMessage, activemq::commands::ActiveMQBlobMessage, activemq::commands::ActiveMQTextMessage, activemq::commands::ActiveMQObjectMessage, and activemq::commands::ActiveMQMessage.
virtual const Pointer<ActiveMQDestination>& activemq::commands::Message::getDestination () const virtual
virtual Pointer<ActiveMQDestination>& activemq::commands::Message::getDestination () virtual
virtual long long activemq::commands::Message::getExpiration () const virtual
virtual const std::string& activemq::commands::Message::getGroupID () const virtual
virtual std::string& activemq::commands::Message::getGroupID () virtual
virtual int activemq::commands::Message::getGroupSequence () const virtual
virtual const std::vector<unsigned char>& activemq::commands::Message::getMarshalledProperties () const virtual
virtual std::vector<unsigned char>& activemq::commands::Message::getMarshalledProperties () virtual
virtual const Pointer<MessageId>& activemq::commands::Message::getMessageId () const virtual
virtual Pointer<MessageId>& activemq::commands::Message::getMessageId () virtual
util::PrimitiveMap& activemq::commands::Message::getMessageProperties () inline
Gets a reference to the Message's Properties object, allows the derived classes to get and set their own specific properties.
Returns
a reference to the Primitive Map that holds message properties.
const util::PrimitiveMap& activemq::commands::Message::getMessageProperties () const inline
virtual const Pointer<ActiveMQDestination>& activemq::commands::Message::getOriginalDestination () const virtual
virtual Pointer<ActiveMQDestination>& activemq::commands::Message::getOriginalDestination () virtual
virtual const Pointer<TransactionId>& activemq::commands::Message::getOriginalTransactionId () const virtual
virtual Pointer<TransactionId>& activemq::commands::Message::getOriginalTransactionId () virtual
virtual unsigned char activemq::commands::Message::getPriority () const virtual
virtual const Pointer<ProducerId>& activemq::commands::Message::getProducerId () const virtual
virtual Pointer<ProducerId>& activemq::commands::Message::getProducerId () virtual
virtual int activemq::commands::Message::getRedeliveryCounter () const virtual
virtual const Pointer<ActiveMQDestination>& activemq::commands::Message::getReplyTo () const virtual
virtual Pointer<ActiveMQDestination>& activemq::commands::Message::getReplyTo () virtual
virtual unsigned int activemq::commands::Message::getSize () const virtual
Returns the Size of this message in Bytes.
Returns
number of bytes this message equates to.
Reimplemented in activemq::commands::ActiveMQTextMessage.
virtual const Pointer<ConsumerId>& activemq::commands::Message::getTargetConsumerId () const virtual
virtual Pointer<ConsumerId>& activemq::commands::Message::getTargetConsumerId () virtual
virtual long long activemq::commands::Message::getTimestamp () const virtual
virtual const Pointer<TransactionId>& activemq::commands::Message::getTransactionId () const virtual
virtual Pointer<TransactionId>& activemq::commands::Message::getTransactionId () virtual
virtual const std::string& activemq::commands::Message::getType () const virtual
virtual std::string& activemq::commands::Message::getType () virtual
virtual const std::string& activemq::commands::Message::getUserID () const virtual
virtual std::string& activemq::commands::Message::getUserID () virtual
virtual bool activemq::commands::Message::isCompressed () const virtual
virtual bool activemq::commands::Message::isDroppable () const virtual
virtual bool activemq::commands::Message::isExpired () const virtual
Returns if this message has expired, meaning that its Expiration time has elapsed.
Returns
true if message is expired.
virtual bool activemq::commands::Message::isMarshalAware () const inline virtual
Indicates that this command is aware of Marshaling, and needs to have its Marshaling methods invoked.
Returns
boolean indicating desire to be in marshaling stages
Reimplemented from activemq::commands::BaseDataStructure.
Reimplemented in activemq::commands::ActiveMQMapMessage.
virtual bool activemq::commands::Message::isMessage () const inline virtual
Returns
an answer of true to the isMessage() query.
Reimplemented from activemq::commands::BaseCommand.
virtual bool activemq::commands::Message::isPersistent () const virtual
bool activemq::commands::Message::isReadOnlyBody () const inline
Returns if the Message Body is Read Only.
Returns
true if Message Content is Read Only.
bool activemq::commands::Message::isReadOnlyProperties () const inline
Returns if the Message Properties Are Read Only.
Returns
true if Message Properties are Read Only.
virtual bool activemq::commands::Message::isRecievedByDFBridge () const virtual
virtual void activemq::commands::Message::onSend () inline virtual
Allows derived Message classes to perform tasks before a message is sent.
Reimplemented in activemq::commands::ActiveMQBytesMessage, activemq::commands::ActiveMQStreamMessage, activemq::commands::ActiveMQMessageTemplate< T >, activemq::commands::ActiveMQMessageTemplate< cms::BytesMessage >, activemq::commands::ActiveMQMessageTemplate< cms::MapMessage >, activemq::commands::ActiveMQMessageTemplate< cms::Message >, activemq::commands::ActiveMQMessageTemplate< cms::StreamMessage >, activemq::commands::ActiveMQMessageTemplate< cms::TextMessage >, and activemq::commands::ActiveMQMessageTemplate< cms::ObjectMessage >.
virtual void activemq::commands::Message::setAckHandler (const Pointer< core::ActiveMQAckHandler > & handler) inline virtual
Sets the Acknowledgment Handler that this Message will use when the Acknowledge method is called.
Parameters
handler ActiveMQAckHandler to call
virtual void activemq::commands::Message::setArrival (long long arrival) virtual
virtual void activemq::commands::Message::setBrokerInTime (long long brokerInTime) virtual
virtual void activemq::commands::Message::setBrokerOutTime (long long brokerOutTime) virtual
virtual void activemq::commands::Message::setBrokerPath (const std::vector< decaf::lang::Pointer< BrokerId > > & brokerPath) virtual
virtual void activemq::commands::Message::setCluster (const std::vector< decaf::lang::Pointer< BrokerId > > & cluster) virtual
virtual void activemq::commands::Message::setCompressed (bool compressed) virtual
void activemq::commands::Message::setConnection (core::ActiveMQConnection * connection) inline
Sets the ActiveMQConnection instance that this Command was created from when the session create methods are called to create a Message.
Parameters
handler ActiveMQConnection parent for this message
virtual void activemq::commands::Message::setContent (const std::vector< unsigned char > & content) virtual
virtual void activemq::commands::Message::setCorrelationId (const std::string & correlationId) virtual
virtual void activemq::commands::Message::setDataStructure (const Pointer< DataStructure > & dataStructure) virtual
virtual void activemq::commands::Message::setDestination (const Pointer< ActiveMQDestination > & destination) virtual
virtual void activemq::commands::Message::setDroppable (bool droppable) virtual
virtual void activemq::commands::Message::setExpiration (long long expiration) virtual
virtual void activemq::commands::Message::setGroupID (const std::string & groupID) virtual
virtual void activemq::commands::Message::setGroupSequence (int groupSequence) virtual
virtual void activemq::commands::Message::setMarshalledProperties (const std::vector< unsigned char > & marshalledProperties) virtual
virtual void activemq::commands::Message::setMessageId (const Pointer< MessageId > & messageId) virtual
virtual void activemq::commands::Message::setOriginalDestination (const Pointer< ActiveMQDestination > & originalDestination) virtual
virtual void activemq::commands::Message::setOriginalTransactionId (const Pointer< TransactionId > & originalTransactionId) virtual
virtual void activemq::commands::Message::setPersistent (bool persistent) virtual
virtual void activemq::commands::Message::setPriority (unsigned char priority) virtual
virtual void activemq::commands::Message::setProducerId (const Pointer< ProducerId > & producerId) virtual
void activemq::commands::Message::setReadOnlyBody (bool value) inline
Set the Read Only State of the Message Content.
Parameters
value - true if Content should be read only.
Referenced by activemq::commands::ActiveMQMessage::clone(), activemq::commands::ActiveMQObjectMessage::clone(), activemq::commands::ActiveMQBlobMessage::clone(), activemq::commands::ActiveMQTextMessage::clone(), activemq::commands::ActiveMQStreamMessage::clone(), activemq::commands::ActiveMQMapMessage::clone(), and activemq::commands::ActiveMQBytesMessage::clone().
void activemq::commands::Message::setReadOnlyProperties (bool value) inline
Set the Read Only State of the Message Properties.
Parameters
value - true if Properties should be read only.
Referenced by activemq::commands::ActiveMQMessage::clone(), activemq::commands::ActiveMQObjectMessage::clone(), activemq::commands::ActiveMQBlobMessage::clone(), activemq::commands::ActiveMQTextMessage::clone(), activemq::commands::ActiveMQStreamMessage::clone(), activemq::commands::ActiveMQMapMessage::clone(), and activemq::commands::ActiveMQBytesMessage::clone().
virtual void activemq::commands::Message::setRecievedByDFBridge (bool recievedByDFBridge) virtual
virtual void activemq::commands::Message::setRedeliveryCounter (int redeliveryCounter) virtual
virtual void activemq::commands::Message::setReplyTo (const Pointer< ActiveMQDestination > & replyTo) virtual
virtual void activemq::commands::Message::setTargetConsumerId (const Pointer< ConsumerId > & targetConsumerId) virtual
virtual void activemq::commands::Message::setTimestamp (long long timestamp) virtual
virtual void activemq::commands::Message::setTransactionId (const Pointer< TransactionId > & transactionId) virtual
virtual void activemq::commands::Message::setType (const std::string & type) virtual
virtual void activemq::commands::Message::setUserID (const std::string & userID) virtual
virtual std::string activemq::commands::Message::toString () const virtual
Returns a string containing the information for this DataStructure such as its type and value of its elements.
Returns
formatted string useful for debugging.
Reimplemented from activemq::commands::BaseCommand.
Reimplemented in activemq::commands::ActiveMQBytesMessage, activemq::commands::ActiveMQMapMessage, activemq::commands::ActiveMQStreamMessage, activemq::commands::ActiveMQBlobMessage, activemq::commands::ActiveMQTextMessage, activemq::commands::ActiveMQObjectMessage, and activemq::commands::ActiveMQMessage.
virtual Pointer<Command> activemq::commands::Message::visit (activemq::state::CommandVisitor * visitor) virtual
Allows a Visitor to visit this command and return a response to the command based on the command type being visited.
The command will call the proper processXXX method in the visitor.
Returns
a Response to the visitor being called or NULL if no response.
Implements activemq::commands::Command.
Field Documentation
long long activemq::commands::Message::arrival protected
long long activemq::commands::Message::brokerInTime protected
long long activemq::commands::Message::brokerOutTime protected
std::vector< decaf::lang::Pointer<BrokerId> > activemq::commands::Message::brokerPath protected
std::vector< decaf::lang::Pointer<BrokerId> > activemq::commands::Message::cluster protected
bool activemq::commands::Message::compressed protected
core::ActiveMQConnection* activemq::commands::Message::connection protected
std::vector<unsigned char> activemq::commands::Message::content protected
std::string activemq::commands::Message::correlationId protected
Pointer<DataStructure> activemq::commands::Message::dataStructure protected
const unsigned int activemq::commands::Message::DEFAULT_MESSAGE_SIZE = 1024 static protected
Pointer<ActiveMQDestination> activemq::commands::Message::destination protected
bool activemq::commands::Message::droppable protected
long long activemq::commands::Message::expiration protected
std::string activemq::commands::Message::groupID protected
int activemq::commands::Message::groupSequence protected
const unsigned char activemq::commands::Message::ID_MESSAGE = 0 static
std::vector<unsigned char> activemq::commands::Message::marshalledProperties protected
Pointer<MessageId> activemq::commands::Message::messageId protected
Pointer<ActiveMQDestination> activemq::commands::Message::originalDestination protected
Pointer<TransactionId> activemq::commands::Message::originalTransactionId protected
bool activemq::commands::Message::persistent protected
unsigned char activemq::commands::Message::priority protected
Pointer<ProducerId> activemq::commands::Message::producerId protected
bool activemq::commands::Message::recievedByDFBridge protected
int activemq::commands::Message::redeliveryCounter protected
Pointer<ActiveMQDestination> activemq::commands::Message::replyTo protected
Pointer<ConsumerId> activemq::commands::Message::targetConsumerId protected
long long activemq::commands::Message::timestamp protected
Pointer<TransactionId> activemq::commands::Message::transactionId protected
std::string activemq::commands::Message::type protected
std::string activemq::commands::Message::userID protected
The documentation for this class was generated from the following file:
src/main/activemq/commands/Message.h