activemq-cpp-3.6.0: decaf::util::concurrent::LinkedBlockingQueue< E > Class Template Reference
decaf::util::concurrent::LinkedBlockingQueue< E > Class Template Reference
A BlockingQueue derivative that allows for a bound to be placed on the number of elements that can be enqueued at any one time.
#include <src/main/decaf/util/concurrent/LinkedBlockingQueue.h>
Data Structures
class ConstLinkedIterator
class LinkedIterator
class QueueNode
class TotalLock
Public Member Functions
LinkedBlockingQueue ()
Create a new instance with a Capacity of Integer::MAX_VALUE.
LinkedBlockingQueue (int capacity)
Create a new instance with the given initial capacity value.
LinkedBlockingQueue (const Collection< E > &collection)
Create a new instance with a Capacity of Integer::MAX_VALUE and adds all the values contained in the specified collection to this Queue.
LinkedBlockingQueue (const LinkedBlockingQueue &queue)
Create a new instance with a Capacity of Integer::MAX_VALUE and adds all the values contained in the specified LinkedBlockingQueue to this Queue.
virtual ~LinkedBlockingQueue ()
LinkedBlockingQueue< E > & operator= (const LinkedBlockingQueue< E > &queue)
LinkedBlockingQueue< E > & operator= (const Collection< E > &collection)
virtual int size () const
Returns the number of elements in this collection.
virtual void clear ()
Removes all of the elements from this collection (optional operation).The collection will be empty after this method returns.This implementation iterates over this collection, removing each element using the Iterator.remove operation. Most implementations will probably choose to override this method for efficiency.Note that this implementation will throw an UnsupportedOperationException if the iterator returned by this collection's iterator method does not implement the remove method and this collection is non-empty.
Exceptions
UnsupportedOperationException if the clear operation is not supported by this collection
This implementation repeatedly invokes poll until it returns false.
virtual int remainingCapacity () const
Returns the number of additional elements that this queue can ideally (in the absence of memory or resource constraints) accept without blocking, or Integer::MAX_VALUE if there is no intrinsic limit.
virtual void put (const E &value)
Inserts the specified element into this queue, waiting if necessary for space to become available.
virtual bool offer (const E &value, long long timeout, const TimeUnit &unit)
Inserts the specified element into this queue, waiting up to the specified wait time if necessary for space to become available.
virtual bool offer (const E &value)
Inserts the specified element into the queue provided that the condition allows such an operation.
virtual E take ()
Retrieves and removes the head of this queue, waiting if necessary until an element becomes available.
virtual bool poll (E &result, long long timeout, const TimeUnit &unit)
Retrieves and removes the head of this queue, waiting up to the specified wait time if necessary for an element to become available.
virtual bool poll (E &result)
Gets and removes the element in the head of the queue.
virtual bool peek (E &result) const
Gets but not removes the element in the head of the queue.
virtual bool remove (const E &value)
Removes a single instance of the specified element from the collection.More formally, removes an element e such that (value == NULL ? e == NULL : value == e), if this collection contains one or more such elements. Returns true if this collection contained the specified element (or equivalently, if this collection changed as a result of the call).
Parameters
value The reference to the element to remove from this Collection.
Returns
true if the collection was changed, false otherwise.
Exceptions
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
This implementation iterates over the collection looking for the specified element. If it finds the element, it removes the element from the collection using the iterator's remove method.Note that this implementation throws an UnsupportedOperationException if the iterator returned by this collection's iterator method does not implement the remove method and this collection contains the specified object.
virtual std::vector< E > toArray () const
Answers an STL vector containing copies of all elements contained in this Collection.
virtual std::string toString () const
virtual int drainTo (Collection< E > &c)
Removes all available elements from this queue and adds them to the given collection.
virtual int drainTo (Collection< E > &sink, int maxElements)
Removes at most the given number of available elements from this queue and adds them to the given collection.
virtual decaf::util::Iterator
< E > * iterator ()
virtual decaf::util::Iterator
< E > * iterator () const
Public Member Functions inherited from decaf::util::concurrent::BlockingQueue< E >
virtual ~BlockingQueue ()
Public Member Functions inherited from decaf::util::AbstractQueue< E >
AbstractQueue ()
virtual ~AbstractQueue ()
virtual bool add (const E &value)
Returns true if this collection changed as a result of the call.(Returns false if this collection does not permit duplicates and already contains the specified element.)Collections that support this operation may place limitations on what elements may be added to this collection. In particular, some collections will refuse to add null elements, and others will impose restrictions on the type of elements that may be added. Collection classes should clearly specify in their documentation any restrictions on what elements may be added.If a collection refuses to add a particular element for any reason other than that it already contains the element, it must throw an exception (rather than returning false). This preserves the invariant that a collection always contains the specified element after this call returns.For non-pointer values, i.e. class instances or string's the object will be copied into the collection, thus the object must support being copied, must not hide the copy constructor and assignment operator.
Parameters
value The reference to the element to add to this Collection.
Returns
true if the element was added to this Collection.
Exceptions
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
IllegalArgumentException if some property of the element prevents it from being added to this collection
IllegalStateException if the element cannot be added at this time due to insertion restrictions.
virtual bool addAll (const Collection< E > &collection)
Adds all of the elements in the specified collection to this collection.The behavior of this operation is undefined if the specified collection is modified while the operation is in progress. (This implies that the behavior of this call is undefined if the specified collection is this collection, and this collection is nonempty.)
Parameters
collection The Collection whose elements are added to this one.
Returns
true if this collection changed as a result of the call
Exceptions
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
IllegalArgumentException if some property of an element prevents it from being added to this collection
IllegalStateException if an element cannot be added at this time due to insertion restrictions.
This implementation iterates over the specified collection, and adds each object returned by the iterator to this collection, in turn.Note that this implementation will throw an UnsupportedOperationException unless add is overridden (assuming the specified collection is non-empty).
virtual E remove ()
Gets and removes the element in the head of the queue.Throws a NoSuchElementException if there is no element in the queue.
Returns
the element in the head of the queue.
Exceptions
NoSuchElementException if there is no element in the queue.
virtual E element () const
Gets but not removes the element in the head of the queue.Throws a NoSuchElementException if there is no element in the queue.
Returns
the element in the head of the queue.
Exceptions
NoSuchElementException if there is no element in the queue.
Public Member Functions inherited from decaf::util::Queue< E >
virtual ~Queue ()
Public Member Functions inherited from decaf::util::Collection< E >
virtual ~Collection ()
Public Member Functions inherited from decaf::lang::Iterable< E >
virtual ~Iterable ()
Public Member Functions inherited from decaf::util::concurrent::Synchronizable
virtual ~Synchronizable ()
Public Member Functions inherited from decaf::util::AbstractCollection< E >
AbstractCollection ()
virtual ~AbstractCollection ()
AbstractCollection< E > & operator= (const AbstractCollection< E > &collection)
Assignment Operator, copy element from the source collection to this collection after clearing any element stored in this collection.
virtual bool contains (const E &value) const
Returns true if this collection contains the specified element.More formally, returns true if and only if this collection contains at least one element e such that (value == NULL ? e == NULL : value == e).
Parameters
value The value to check for presence in the collection.
Returns
true if there is at least one of the elements in the collection
Exceptions
NullPointerException if the Collection contains pointers and the Collection does not allow for NULL elements (optional check).
virtual bool containsAll (const Collection< E > &collection) const
Returns true if this collection contains all of the elements in the specified collection.
Parameters
collection The Collection to compare to this one.
Exceptions
NullPointerException if the Collection contains pointers and the Collection does not allow for NULL elements (optional check).
virtual bool equals (const Collection< E > &collection) const
Answers true if this Collection and the one given are the same size and if each element contained in the Collection given is equal to an element contained in this collection.
virtual void copy (const Collection< E > &collection)
Renders this Collection as a Copy of the given Collection.
virtual bool isEmpty () const
Returns true if this collection contains no elements.
virtual bool add (const E &value DECAF_UNUSED)
virtual bool removeAll (const Collection< E > &collection)
Removes all this collection's elements that are also contained in the specified collection (optional operation).After this call returns, this collection will contain no elements in common with the specified collection.
Parameters
collection The Collection whose elements are to be removed from this one.
Returns
true if the collection changed as a result of this call.
Exceptions
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
virtual bool retainAll (const Collection< E > &collection)
Retains only the elements in this collection that are contained in the specified collection (optional operation).In other words, removes from this collection all of its elements that are not contained in the specified collection.
Parameters
collection The Collection whose elements are to be retained.
Returns
true if the collection changed as a result of this call.
Exceptions
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
virtual void lock ()
Locks the object.
virtual bool tryLock ()
Attempts to Lock the object, if the lock is already held by another thread than this method returns false.
virtual void unlock ()
Unlocks the object.
virtual void wait ()
Waits on a signal from this object, which is generated by a call to Notify.
virtual void wait (long long millisecs)
Waits on a signal from this object, which is generated by a call to Notify.
virtual void wait (long long millisecs, int nanos)
Waits on a signal from this object, which is generated by a call to Notify.
virtual void notify ()
Signals a waiter on this object that it can now wake up and continue.
virtual void notifyAll ()
Signals the waiters on this object that it can now wake up and continue.
Additional Inherited Members
Protected Attributes inherited from decaf::util::AbstractCollection< E >
util::concurrent::Mutex mutex
Detailed Description
template<typename E>
class decaf::util::concurrent::LinkedBlockingQueue< E >
A BlockingQueue derivative that allows for a bound to be placed on the number of elements that can be enqueued at any one time.
Elements are inserted and removed in FIFO order. The internal structure of the queue is based on a linked nodes which provides for better performance over their array based versions but the performance is less predictable.
The capacity bound of this class default to Integer::MAX_VALUE.
Since
1.0
Constructor & Destructor Documentation
template<typename E> decaf::util::concurrent::LinkedBlockingQueue< E >::LinkedBlockingQueue () inline
Create a new instance with a Capacity of Integer::MAX_VALUE.
template<typename E> decaf::util::concurrent::LinkedBlockingQueue< E >::LinkedBlockingQueue (int capacity) inline
Create a new instance with the given initial capacity value.
Parameters
capacity The initial capacity value to assign to this Queue.
Exceptions
IllegalArgumentException if the specified capacity is not greater than zero.
template<typename E> decaf::util::concurrent::LinkedBlockingQueue< E >::LinkedBlockingQueue (const Collection< E > & collection) inline
Create a new instance with a Capacity of Integer::MAX_VALUE and adds all the values contained in the specified collection to this Queue.
Parameters
collection The Collection whose elements are to be copied to this Queue.
Exceptions
IllegalStateException if the number of elements in the collection exceeds this Queue's capacity.
template<typename E> decaf::util::concurrent::LinkedBlockingQueue< E >::LinkedBlockingQueue (const LinkedBlockingQueue< E > & queue) inline
Create a new instance with a Capacity of Integer::MAX_VALUE and adds all the values contained in the specified LinkedBlockingQueue to this Queue.
Parameters
queue The LinkedBlockingQueue whose elements are to be copied to this Queue.
Exceptions
IllegalStateException if the number of elements in the collection exceeds this Queue's capacity.
template<typename E> virtual decaf::util::concurrent::LinkedBlockingQueue< E >::~LinkedBlockingQueue () inline virtual
Member Function Documentation
template<typename E> virtual void decaf::util::concurrent::LinkedBlockingQueue< E >::clear () inline virtual
Removes all of the elements from this collection (optional operation).The collection will be empty after this method returns.This implementation iterates over this collection, removing each element using the Iterator.remove operation. Most implementations will probably choose to override this method for efficiency.Note that this implementation will throw an UnsupportedOperationException if the iterator returned by this collection's iterator method does not implement the remove method and this collection is non-empty.
Exceptions
UnsupportedOperationException if the clear operation is not supported by this collection
This implementation repeatedly invokes poll until it returns false.
This implementation repeatedly invokes poll until it returns false.
Reimplemented from decaf::util::AbstractQueue< E >.
Referenced by decaf::util::concurrent::LinkedBlockingQueue< Pointer< Transport > >::operator=().
template<typename E> virtual int decaf::util::concurrent::LinkedBlockingQueue< E >::drainTo (Collection< E > & c) inline virtual
Removes all available elements from this queue and adds them to the given collection.
This operation may be more efficient than repeatedly polling this queue. A failure encountered while attempting to add elements to collection c may result in elements being in neither, either or both collections when the associated exception is thrown. Attempts to drain a queue to itself result in IllegalArgumentException. Further, the behavior of this operation is undefined if the specified collection is modified while the operation is in progress.
Parameters
c the collection to transfer elements into
Returns
the number of elements transferred
Exceptions
UnsupportedOperationException if addition of elements is not supported by the specified collection
IllegalArgumentException if the specified collection is this queue, or some property of an element of this queue prevents it from being added to the specified collection
Implements decaf::util::concurrent::BlockingQueue< E >.
Referenced by decaf::util::concurrent::LinkedBlockingQueue< Pointer< Transport > >::drainTo().
template<typename E> virtual int decaf::util::concurrent::LinkedBlockingQueue< E >::drainTo (Collection< E > & c, int maxElements) inline virtual
Removes at most the given number of available elements from this queue and adds them to the given collection.
A failure encountered while attempting to add elements to collection c may result in elements being in neither, either or both collections when the associated exception is thrown. Attempts to drain a queue to itself result in IllegalArgumentException. Further, the behavior of this operation is undefined if the specified collection is modified while the operation is in progress.
Parameters
c the collection to transfer elements into
maxElements the maximum number of elements to transfer
Returns
the number of elements transferred
Exceptions
UnsupportedOperationException if addition of elements is not supported by the specified collection
IllegalArgumentException if the specified collection is this queue, or some property of an element of this queue prevents it from being added to the specified collection
Implements decaf::util::concurrent::BlockingQueue< E >.
template<typename E> virtual decaf::util::Iterator<E>* decaf::util::concurrent::LinkedBlockingQueue< E >::iterator () inline virtual
Returns
an iterator over a set of elements of type T.
Implements decaf::lang::Iterable< E >.
Referenced by decaf::util::concurrent::LinkedBlockingQueue< Pointer< Transport > >::LinkedBlockingQueue().
template<typename E> virtual decaf::util::Iterator<E>* decaf::util::concurrent::LinkedBlockingQueue< E >::iterator () const inline virtual
Implements decaf::lang::Iterable< E >.
template<typename E> virtual bool decaf::util::concurrent::LinkedBlockingQueue< E >::offer (const E & e, long long timeout, const TimeUnit & unit) inline virtual
Inserts the specified element into this queue, waiting up to the specified wait time if necessary for space to become available.
Parameters
e the element to add
timeout how long to wait before giving up, in units of unit
unit a TimeUnit determining how to interpret the timeout parameter
Returns
true if successful, or false if the specified waiting time elapses before space is available
Exceptions
InterruptedException if interrupted while waiting
NullPointerException if the specified element is null
IllegalArgumentException if some property of the specified element prevents it from being added to this queue
Implements decaf::util::concurrent::BlockingQueue< E >.
template<typename E> virtual bool decaf::util::concurrent::LinkedBlockingQueue< E >::offer (const E & value) inline virtual
Inserts the specified element into the queue provided that the condition allows such an operation.
The method is generally preferable to the collection.add(E), since the latter might throw an exception if the operation fails.
Parameters
value the specified element to insert into the queue.
Returns
true if the operation succeeds and false if it fails.
Exceptions
NullPointerException if the Queue implementation does not allow Null values to be inserted into the Queue.
IllegalArgumentException if some property of the specified element prevents it from being added to this queue
Implements decaf::util::Queue< E >.
template<typename E> LinkedBlockingQueue<E>& decaf::util::concurrent::LinkedBlockingQueue< E >::operator= (const LinkedBlockingQueue< E > & queue) inline
template<typename E> LinkedBlockingQueue<E>& decaf::util::concurrent::LinkedBlockingQueue< E >::operator= (const Collection< E > & collection) inline
template<typename E> virtual bool decaf::util::concurrent::LinkedBlockingQueue< E >::peek (E & result) const inline virtual
Gets but not removes the element in the head of the queue.
The result if successful is assigned to the result parameter.
Parameters
result Reference to an instance of the contained type to assigned the removed value to.
Returns
true if the element at the head of the queue was removed and assigned to the result parameter.
Implements decaf::util::Queue< E >.
template<typename E> virtual bool decaf::util::concurrent::LinkedBlockingQueue< E >::poll (E & result, long long timeout, const TimeUnit & unit) inline virtual
Retrieves and removes the head of this queue, waiting up to the specified wait time if necessary for an element to become available.
Parameters
result the referenced value that will be assigned the value retrieved from the Queue. Undefined if this methods returned false.
timeout how long to wait before giving up, in units of unit
unit a TimeUnit determining how to interpret the timeout parameter.
Returns
true if successful or false if the specified waiting time elapses before an element is available.
Exceptions
InterruptedException if interrupted while waiting
Implements decaf::util::concurrent::BlockingQueue< E >.
template<typename E> virtual bool decaf::util::concurrent::LinkedBlockingQueue< E >::poll (E & result) inline virtual
Gets and removes the element in the head of the queue.
If the operation succeeds the value of the element at the head of the Queue is assigned to the result parameter and the method returns true. If the operation fails the method returns false and the value of the result parameter is undefined.
Parameters
result Reference to an instance of the contained type to assigned the removed value to.
Returns
true if the element at the head of the queue was removed and assigned to the result parameter.
Implements decaf::util::Queue< E >.
template<typename E> virtual void decaf::util::concurrent::LinkedBlockingQueue< E >::put (const E & value) inline virtual
Inserts the specified element into this queue, waiting if necessary for space to become available.
Parameters
value the element to add
Exceptions
InterruptedException if interrupted while waiting
NullPointerException if the specified element is null
IllegalArgumentException if some property of the specified element prevents it from being added to this queue
Implements decaf::util::concurrent::BlockingQueue< E >.
template<typename E> virtual int decaf::util::concurrent::LinkedBlockingQueue< E >::remainingCapacity () const inline virtual
Returns the number of additional elements that this queue can ideally (in the absence of memory or resource constraints) accept without blocking, or Integer::MAX_VALUE if there is no intrinsic limit.
Note that you cannot always tell if an attempt to insert an element will succeed by inspecting remainingCapacity because it may be the case that another thread is about to insert or remove an element.
Returns
the remaining capacity
Implements decaf::util::concurrent::BlockingQueue< E >.
template<typename E> virtual bool decaf::util::concurrent::LinkedBlockingQueue< E >::remove (const E & value) inline virtual
Removes a single instance of the specified element from the collection.More formally, removes an element e such that (value == NULL ? e == NULL : value == e), if this collection contains one or more such elements. Returns true if this collection contained the specified element (or equivalently, if this collection changed as a result of the call).
Parameters
value The reference to the element to remove from this Collection.
Returns
true if the collection was changed, false otherwise.
Exceptions
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
This implementation iterates over the collection looking for the specified element. If it finds the element, it removes the element from the collection using the iterator's remove method.Note that this implementation throws an UnsupportedOperationException if the iterator returned by this collection's iterator method does not implement the remove method and this collection contains the specified object.
This implementation iterates over the collection looking for the specified element. If it finds the element, it removes the element from the collection using the iterator's remove method.
Note that this implementation throws an UnsupportedOperationException if the iterator returned by this collection's iterator method does not implement the remove method and this collection contains the specified object.
Reimplemented from decaf::util::AbstractCollection< E >.
template<typename E> virtual int decaf::util::concurrent::LinkedBlockingQueue< E >::size () const inline virtual
Returns the number of elements in this collection.
If this collection contains more than Integer::MAX_VALUE elements, returns Integer::MAX_VALUE.
Returns
the number of elements in this collection
Implements decaf::util::Collection< E >.
Referenced by decaf::util::concurrent::LinkedBlockingQueue< Pointer< Transport > >::toArray().
template<typename E> virtual E decaf::util::concurrent::LinkedBlockingQueue< E >::take () inline virtual
Retrieves and removes the head of this queue, waiting if necessary until an element becomes available.
Returns
the head of this queue
Exceptions
InterruptedException if interrupted while waiting
Implements decaf::util::concurrent::BlockingQueue< E >.
template<typename E> virtual std::vector<E> decaf::util::concurrent::LinkedBlockingQueue< E >::toArray () const inline virtual
Answers an STL vector containing copies of all elements contained in this Collection.
All the elements in the array will not be referenced by the collection. The elements in the returned array will be sorted to the same order as those returned by the iterator of this collection itself if the collection guarantees the order.
Returns
an vector of copies of all the elements from this Collection
Reimplemented from decaf::util::AbstractCollection< E >.
template<typename E> virtual std::string decaf::util::concurrent::LinkedBlockingQueue< E >::toString () const inline virtual
Referenced by decaf::util::concurrent::LinkedBlockingQueue< Pointer< Transport > >::toString().
The documentation for this class was generated from the following file:
src/main/decaf/util/concurrent/LinkedBlockingQueue.h