activemq-cpp-3.3.0: activemq::util::CMSExceptionSupport Class Reference
activemq::util::CMSExceptionSupport Class Reference
#include <src/main/activemq/util/CMSExceptionSupport.h>
Public Member Functions
virtual ~CMSExceptionSupport ()
Static Public Member Functions
static cms::CMSException create (const std::string &msg, const decaf::lang::Exception &cause)
static cms::CMSException create (const decaf::lang::Exception &cause)
static cms::MessageEOFException createMessageEOFException (const decaf::lang::Exception &cause)
static cms::MessageFormatException createMessageFormatException (const decaf::lang::Exception &cause)
Constructor & Destructor Documentation
virtual activemq::util::CMSExceptionSupport::~CMSExceptionSupport () [virtual]
Member Function Documentation
static cms::CMSException activemq::util::CMSExceptionSupport::create (const std::string & msg, const decaf::lang::Exception & cause) [static]
static cms::CMSException activemq::util::CMSExceptionSupport::create (const decaf::lang::Exception & cause) [static]
static cms::MessageEOFException activemq::util::CMSExceptionSupport::createMessageEOFException (const decaf::lang::Exception & cause) [static]
static cms::MessageFormatException activemq::util::CMSExceptionSupport::createMessageFormatException (const decaf::lang::Exception & cause) [static]
Referenced by activemq::commands::ActiveMQMessageTemplate< cms::ObjectMessage >::getBooleanProperty(), activemq::commands::ActiveMQMessageTemplate< cms::ObjectMessage >::getByteProperty(), activemq::commands::ActiveMQMessageTemplate< cms::ObjectMessage >::getDoubleProperty(), activemq::commands::ActiveMQMessageTemplate< cms::ObjectMessage >::getFloatProperty(), activemq::commands::ActiveMQMessageTemplate< cms::ObjectMessage >::getIntProperty(), activemq::commands::ActiveMQMessageTemplate< cms::ObjectMessage >::getLongProperty(), activemq::commands::ActiveMQMessageTemplate< cms::ObjectMessage >::getShortProperty(), and activemq::commands::ActiveMQMessageTemplate< cms::ObjectMessage >::getStringProperty().
The documentation for this class was generated from the following file:
src/main/activemq/util/CMSExceptionSupport.h