activemq-cpp-3.6.0: decaf::util::StlList< E > Class Template Reference
decaf::util::StlList< E > Class Template Reference
List class that wraps the STL list object to provide a simpler interface and additional methods not provided by the STL type.
#include <src/main/decaf/util/StlList.h>
Data Structures
class ConstStlListIterator
class StlListIterator
Public Member Functions
StlList ()
Default constructor - does nothing.
StlList (const StlList &source)
Copy constructor - copies the content of the given set into this one.
StlList (const Collection< E > &source)
Copy constructor - copies the content of the given set into this one.
virtual bool equals (const Collection< E > &collection) const
Answers true if this Collection and the one given are the same size and if each element contained in the Collection given is equal to an element contained in this collection.
Parameters
collection - The Collection to be compared to this one.
Returns
true if this Collection is equal to the one given.
virtual void copy (const Collection< E > &collection)
Renders this Collection as a Copy of the given Collection.The default implementation iterates over the contents of the given collection adding each to this collection after first calling this Collection's clear method.
Parameters
collection The collection to mirror.
Exceptions
UnsupportedOperationExceptio if this is an unmodifiable collection.
IllegalStateException if the elements cannot be added at this time due to insertion restrictions.
virtual Iterator< E > * iterator ()
Returns
an iterator over a set of elements of type T.
virtual Iterator< E > * iterator () const
virtual ListIterator< E > * listIterator ()
Returns
a list iterator over the elements in this list (in proper sequence).
virtual ListIterator< E > * listIterator () const
virtual ListIterator< E > * listIterator (int index)
Parameters
index index of first element to be returned from the list iterator (by a call to the next method).
Returns
a list iterator of the elements in this list (in proper sequence), starting at the specified position in this list. The specified index indicates the first element that would be returned by an initial call to next. An initial call to previous would return the element with the specified index minus one.
Exceptions
IndexOutOfBoundsException if the index is out of range (index < 0 || index > size())
virtual ListIterator< E > * listIterator (int index) const
virtual void clear ()
Removes all of the elements from this collection (optional operation).The collection will be empty after this method returns.This implementation iterates over this collection, removing each element using the Iterator.remove operation. Most implementations will probably choose to override this method for efficiency.Note that this implementation will throw an UnsupportedOperationException if the iterator returned by this collection's iterator method does not implement the remove method and this collection is non-empty.
Exceptions
UnsupportedOperationException if the clear operation is not supported by this collection
virtual bool isEmpty () const
Returns true if this collection contains no elements.This implementation returns size() == 0.
Returns
true if the size method return 0.
virtual int size () const
Returns the number of elements in this collection.If this collection contains more than Integer::MAX_VALUE elements, returns Integer::MAX_VALUE.
Returns
the number of elements in this collection
virtual E get (int index) const
Gets the element contained at position passed.
Parameters
index The position to get.
Returns
value at index specified.
Exceptions
IndexOutOfBoundsException if the index given is less than zero or greater than the List size.
virtual E set (int index, const E &element)
Replaces the element at the specified position in this list with the specified element.
Parameters
index The index of the element to replace.
element The element to be stored at the specified position.
Returns
the element previously at the specified position.
Exceptions
IndexOutOfBoundsException if the index given is less than zero or greater than the List size.
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
IllegalArgumentException if some property of the element prevents it from being added to this collection
IllegalStateException if the element cannot be added at this time due to insertion restrictions.
virtual void add (int index, const E &element)
Inserts the specified element at the specified position in this list.
virtual bool add (const E &value)
Returns true if this collection changed as a result of the call.
virtual bool addAll (const Collection< E > &collection)
Adds all of the elements in the specified collection to this collection.The behavior of this operation is undefined if the specified collection is modified while the operation is in progress. (This implies that the behavior of this call is undefined if the specified collection is this collection, and this collection is nonempty.)
Parameters
collection The Collection whose elements are added to this one.
Returns
true if this collection changed as a result of the call
Exceptions
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
IllegalArgumentException if some property of an element prevents it from being added to this collection
IllegalStateException if an element cannot be added at this time due to insertion restrictions.
This implementation iterates over the specified collection, and adds each object returned by the iterator to this collection, in turn.Note that this implementation will throw an UnsupportedOperationException unless add is overridden (assuming the specified collection is non-empty).
virtual bool addAll (int index, const Collection< E > &collection)
Inserts all of the elements in the specified collection into this list at the specified position (optional operation).Shifts the element currently at that position (if any) and any subsequent elements to the right (increases their indices). The new elements will appear in this list in the order that they are returned by the specified collection's iterator. The behavior of this operation is undefined if the specified collection is modified while the operation is in progress. (Note that this will occur if the specified collection is this list, and it's nonempty.)
Parameters
index The index at which to insert the first element from the specified collection
source The Collection containing elements to be added to this list
Returns
true if this list changed as a result of the call
Exceptions
IndexOutOfBoundsException if the index given is less than zero or greater than the List size.
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
IllegalArgumentException if some property of the element prevents it from being added to this collection
IllegalStateException if the element cannot be added at this time due to insertion restrictions.
virtual bool remove (const E &value)
Removes a single instance of the specified element from the collection.More formally, removes an element e such that (value == NULL ? e == NULL : value == e), if this collection contains one or more such elements. Returns true if this collection contained the specified element (or equivalently, if this collection changed as a result of the call).
Parameters
value The reference to the element to remove from this Collection.
Returns
true if the collection was changed, false otherwise.
Exceptions
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
This implementation iterates over the collection looking for the specified element. If it finds the element, it removes the element from the collection using the iterator's remove method.Note that this implementation throws an UnsupportedOperationException if the iterator returned by this collection's iterator method does not implement the remove method and this collection contains the specified object.
virtual E removeAt (int index)
Removes the element at the specified position in this list.Shifts any subsequent elements to the left (subtracts one from their indices). Returns the element that was removed from the list.
Parameters
index - the index of the element to be removed.
Returns
the element previously at the specified position.
Exceptions
IndexOutOfBoundsException if the index given is less than zero or greater than the List size.
UnsupportedOperationExceptio if this is an unmodifiable collection.
virtual int indexOf (const E &value) const
Returns the index of the first occurrence of the specified element in this list, or -1 if this list does not contain the element.
virtual int lastIndexOf (const E &value) const
Returns the index of the last occurrence of the specified element in this list, or -1 if this list does not contain the element.
virtual bool contains (const E &value) const
Returns true if this collection contains the specified element.More formally, returns true if and only if this collection contains at least one element e such that (value == NULL ? e == NULL : value == e).
Parameters
value The value to check for presence in the collection.
Returns
true if there is at least one of the elements in the collection
Exceptions
NullPointerException if the Collection contains pointers and the Collection does not allow for NULL elements (optional check).
This implementation iterates over the elements in the collection, checking each element in turn for equality with the specified element.
Public Member Functions inherited from decaf::util::AbstractList< E >
AbstractList ()
virtual ~AbstractList ()
virtual void add (int index DECAF_UNUSED, const E &element DECAF_UNUSED)
virtual E set (int index DECAF_UNUSED, const E &element DECAF_UNUSED)
Public Member Functions inherited from decaf::util::List< E >
List ()
virtual ~List ()
Public Member Functions inherited from decaf::util::Collection< E >
virtual ~Collection ()
Public Member Functions inherited from decaf::lang::Iterable< E >
virtual ~Iterable ()
Public Member Functions inherited from decaf::util::concurrent::Synchronizable
virtual ~Synchronizable ()
Public Member Functions inherited from decaf::util::AbstractCollection< E >
AbstractCollection ()
virtual ~AbstractCollection ()
AbstractCollection< E > & operator= (const AbstractCollection< E > &collection)
Assignment Operator, copy element from the source collection to this collection after clearing any element stored in this collection.
virtual bool containsAll (const Collection< E > &collection) const
Returns true if this collection contains all of the elements in the specified collection.
Parameters
collection The Collection to compare to this one.
Exceptions
NullPointerException if the Collection contains pointers and the Collection does not allow for NULL elements (optional check).
virtual bool add (const E &value DECAF_UNUSED)
virtual bool removeAll (const Collection< E > &collection)
Removes all this collection's elements that are also contained in the specified collection (optional operation).After this call returns, this collection will contain no elements in common with the specified collection.
Parameters
collection The Collection whose elements are to be removed from this one.
Returns
true if the collection changed as a result of this call.
Exceptions
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
virtual bool retainAll (const Collection< E > &collection)
Retains only the elements in this collection that are contained in the specified collection (optional operation).In other words, removes from this collection all of its elements that are not contained in the specified collection.
Parameters
collection The Collection whose elements are to be retained.
Returns
true if the collection changed as a result of this call.
Exceptions
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
virtual std::vector< E > toArray () const
Answers an STL vector containing copies of all elements contained in this Collection.
virtual void lock ()
Locks the object.
virtual bool tryLock ()
Attempts to Lock the object, if the lock is already held by another thread than this method returns false.
virtual void unlock ()
Unlocks the object.
virtual void wait ()
Waits on a signal from this object, which is generated by a call to Notify.
virtual void wait (long long millisecs)
Waits on a signal from this object, which is generated by a call to Notify.
virtual void wait (long long millisecs, int nanos)
Waits on a signal from this object, which is generated by a call to Notify.
virtual void notify ()
Signals a waiter on this object that it can now wake up and continue.
virtual void notifyAll ()
Signals the waiters on this object that it can now wake up and continue.
Additional Inherited Members
Protected Member Functions inherited from decaf::util::AbstractList< E >
void removeRange (int start, int end)
Protected Attributes inherited from decaf::util::AbstractList< E >
int modCount
Detailed Description
template<typename E>
class decaf::util::StlList< E >
List class that wraps the STL list object to provide a simpler interface and additional methods not provided by the STL type.
Constructor & Destructor Documentation
template<typename E> decaf::util::StlList< E >::StlList () inline
Default constructor - does nothing.
template<typename E> decaf::util::StlList< E >::StlList (const StlList< E > & source) inline
Copy constructor - copies the content of the given set into this one.
Parameters
source The source set.
References decaf::util::StlList< E >::copy().
template<typename E> decaf::util::StlList< E >::StlList (const Collection< E > & source) inline
Copy constructor - copies the content of the given set into this one.
Parameters
source The source set.
References decaf::util::StlList< E >::copy().
Member Function Documentation
template<typename E> virtual void decaf::util::StlList< E >::add (int index, const E & element) inline virtual
Inserts the specified element at the specified position in this list.
Shifts the element currently at that position (if any) and any subsequent elements to the right (adds one to their indices).
Parameters
index The index at which the specified element is to be inserted.
element The element to be inserted in this List.
Exceptions
IndexOutOfBoundsException if the index is greater than size of the List.
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
IllegalArgumentException if some property of the element prevents it from being added to this collection
IllegalStateException if the element cannot be added at this time due to insertion restrictions.
Implements decaf::util::List< E >.
References decaf::util::StlList< E >::size().
template<typename E> virtual bool decaf::util::StlList< E >::add (const E & value) inline virtual
Returns true if this collection changed as a result of the call.
(Returns false if this collection does not permit duplicates and already contains the specified element.)
Collections that support this operation may place limitations on what elements may be added to this collection. In particular, some collections will refuse to add null elements, and others will impose restrictions on the type of elements that may be added. Collection classes should clearly specify in their documentation any restrictions on what elements may be added.
If a collection refuses to add a particular element for any reason other than that it already contains the element, it must throw an exception (rather than returning false). This preserves the invariant that a collection always contains the specified element after this call returns.
For non-pointer values, i.e. class instances or string's the object will be copied into the collection, thus the object must support being copied, must not hide the copy constructor and assignment operator.
Parameters
value The reference to the element to add to this Collection.
Returns
true if the element was added to this Collection.
Exceptions
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
IllegalArgumentException if some property of the element prevents it from being added to this collection
IllegalStateException if the element cannot be added at this time due to insertion restrictions.
Reimplemented from decaf::util::AbstractList< E >.
template<typename E> virtual bool decaf::util::StlList< E >::addAll (const Collection< E > & collection) inline virtual
Adds all of the elements in the specified collection to this collection.The behavior of this operation is undefined if the specified collection is modified while the operation is in progress. (This implies that the behavior of this call is undefined if the specified collection is this collection, and this collection is nonempty.)
Parameters
collection The Collection whose elements are added to this one.
Returns
true if this collection changed as a result of the call
Exceptions
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
IllegalArgumentException if some property of an element prevents it from being added to this collection
IllegalStateException if an element cannot be added at this time due to insertion restrictions.
This implementation iterates over the specified collection, and adds each object returned by the iterator to this collection, in turn.Note that this implementation will throw an UnsupportedOperationException unless add is overridden (assuming the specified collection is non-empty).
This implementation iterates over the specified collection, and adds each object returned by the iterator to this collection, in turn.
Note that this implementation will throw an UnsupportedOperationException unless add is overridden (assuming the specified collection is non-empty).
Reimplemented from decaf::util::AbstractCollection< E >.
References decaf::util::Collection< E >::isEmpty(), decaf::util::StlList< E >::listIterator(), and decaf::util::Collection< E >::toArray().
template<typename E> virtual bool decaf::util::StlList< E >::addAll (int index, const Collection< E > & collection) inline virtual
Inserts all of the elements in the specified collection into this list at the specified position (optional operation).Shifts the element currently at that position (if any) and any subsequent elements to the right (increases their indices). The new elements will appear in this list in the order that they are returned by the specified collection's iterator. The behavior of this operation is undefined if the specified collection is modified while the operation is in progress. (Note that this will occur if the specified collection is this list, and it's nonempty.)
Parameters
index The index at which to insert the first element from the specified collection
source The Collection containing elements to be added to this list
Returns
true if this list changed as a result of the call
Exceptions
IndexOutOfBoundsException if the index given is less than zero or greater than the List size.
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
IllegalArgumentException if some property of the element prevents it from being added to this collection
IllegalStateException if the element cannot be added at this time due to insertion restrictions.
Reimplemented from decaf::util::AbstractList< E >.
References decaf::util::Collection< E >::isEmpty(), decaf::util::StlList< E >::listIterator(), decaf::util::StlList< E >::size(), and decaf::util::Collection< E >::toArray().
template<typename E> virtual void decaf::util::StlList< E >::clear () inline virtual
Removes all of the elements from this collection (optional operation).The collection will be empty after this method returns.This implementation iterates over this collection, removing each element using the Iterator.remove operation. Most implementations will probably choose to override this method for efficiency.Note that this implementation will throw an UnsupportedOperationException if the iterator returned by this collection's iterator method does not implement the remove method and this collection is non-empty.
Exceptions
UnsupportedOperationException if the clear operation is not supported by this collection
Reimplemented from decaf::util::AbstractList< E >.
template<typename E> virtual bool decaf::util::StlList< E >::contains (const E & value) const inline virtual
Returns true if this collection contains the specified element.More formally, returns true if and only if this collection contains at least one element e such that (value == NULL ? e == NULL : value == e).
Parameters
value The value to check for presence in the collection.
Returns
true if there is at least one of the elements in the collection
Exceptions
NullPointerException if the Collection contains pointers and the Collection does not allow for NULL elements (optional check).
This implementation iterates over the elements in the collection, checking each element in turn for equality with the specified element.
This implementation iterates over the elements in the collection, checking each element in turn for equality with the specified element.
Reimplemented from decaf::util::AbstractCollection< E >.
template<typename E> virtual void decaf::util::StlList< E >::copy (const Collection< E > & collection) inline virtual
Renders this Collection as a Copy of the given Collection.The default implementation iterates over the contents of the given collection adding each to this collection after first calling this Collection's clear method.
Parameters
collection The collection to mirror.
Exceptions
UnsupportedOperationExceptio if this is an unmodifiable collection.
IllegalStateException if the elements cannot be added at this time due to insertion restrictions.
Reimplemented from decaf::util::AbstractCollection< E >.
References NULL.
Referenced by decaf::util::StlList< E >::StlList().
template<typename E> virtual bool decaf::util::StlList< E >::equals (const Collection< E > & collection) const inline virtual
Answers true if this Collection and the one given are the same size and if each element contained in the Collection given is equal to an element contained in this collection.
Parameters
collection - The Collection to be compared to this one.
Returns
true if this Collection is equal to the one given.
Reimplemented from decaf::util::AbstractCollection< E >.
References NULL.
template<typename E> virtual E decaf::util::StlList< E >::get (int index) const inline virtual
Gets the element contained at position passed.
Parameters
index The position to get.
Returns
value at index specified.
Exceptions
IndexOutOfBoundsException if the index given is less than zero or greater than the List size.
Implements decaf::util::List< E >.
References decaf::util::StlList< E >::size().
template<typename E> virtual int decaf::util::StlList< E >::indexOf (const E & value) const inline virtual
Returns the index of the first occurrence of the specified element in this list, or -1 if this list does not contain the element.
More formally, returns the lowest index i such that get(i) == value, or -1 if there is no such index.
Parameters
value The element to search for in this List.
Returns
the index of the first occurrence of the specified element in this list,
Exceptions
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
Reimplemented from decaf::util::AbstractList< E >.
template<typename E> virtual bool decaf::util::StlList< E >::isEmpty () const inline virtual
Returns true if this collection contains no elements.This implementation returns size() == 0.
Returns
true if the size method return 0.
Reimplemented from decaf::util::AbstractCollection< E >.
template<typename E> virtual Iterator<E>* decaf::util::StlList< E >::iterator () inline virtual
Returns
an iterator over a set of elements of type T.
Reimplemented from decaf::util::AbstractList< E >.
template<typename E> virtual Iterator<E>* decaf::util::StlList< E >::iterator () const inline virtual
Reimplemented from decaf::util::AbstractList< E >.
template<typename E> virtual int decaf::util::StlList< E >::lastIndexOf (const E & value) const inline virtual
Returns the index of the last occurrence of the specified element in this list, or -1 if this list does not contain the element.
More formally, returns the highest index i such that get(i) == value or -1 if there is no such index.
Parameters
value The element to search for in this List.
Returns
the index of the last occurrence of the specified element in this list.
Exceptions
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
Reimplemented from decaf::util::AbstractList< E >.
References decaf::util::StlList< E >::size().
template<typename E> virtual ListIterator<E>* decaf::util::StlList< E >::listIterator () inline virtual
Returns
a list iterator over the elements in this list (in proper sequence).
Reimplemented from decaf::util::AbstractList< E >.
Referenced by decaf::util::StlList< E >::addAll().
template<typename E> virtual ListIterator<E>* decaf::util::StlList< E >::listIterator () const inline virtual
Reimplemented from decaf::util::AbstractList< E >.
template<typename E> virtual ListIterator<E>* decaf::util::StlList< E >::listIterator (int index) inline virtual
Parameters
index index of first element to be returned from the list iterator (by a call to the next method).
Returns
a list iterator of the elements in this list (in proper sequence), starting at the specified position in this list. The specified index indicates the first element that would be returned by an initial call to next. An initial call to previous would return the element with the specified index minus one.
Exceptions
IndexOutOfBoundsException if the index is out of range (index < 0 || index > size())
Reimplemented from decaf::util::AbstractList< E >.
References decaf::util::StlList< E >::size().
template<typename E> virtual ListIterator<E>* decaf::util::StlList< E >::listIterator (int index) const inline virtual
Reimplemented from decaf::util::AbstractList< E >.
References decaf::util::StlList< E >::size().
template<typename E> virtual bool decaf::util::StlList< E >::remove (const E & value) inline virtual
Removes a single instance of the specified element from the collection.More formally, removes an element e such that (value == NULL ? e == NULL : value == e), if this collection contains one or more such elements. Returns true if this collection contained the specified element (or equivalently, if this collection changed as a result of the call).
Parameters
value The reference to the element to remove from this Collection.
Returns
true if the collection was changed, false otherwise.
Exceptions
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
This implementation iterates over the collection looking for the specified element. If it finds the element, it removes the element from the collection using the iterator's remove method.Note that this implementation throws an UnsupportedOperationException if the iterator returned by this collection's iterator method does not implement the remove method and this collection contains the specified object.
Reimplemented from decaf::util::AbstractCollection< E >.
References decaf::util::StlList< E >::size().
template<typename E> virtual E decaf::util::StlList< E >::removeAt (int index) inline virtual
Removes the element at the specified position in this list.Shifts any subsequent elements to the left (subtracts one from their indices). Returns the element that was removed from the list.
Parameters
index - the index of the element to be removed.
Returns
the element previously at the specified position.
Exceptions
IndexOutOfBoundsException if the index given is less than zero or greater than the List size.
UnsupportedOperationExceptio if this is an unmodifiable collection.
Reimplemented from decaf::util::AbstractList< E >.
References decaf::util::StlList< E >::size().
template<typename E> virtual E decaf::util::StlList< E >::set (int index , const E & element) inline virtual
Replaces the element at the specified position in this list with the specified element.
Parameters
index The index of the element to replace.
element The element to be stored at the specified position.
Returns
the element previously at the specified position.
Exceptions
IndexOutOfBoundsException if the index given is less than zero or greater than the List size.
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
IllegalArgumentException if some property of the element prevents it from being added to this collection
IllegalStateException if the element cannot be added at this time due to insertion restrictions.
Implements decaf::util::List< E >.
References decaf::util::StlList< E >::size().
template<typename E> virtual int decaf::util::StlList< E >::size () const inline virtual
Returns the number of elements in this collection.If this collection contains more than Integer::MAX_VALUE elements, returns Integer::MAX_VALUE.
Returns
the number of elements in this collection
Implements decaf::util::Collection< E >.
Referenced by decaf::util::StlList< E >::add(), decaf::util::StlList< E >::addAll(), decaf::util::StlList< E >::get(), decaf::util::StlList< E >::lastIndexOf(), decaf::util::StlList< E >::listIterator(), decaf::util::StlList< E >::remove(), decaf::util::StlList< E >::removeAt(), and decaf::util::StlList< E >::set().
The documentation for this class was generated from the following file:
src/main/decaf/util/StlList.h