activemq-cpp-3.4.0: decaf::lang::exceptions::NumberFormatException Class Reference
decaf::lang::exceptions::NumberFormatException Class Reference
#include <src/main/decaf/lang/exceptions/NumberFormatException.h>
Public Member Functions
NumberFormatException ()
Default Constructor.
NumberFormatException (const Exception &ex) throw ()
Conversion Constructor from some other Exception.
NumberFormatException (const NumberFormatException &ex) throw ()
Copy Constructor.
NumberFormatException (const char *file, const int lineNumber, const std::exception *cause, const char *msg,...) throw ()
Constructor - Initializes the file name and line number where this message occurred.
NumberFormatException (const std::exception *cause) throw ()
Constructor.
NumberFormatException (const char *file, const int lineNumber, const char *msg,...) throw ()
Constructor - Initializes the file name and line number where this message occured.
virtual NumberFormatException * clone () const
Clones this exception.
virtual ~NumberFormatException () throw ()
Constructor & Destructor Documentation
decaf::lang::exceptions::NumberFormatException::NumberFormatException () [inline]
Default Constructor.
Referenced by clone().
decaf::lang::exceptions::NumberFormatException::NumberFormatException (const Exception & ex) throw () [inline]
Conversion Constructor from some other Exception.
Parameters:
ex The Exception whose data is to be copied into this one.
decaf::lang::exceptions::NumberFormatException::NumberFormatException (const NumberFormatException & ex) throw () [inline]
Copy Constructor.
Parameters:
ex The Exception whose data is to be copied into this one.
decaf::lang::exceptions::NumberFormatException::NumberFormatException (const char * file, const int lineNumber, const std::exception * cause, const char * msg, ...) throw () [inline]
Constructor - Initializes the file name and line number where this message occurred.
Sets the message to report, using an optional list of arguments to parse into the message
Parameters:
file The file name where exception occurs
lineNumber The line number where the exception occurred.
cause The exception that was the cause for this one to be thrown.
msg The message to report
... list of primitives that are formatted into the message
References decaf::lang::Exception::buildMessage(), and decaf::lang::Exception::setMark().
decaf::lang::exceptions::NumberFormatException::NumberFormatException (const std::exception * cause) throw () [inline]
Constructor.
Parameters:
cause Pointer to the exception that caused this one to be thrown, the object is cloned caller retains ownership.
decaf::lang::exceptions::NumberFormatException::NumberFormatException (const char * file, const int lineNumber, const char * msg, ...) throw () [inline]
Constructor - Initializes the file name and line number where this message occured.
Sets the message to report, using an optional list of arguments to parse into the message
Parameters:
file The file name where exception occurs
lineNumber The line number where the exception occurred.
msg The message to report
... list of primitives that are formatted into the message
References decaf::lang::Exception::buildMessage(), and decaf::lang::Exception::setMark().
virtual decaf::lang::exceptions::NumberFormatException::~NumberFormatException () throw () [inline, virtual]
Member Function Documentation
virtual NumberFormatException* decaf::lang::exceptions::NumberFormatException::clone () const [inline, virtual]
Clones this exception.
This is useful for cases where you need to preserve the type of the original exception as well as the message. All subclasses should override.
Returns:
an new Exception instance that is a copy of this one.
Reimplemented from decaf::lang::Exception.
References NumberFormatException().
The documentation for this class was generated from the following file:
src/main/decaf/lang/exceptions/NumberFormatException.h