activemq-cpp-3.9.0: activemq::commands::BaseCommand Class Reference
activemq::commands::BaseCommand Class Reference
#include <src/main/activemq/commands/BaseCommand.h>
Public Member Functions
BaseCommand ()
virtual ~BaseCommand ()
virtual void setCommandId (int id)
Sets the Command Id of this Message.
virtual int getCommandId () const
Gets the Command Id of this Message.
virtual void setResponseRequired (const bool required)
Set if this Message requires a Response.
virtual bool isResponseRequired () const
Is a Response required for this Command.
virtual void copyDataStructure (const DataStructure *src)
Copy the contents of the passed object into this objects members, overwriting any existing data.
virtual std::string toString () const
Returns a string containing the information for this DataStructure such as its type and value of its elements.
virtual bool equals (const DataStructure *value) const
Compares the DataStructure passed in to this one, and returns if they are equivalent.
virtual bool isBrokerInfo () const
virtual bool isControlCommand () const
virtual bool isConnectionControl () const
virtual bool isConnectionError () const
virtual bool isConnectionInfo () const
virtual bool isConsumerInfo () const
virtual bool isConsumerControl () const
virtual bool isDestinationInfo () const
virtual bool isFlushCommand () const
virtual bool isMessage () const
virtual bool isMessageAck () const
virtual bool isMessagePull () const
virtual bool isKeepAliveInfo () const
virtual bool isMessageDispatch () const
virtual bool isMessageDispatchNotification () const
virtual bool isProducerAck () const
virtual bool isProducerInfo () const
virtual bool isResponse () const
virtual bool isRemoveInfo () const
virtual bool isRemoveSubscriptionInfo () const
virtual bool isReplayCommand () const
virtual bool isSessionInfo () const
virtual bool isShutdownInfo () const
virtual bool isTransactionInfo () const
virtual bool isWireFormatInfo () const
Public Member Functions inherited from activemq::commands::Command
virtual ~Command ()
virtual decaf::lang::Pointer
< commands::Command > visit (activemq::state::CommandVisitor *visitor)=0
Allows a Visitor to visit this command and return a response to the command based on the command type being visited.
Public Member Functions inherited from activemq::commands::BaseDataStructure
virtual ~BaseDataStructure ()
virtual bool isMarshalAware () const
Determine if the class implementing this interface is really wanting to be told about marshaling.
virtual void beforeMarshal (wireformat::WireFormat *wireFormat AMQCPP_UNUSED)
virtual void afterMarshal (wireformat::WireFormat *wireFormat AMQCPP_UNUSED)
virtual void beforeUnmarshal (wireformat::WireFormat *wireFormat AMQCPP_UNUSED)
virtual void afterUnmarshal (wireformat::WireFormat *wireFormat AMQCPP_UNUSED)
virtual void setMarshaledForm (wireformat::WireFormat *wireFormat AMQCPP_UNUSED, const std::vector< char > &data AMQCPP_UNUSED)
virtual std::vector< unsigned
char > getMarshaledForm (wireformat::WireFormat *wireFormat AMQCPP_UNUSED)
virtual void copyDataStructure (const DataStructure *src AMQCPP_UNUSED)
virtual bool equals (const DataStructure *value AMQCPP_UNUSED) const
Public Member Functions inherited from activemq::commands::DataStructure
virtual ~DataStructure ()
virtual unsigned char getDataStructureType () const =0
Get the DataStructure Type as defined in CommandTypes.h.
virtual DataStructure * cloneDataStructure () const =0
Clone this obbject and return a new instance that the caller now owns, this will be an exact copy of this one.
Public Member Functions inherited from activemq::wireformat::MarshalAware
virtual ~MarshalAware ()
virtual void beforeMarshal (WireFormat *wireFormat)=0
Called before marshaling is started to prepare the object to be marshaled.
virtual void afterMarshal (WireFormat *wireFormat)=0
Called after marshaling is started to cleanup the object being marshaled.
virtual void beforeUnmarshal (WireFormat *wireFormat)=0
Called before unmarshaling is started to prepare the object to be unmarshaled.
virtual void afterUnmarshal (WireFormat *wireFormat)=0
Called after unmarshaling is started to cleanup the object being unmarshaled.
virtual void setMarshaledForm (WireFormat *wireFormat, const std::vector< char > &data)=0
Called to set the data to this object that will contain the objects marshaled form.
virtual std::vector< unsigned
char > getMarshaledForm (WireFormat *wireFormat)=0
Called to get the data to this object that will contain the objects marshaled form.
Constructor & Destructor Documentation
activemq::commands::BaseCommand::BaseCommand () inline
virtual activemq::commands::BaseCommand::~BaseCommand () inline virtual
Member Function Documentation
virtual void activemq::commands::BaseCommand::copyDataStructure (const DataStructure * src) inline virtual
Copy the contents of the passed object into this objects members, overwriting any existing data.
Returns
src - Source Object
Implements activemq::commands::DataStructure.
Reimplemented in activemq::commands::Message, activemq::commands::ConsumerInfo, activemq::commands::BrokerError, activemq::commands::MessageAck, activemq::commands::BrokerInfo, activemq::commands::ConnectionInfo, activemq::commands::MessageDispatch, activemq::commands::ConnectionControl, activemq::commands::ConsumerControl, activemq::commands::ProducerInfo, activemq::commands::ActiveMQBytesMessage, activemq::commands::DestinationInfo, activemq::commands::MessagePull, activemq::commands::SessionInfo, activemq::commands::MessageDispatchNotification, activemq::commands::TransactionInfo, activemq::commands::ConnectionError, activemq::commands::RemoveSubscriptionInfo, activemq::commands::ProducerAck, activemq::commands::RemoveInfo, activemq::commands::DataArrayResponse, activemq::commands::DataResponse, activemq::commands::ExceptionResponse, activemq::commands::ReplayCommand, activemq::commands::ControlCommand, activemq::commands::IntegerResponse, activemq::commands::Response, activemq::commands::FlushCommand, activemq::commands::KeepAliveInfo, activemq::commands::ShutdownInfo, activemq::commands::ActiveMQStreamMessage, activemq::commands::ActiveMQMapMessage, activemq::commands::WireFormatInfo, activemq::commands::ActiveMQBlobMessage, activemq::commands::ActiveMQTextMessage, activemq::commands::ActiveMQObjectMessage, and activemq::commands::ActiveMQMessage.
References getCommandId(), and isResponseRequired().
virtual bool activemq::commands::BaseCommand::equals (const DataStructure * value) const inline virtual
Compares the DataStructure passed in to this one, and returns if they are equivalent.
Equivalent here means that they are of the same type, and that each element of the objects are the same.
Returns
true if DataStructure's are Equal.
Implements activemq::commands::DataStructure.
Reimplemented in activemq::commands::Message, activemq::commands::ConsumerInfo, activemq::commands::MessageAck, activemq::commands::BrokerInfo, activemq::commands::ConnectionInfo, activemq::commands::MessageDispatch, activemq::commands::ConnectionControl, activemq::commands::ConsumerControl, activemq::commands::ProducerInfo, activemq::commands::ActiveMQBytesMessage, activemq::commands::DestinationInfo, activemq::commands::MessagePull, activemq::commands::SessionInfo, activemq::commands::MessageDispatchNotification, activemq::commands::TransactionInfo, activemq::commands::ConnectionError, activemq::commands::RemoveSubscriptionInfo, activemq::commands::ProducerAck, activemq::commands::RemoveInfo, activemq::commands::DataArrayResponse, activemq::commands::DataResponse, activemq::commands::ExceptionResponse, activemq::commands::ReplayCommand, activemq::commands::ControlCommand, activemq::commands::IntegerResponse, activemq::commands::Response, activemq::commands::FlushCommand, activemq::commands::KeepAliveInfo, activemq::commands::ShutdownInfo, activemq::commands::ActiveMQStreamMessage, activemq::commands::ActiveMQMessageTemplate< T >, activemq::commands::ActiveMQMessageTemplate< cms::BytesMessage >, activemq::commands::ActiveMQMessageTemplate< cms::MapMessage >, activemq::commands::ActiveMQMessageTemplate< cms::Message >, activemq::commands::ActiveMQMessageTemplate< cms::StreamMessage >, activemq::commands::ActiveMQMessageTemplate< cms::TextMessage >, activemq::commands::ActiveMQMessageTemplate< cms::ObjectMessage >, activemq::commands::ActiveMQMapMessage, activemq::commands::WireFormatInfo, activemq::commands::ActiveMQBlobMessage, activemq::commands::ActiveMQTextMessage, activemq::commands::ActiveMQObjectMessage, and activemq::commands::ActiveMQMessage.
References activemq::commands::BaseDataStructure::equals().
virtual int activemq::commands::BaseCommand::getCommandId () const inline virtual
Gets the Command Id of this Message.
Returns
Command Id
Implements activemq::commands::Command.
Referenced by copyDataStructure().
virtual bool activemq::commands::BaseCommand::isBrokerInfo () const inline virtual
Implements activemq::commands::Command.
Reimplemented in activemq::commands::BrokerInfo.
virtual bool activemq::commands::BaseCommand::isConnectionControl () const inline virtual
Implements activemq::commands::Command.
Reimplemented in activemq::commands::ConnectionControl.
virtual bool activemq::commands::BaseCommand::isConnectionError () const inline virtual
Implements activemq::commands::Command.
Reimplemented in activemq::commands::ConnectionError.
virtual bool activemq::commands::BaseCommand::isConnectionInfo () const inline virtual
Implements activemq::commands::Command.
Reimplemented in activemq::commands::ConnectionInfo.
virtual bool activemq::commands::BaseCommand::isConsumerControl () const inline virtual
Implements activemq::commands::Command.
Reimplemented in activemq::commands::ConsumerControl.
virtual bool activemq::commands::BaseCommand::isConsumerInfo () const inline virtual
Implements activemq::commands::Command.
Reimplemented in activemq::commands::ConsumerInfo.
virtual bool activemq::commands::BaseCommand::isControlCommand () const inline virtual
Implements activemq::commands::Command.
Reimplemented in activemq::commands::ControlCommand.
virtual bool activemq::commands::BaseCommand::isDestinationInfo () const inline virtual
Implements activemq::commands::Command.
virtual bool activemq::commands::BaseCommand::isFlushCommand () const inline virtual
Implements activemq::commands::Command.
Reimplemented in activemq::commands::FlushCommand.
virtual bool activemq::commands::BaseCommand::isKeepAliveInfo () const inline virtual
Implements activemq::commands::Command.
Reimplemented in activemq::commands::KeepAliveInfo.
virtual bool activemq::commands::BaseCommand::isMessage () const inline virtual
Implements activemq::commands::Command.
Reimplemented in activemq::commands::Message.
virtual bool activemq::commands::BaseCommand::isMessageAck () const inline virtual
Implements activemq::commands::Command.
Reimplemented in activemq::commands::MessageAck.
virtual bool activemq::commands::BaseCommand::isMessageDispatch () const inline virtual
Implements activemq::commands::Command.
Reimplemented in activemq::commands::MessageDispatch.
virtual bool activemq::commands::BaseCommand::isMessageDispatchNotification () const inline virtual
Implements activemq::commands::Command.
Reimplemented in activemq::commands::MessageDispatchNotification.
virtual bool activemq::commands::BaseCommand::isMessagePull () const inline virtual
Implements activemq::commands::Command.
Reimplemented in activemq::commands::MessagePull.
virtual bool activemq::commands::BaseCommand::isProducerAck () const inline virtual
Implements activemq::commands::Command.
Reimplemented in activemq::commands::ProducerAck.
virtual bool activemq::commands::BaseCommand::isProducerInfo () const inline virtual
Implements activemq::commands::Command.
Reimplemented in activemq::commands::ProducerInfo.
virtual bool activemq::commands::BaseCommand::isRemoveInfo () const inline virtual
Implements activemq::commands::Command.
Reimplemented in activemq::commands::RemoveInfo.
virtual bool activemq::commands::BaseCommand::isRemoveSubscriptionInfo () const inline virtual
Implements activemq::commands::Command.
Reimplemented in activemq::commands::RemoveSubscriptionInfo.
virtual bool activemq::commands::BaseCommand::isReplayCommand () const inline virtual
Implements activemq::commands::Command.
Reimplemented in activemq::commands::ReplayCommand.
virtual bool activemq::commands::BaseCommand::isResponse () const inline virtual
Implements activemq::commands::Command.
Reimplemented in activemq::commands::Response.
virtual bool activemq::commands::BaseCommand::isResponseRequired () const inline virtual
Is a Response required for this Command.
Returns
true if a response is required.
Implements activemq::commands::Command.
Referenced by copyDataStructure().
virtual bool activemq::commands::BaseCommand::isSessionInfo () const inline virtual
Implements activemq::commands::Command.
virtual bool activemq::commands::BaseCommand::isShutdownInfo () const inline virtual
Implements activemq::commands::Command.
Reimplemented in activemq::commands::ShutdownInfo.
virtual bool activemq::commands::BaseCommand::isTransactionInfo () const inline virtual
Implements activemq::commands::Command.
Reimplemented in activemq::commands::TransactionInfo.
virtual bool activemq::commands::BaseCommand::isWireFormatInfo () const inline virtual
Implements activemq::commands::Command.
Reimplemented in activemq::commands::WireFormatInfo.
virtual void activemq::commands::BaseCommand::setCommandId (int id) inline virtual
Sets the Command Id of this Message.
Parameters
id Command Id
Implements activemq::commands::Command.
virtual void activemq::commands::BaseCommand::setResponseRequired (const bool required) inline virtual
Set if this Message requires a Response.
Parameters
required true if response is required
Implements activemq::commands::Command.
virtual std::string activemq::commands::BaseCommand::toString () const inline virtual
Returns a string containing the information for this DataStructure such as its type and value of its elements.
Returns
formatted string useful for debugging.
Implements activemq::commands::Command.
Reimplemented in activemq::commands::Message, activemq::commands::ConsumerInfo, activemq::commands::MessageAck, activemq::commands::BrokerInfo, activemq::commands::ConnectionInfo, activemq::commands::MessageDispatch, activemq::commands::ConnectionControl, activemq::commands::ConsumerControl, activemq::commands::ProducerInfo, activemq::commands::ActiveMQBytesMessage, activemq::commands::DestinationInfo, activemq::commands::MessagePull, activemq::commands::SessionInfo, activemq::commands::MessageDispatchNotification, activemq::commands::TransactionInfo, activemq::commands::ConnectionError, activemq::commands::RemoveSubscriptionInfo, activemq::commands::ProducerAck, activemq::commands::RemoveInfo, activemq::commands::DataArrayResponse, activemq::commands::DataResponse, activemq::commands::ExceptionResponse, activemq::commands::ReplayCommand, activemq::commands::ControlCommand, activemq::commands::IntegerResponse, activemq::commands::Response, activemq::commands::FlushCommand, activemq::commands::KeepAliveInfo, activemq::commands::ShutdownInfo, activemq::commands::ActiveMQStreamMessage, activemq::commands::ActiveMQMapMessage, activemq::commands::WireFormatInfo, activemq::commands::ActiveMQBlobMessage, activemq::commands::ActiveMQTextMessage, activemq::commands::ActiveMQObjectMessage, and activemq::commands::ActiveMQMessage.
References activemq::commands::BaseDataStructure::toString().
The documentation for this class was generated from the following file:
src/main/activemq/commands/BaseCommand.h