activemq-cpp-3.6.0: decaf::util::concurrent::CopyOnWriteArraySet< E > Class Template Reference
decaf::util::concurrent::CopyOnWriteArraySet< E > Class Template Reference
Since the CopyOnWriteArraySet and the CopyOnWriteArrayList share much of the same operational semantics this class uses the CopyOnWriteArrayList for all its underlying operations.
#include <src/main/decaf/util/concurrent/CopyOnWriteArraySet.h>
Public Member Functions
CopyOnWriteArraySet ()
CopyOnWriteArraySet (const Collection< E > &collection)
CopyOnWriteArraySet (const E *array, int size)
virtual ~CopyOnWriteArraySet ()
virtual void copy (const Collection< E > &collection)
Renders this Collection as a Copy of the given Collection.
virtual decaf::util::Iterator
< E > * iterator ()
virtual decaf::util::Iterator
< E > * iterator () const
virtual int size () const
Returns the number of elements in this collection.
virtual bool isEmpty () const
Returns true if this collection contains no elements.
virtual bool add (const E &value)
Returns true if this collection changed as a result of the call.
virtual bool addAll (const Collection< E > &collection)
Adds all of the elements in the specified collection to this collection.The behavior of this operation is undefined if the specified collection is modified while the operation is in progress. (This implies that the behavior of this call is undefined if the specified collection is this collection, and this collection is nonempty.)
Parameters
collection The Collection whose elements are added to this one.
Returns
true if this collection changed as a result of the call
Exceptions
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
IllegalArgumentException if some property of an element prevents it from being added to this collection
IllegalStateException if an element cannot be added at this time due to insertion restrictions.
This implementation iterates over the specified collection, and adds each object returned by the iterator to this collection, in turn.Note that this implementation will throw an UnsupportedOperationException unless add is overridden (assuming the specified collection is non-empty).
virtual void clear ()
Removes all of the elements from this collection (optional operation).
virtual bool contains (const E &value) const
Returns true if this collection contains the specified element.More formally, returns true if and only if this collection contains at least one element e such that (value == NULL ? e == NULL : value == e).
Parameters
value The value to check for presence in the collection.
Returns
true if there is at least one of the elements in the collection
Exceptions
NullPointerException if the Collection contains pointers and the Collection does not allow for NULL elements (optional check).
This implementation iterates over the elements in the collection, checking each element in turn for equality with the specified element.
virtual bool containsAll (const Collection< E > &collection) const
Returns true if this collection contains all of the elements in the specified collection.
Parameters
collection The Collection to compare to this one.
Exceptions
NullPointerException if the Collection contains pointers and the Collection does not allow for NULL elements (optional check).
This implementation iterates over the specified collection, checking each element returned by the iterator in turn to see if it's contained in this collection. If all elements are so contained true is returned, otherwise false.
virtual bool remove (const E &value)
Removes a single instance of the specified element from the collection.More formally, removes an element e such that (value == NULL ? e == NULL : value == e), if this collection contains one or more such elements. Returns true if this collection contained the specified element (or equivalently, if this collection changed as a result of the call).
Parameters
value The reference to the element to remove from this Collection.
Returns
true if the collection was changed, false otherwise.
Exceptions
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
This implementation iterates over the collection looking for the specified element. If it finds the element, it removes the element from the collection using the iterator's remove method.Note that this implementation throws an UnsupportedOperationException if the iterator returned by this collection's iterator method does not implement the remove method and this collection contains the specified object.
virtual bool removeAll (const Collection< E > &collection)
Removes all this collection's elements that are also contained in the specified collection (optional operation).After this call returns, this collection will contain no elements in common with the specified collection.
Parameters
collection The Collection whose elements are to be removed from this one.
Returns
true if the collection changed as a result of this call.
Exceptions
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
This implementation iterates over this collection, checking each element returned by the iterator in turn to see if it's contained in the specified collection. If it's so contained, it's removed from this collection with the iterator's remove method.Note that this implementation will throw an UnsupportedOperationException if the iterator returned by the iterator method does not implement the remove method and this collection contains one or more elements in common with the specified collection.This implementation determines which is the smaller of this set and the specified collection, by invoking the size method on each. If this set has fewer elements, then the implementation iterates over this set, checking each element returned by the iterator in turn to see if it is contained in the specified collection. If it is so contained, it is removed from this set with the iterator's remove method. If the specified collection has fewer elements, then the implementation iterates over the specified collection, removing from this set each element returned by the iterator, using this set's remove method.Note that this implementation will throw an UnsupportedOperationException if the iterator returned by the iterator method does not implement the remove method.
virtual bool retainAll (const Collection< E > &collection)
Retains only the elements in this collection that are contained in the specified collection (optional operation).In other words, removes from this collection all of its elements that are not contained in the specified collection.
Parameters
collection The Collection whose elements are to be retained.
Returns
true if the collection changed as a result of this call.
Exceptions
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
This implementation iterates over this collection, checking each element returned by the iterator in turn to see if it's contained in the specified collection. If it's not so contained, it's removed from this collection with the iterator's remove method.Note that this implementation will throw an UnsupportedOperationException if the iterator returned by the iterator method does not implement the remove method and this collection contains one or more elements not present in the specified collection.
virtual std::vector< E > toArray () const
Answers an STL vector containing copies of all elements contained in this Collection.
virtual bool equals (const Collection< E > &collection) const
Answers true if this Collection and the one given are the same size and if each element contained in the Collection given is equal to an element contained in this collection.
Public Member Functions inherited from decaf::util::AbstractSet< E >
virtual ~AbstractSet ()
Public Member Functions inherited from decaf::util::Set< E >
virtual ~Set ()
Public Member Functions inherited from decaf::util::Collection< E >
virtual ~Collection ()
Public Member Functions inherited from decaf::lang::Iterable< E >
virtual ~Iterable ()
Public Member Functions inherited from decaf::util::concurrent::Synchronizable
virtual ~Synchronizable ()
Public Member Functions inherited from decaf::util::AbstractCollection< E >
AbstractCollection ()
virtual ~AbstractCollection ()
AbstractCollection< E > & operator= (const AbstractCollection< E > &collection)
Assignment Operator, copy element from the source collection to this collection after clearing any element stored in this collection.
virtual bool add (const E &value DECAF_UNUSED)
virtual void lock ()
Locks the object.
virtual bool tryLock ()
Attempts to Lock the object, if the lock is already held by another thread than this method returns false.
virtual void unlock ()
Unlocks the object.
virtual void wait ()
Waits on a signal from this object, which is generated by a call to Notify.
virtual void wait (long long millisecs)
Waits on a signal from this object, which is generated by a call to Notify.
virtual void wait (long long millisecs, int nanos)
Waits on a signal from this object, which is generated by a call to Notify.
virtual void notify ()
Signals a waiter on this object that it can now wake up and continue.
virtual void notifyAll ()
Signals the waiters on this object that it can now wake up and continue.
Additional Inherited Members
Protected Attributes inherited from decaf::util::AbstractCollection< E >
util::concurrent::Mutex mutex
Detailed Description
template<typename E>
class decaf::util::concurrent::CopyOnWriteArraySet< E >
Since the CopyOnWriteArraySet and the CopyOnWriteArrayList share much of the same operational semantics this class uses the CopyOnWriteArrayList for all its underlying operations.
This collection is best used in applications where the Set size is usually small and write operations are minimal as they result in a copy of the underlying array being created. Reads are generally fast and the iterators provided by this collection do not block as they operate on a snapshot of the data taken at the time of their creation.
Since
1.0
Constructor & Destructor Documentation
template<typename E > decaf::util::concurrent::CopyOnWriteArraySet< E >::CopyOnWriteArraySet () inline
template<typename E > decaf::util::concurrent::CopyOnWriteArraySet< E >::CopyOnWriteArraySet (const Collection< E > & collection) inline
References decaf::util::concurrent::CopyOnWriteArraySet< E >::copy().
template<typename E > decaf::util::concurrent::CopyOnWriteArraySet< E >::CopyOnWriteArraySet (const E * array, int size) inline
References decaf::util::concurrent::CopyOnWriteArraySet< E >::size().
template<typename E > virtual decaf::util::concurrent::CopyOnWriteArraySet< E >::~CopyOnWriteArraySet () inline virtual
Member Function Documentation
template<typename E > virtual bool decaf::util::concurrent::CopyOnWriteArraySet< E >::add (const E & value) inline virtual
Returns true if this collection changed as a result of the call.
(Returns false if this collection does not permit duplicates and already contains the specified element.)
Collections that support this operation may place limitations on what elements may be added to this collection. In particular, some collections will refuse to add null elements, and others will impose restrictions on the type of elements that may be added. Collection classes should clearly specify in their documentation any restrictions on what elements may be added.
If a collection refuses to add a particular element for any reason other than that it already contains the element, it must throw an exception (rather than returning false). This preserves the invariant that a collection always contains the specified element after this call returns.
For non-pointer values, i.e. class instances or string's the object will be copied into the collection, thus the object must support being copied, must not hide the copy constructor and assignment operator.
Parameters
value The reference to the element to add to this Collection.
Returns
true if the element was added to this Collection.
Exceptions
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
IllegalArgumentException if some property of the element prevents it from being added to this collection
IllegalStateException if the element cannot be added at this time due to insertion restrictions.
Implements decaf::util::Collection< E >.
template<typename E > virtual bool decaf::util::concurrent::CopyOnWriteArraySet< E >::addAll (const Collection< E > & collection) inline virtual
Adds all of the elements in the specified collection to this collection.The behavior of this operation is undefined if the specified collection is modified while the operation is in progress. (This implies that the behavior of this call is undefined if the specified collection is this collection, and this collection is nonempty.)
Parameters
collection The Collection whose elements are added to this one.
Returns
true if this collection changed as a result of the call
Exceptions
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
IllegalArgumentException if some property of an element prevents it from being added to this collection
IllegalStateException if an element cannot be added at this time due to insertion restrictions.
This implementation iterates over the specified collection, and adds each object returned by the iterator to this collection, in turn.Note that this implementation will throw an UnsupportedOperationException unless add is overridden (assuming the specified collection is non-empty).
This implementation iterates over the specified collection, and adds each object returned by the iterator to this collection, in turn.
Note that this implementation will throw an UnsupportedOperationException unless add is overridden (assuming the specified collection is non-empty).
Reimplemented from decaf::util::AbstractCollection< E >.
template<typename E > virtual void decaf::util::concurrent::CopyOnWriteArraySet< E >::clear () inline virtual
Removes all of the elements from this collection (optional operation).
The collection will be empty after this method returns.
This implementation iterates over this collection, removing each element using the Iterator.remove operation. Most implementations will probably choose to override this method for efficiency.
Note that this implementation will throw an UnsupportedOperationException if the iterator returned by this collection's iterator method does not implement the remove method and this collection is non-empty.
Exceptions
UnsupportedOperationException if the clear operation is not supported by this collection
Reimplemented from decaf::util::AbstractCollection< E >.
template<typename E > virtual bool decaf::util::concurrent::CopyOnWriteArraySet< E >::contains (const E & value) const inline virtual
Returns true if this collection contains the specified element.More formally, returns true if and only if this collection contains at least one element e such that (value == NULL ? e == NULL : value == e).
Parameters
value The value to check for presence in the collection.
Returns
true if there is at least one of the elements in the collection
Exceptions
NullPointerException if the Collection contains pointers and the Collection does not allow for NULL elements (optional check).
This implementation iterates over the elements in the collection, checking each element in turn for equality with the specified element.
This implementation iterates over the elements in the collection, checking each element in turn for equality with the specified element.
Reimplemented from decaf::util::AbstractCollection< E >.
template<typename E > virtual bool decaf::util::concurrent::CopyOnWriteArraySet< E >::containsAll (const Collection< E > & collection) const inline virtual
Returns true if this collection contains all of the elements in the specified collection.
Parameters
collection The Collection to compare to this one.
Exceptions
NullPointerException if the Collection contains pointers and the Collection does not allow for NULL elements (optional check).
This implementation iterates over the specified collection, checking each element returned by the iterator in turn to see if it's contained in this collection. If all elements are so contained true is returned, otherwise false.
This implementation iterates over the specified collection, checking each element returned by the iterator in turn to see if it's contained in this collection. If all elements are so contained true is returned, otherwise false.
Reimplemented from decaf::util::AbstractCollection< E >.
template<typename E > virtual void decaf::util::concurrent::CopyOnWriteArraySet< E >::copy (const Collection< E > & collection) inline virtual
Renders this Collection as a Copy of the given Collection.
The default implementation iterates over the contents of the given collection adding each to this collection after first calling this Collection's clear method.
Parameters
collection The collection to mirror.
Exceptions
UnsupportedOperationExceptio if this is an unmodifiable collection.
IllegalStateException if the elements cannot be added at this time due to insertion restrictions.
Reimplemented from decaf::util::AbstractCollection< E >.
Referenced by decaf::util::concurrent::CopyOnWriteArraySet< E >::CopyOnWriteArraySet().
template<typename E > virtual bool decaf::util::concurrent::CopyOnWriteArraySet< E >::equals (const Collection< E > & collection) const inline virtual
Answers true if this Collection and the one given are the same size and if each element contained in the Collection given is equal to an element contained in this collection.
Parameters
collection - The Collection to be compared to this one.
Returns
true if this Collection is equal to the one given.
Reimplemented from decaf::util::AbstractCollection< E >.
References decaf::lang::Iterable< E >::iterator(), NULL, decaf::util::concurrent::CopyOnWriteArraySet< E >::size(), and decaf::util::Collection< E >::size().
template<typename E > virtual bool decaf::util::concurrent::CopyOnWriteArraySet< E >::isEmpty () const inline virtual
Returns true if this collection contains no elements.
This implementation returns size() == 0.
Returns
true if the size method return 0.
Reimplemented from decaf::util::AbstractCollection< E >.
template<typename E > virtual decaf::util::Iterator<E>* decaf::util::concurrent::CopyOnWriteArraySet< E >::iterator () inline virtual
Returns
an iterator over a set of elements of type T.
Implements decaf::lang::Iterable< E >.
template<typename E > virtual decaf::util::Iterator<E>* decaf::util::concurrent::CopyOnWriteArraySet< E >::iterator () const inline virtual
Implements decaf::lang::Iterable< E >.
template<typename E > virtual bool decaf::util::concurrent::CopyOnWriteArraySet< E >::remove (const E & value) inline virtual
Removes a single instance of the specified element from the collection.More formally, removes an element e such that (value == NULL ? e == NULL : value == e), if this collection contains one or more such elements. Returns true if this collection contained the specified element (or equivalently, if this collection changed as a result of the call).
Parameters
value The reference to the element to remove from this Collection.
Returns
true if the collection was changed, false otherwise.
Exceptions
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
This implementation iterates over the collection looking for the specified element. If it finds the element, it removes the element from the collection using the iterator's remove method.Note that this implementation throws an UnsupportedOperationException if the iterator returned by this collection's iterator method does not implement the remove method and this collection contains the specified object.
This implementation iterates over the collection looking for the specified element. If it finds the element, it removes the element from the collection using the iterator's remove method.
Note that this implementation throws an UnsupportedOperationException if the iterator returned by this collection's iterator method does not implement the remove method and this collection contains the specified object.
Reimplemented from decaf::util::AbstractCollection< E >.
template<typename E > virtual bool decaf::util::concurrent::CopyOnWriteArraySet< E >::removeAll (const Collection< E > & collection) inline virtual
Removes all this collection's elements that are also contained in the specified collection (optional operation).After this call returns, this collection will contain no elements in common with the specified collection.
Parameters
collection The Collection whose elements are to be removed from this one.
Returns
true if the collection changed as a result of this call.
Exceptions
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
This implementation iterates over this collection, checking each element returned by the iterator in turn to see if it's contained in the specified collection. If it's so contained, it's removed from this collection with the iterator's remove method.Note that this implementation will throw an UnsupportedOperationException if the iterator returned by the iterator method does not implement the remove method and this collection contains one or more elements in common with the specified collection.This implementation determines which is the smaller of this set and the specified collection, by invoking the size method on each. If this set has fewer elements, then the implementation iterates over this set, checking each element returned by the iterator in turn to see if it is contained in the specified collection. If it is so contained, it is removed from this set with the iterator's remove method. If the specified collection has fewer elements, then the implementation iterates over the specified collection, removing from this set each element returned by the iterator, using this set's remove method.Note that this implementation will throw an UnsupportedOperationException if the iterator returned by the iterator method does not implement the remove method.
This implementation determines which is the smaller of this set and the specified collection, by invoking the size method on each. If this set has fewer elements, then the implementation iterates over this set, checking each element returned by the iterator in turn to see if it is contained in the specified collection. If it is so contained, it is removed from this set with the iterator's remove method. If the specified collection has fewer elements, then the implementation iterates over the specified collection, removing from this set each element returned by the iterator, using this set's remove method.
Note that this implementation will throw an UnsupportedOperationException if the iterator returned by the iterator method does not implement the remove method.
Reimplemented from decaf::util::AbstractSet< E >.
template<typename E > virtual bool decaf::util::concurrent::CopyOnWriteArraySet< E >::retainAll (const Collection< E > & collection) inline virtual
Retains only the elements in this collection that are contained in the specified collection (optional operation).In other words, removes from this collection all of its elements that are not contained in the specified collection.
Parameters
collection The Collection whose elements are to be retained.
Returns
true if the collection changed as a result of this call.
Exceptions
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
This implementation iterates over this collection, checking each element returned by the iterator in turn to see if it's contained in the specified collection. If it's not so contained, it's removed from this collection with the iterator's remove method.Note that this implementation will throw an UnsupportedOperationException if the iterator returned by the iterator method does not implement the remove method and this collection contains one or more elements not present in the specified collection.
This implementation iterates over this collection, checking each element returned by the iterator in turn to see if it's contained in the specified collection. If it's not so contained, it's removed from this collection with the iterator's remove method.
Note that this implementation will throw an UnsupportedOperationException if the iterator returned by the iterator method does not implement the remove method and this collection contains one or more elements not present in the specified collection.
Reimplemented from decaf::util::AbstractCollection< E >.
template<typename E > virtual int decaf::util::concurrent::CopyOnWriteArraySet< E >::size () const inline virtual
Returns the number of elements in this collection.
If this collection contains more than Integer::MAX_VALUE elements, returns Integer::MAX_VALUE.
Returns
the number of elements in this collection
Implements decaf::util::Collection< E >.
Referenced by decaf::util::concurrent::CopyOnWriteArraySet< E >::CopyOnWriteArraySet(), and decaf::util::concurrent::CopyOnWriteArraySet< E >::equals().
template<typename E > virtual std::vector<E> decaf::util::concurrent::CopyOnWriteArraySet< E >::toArray () const inline virtual
Answers an STL vector containing copies of all elements contained in this Collection.
All the elements in the array will not be referenced by the collection. The elements in the returned array will be sorted to the same order as those returned by the iterator of this collection itself if the collection guarantees the order.
Returns
an vector of copies of all the elements from this Collection
Reimplemented from decaf::util::AbstractCollection< E >.
The documentation for this class was generated from the following file:
src/main/decaf/util/concurrent/CopyOnWriteArraySet.h