activemq-cpp-3.3.0: decaf::util::ArrayList< E > Class Template Reference
decaf::util::ArrayList< E > Class Template Reference
#include <src/main/decaf/util/ArrayList.h>
Public Member Functions
ArrayList ()
ArrayList (const Collection< E > &collection)
ArrayList (const ArrayList< E > &arrayList)
ArrayList (int initialCapacity)
virtual ~ArrayList ()
ArrayList< E > & operator= (const ArrayList< E > &list)
ArrayList< E > & operator= (const Collection< E > &collection)
void ensureCapacity (int minimumCapacity)
Increases the capacity of this ArrayList instance, if necessary, to ensure that it can hold at least the number of elements specified by the minimum capacity argument.
void trimToSize ()
Trims the internal array to match the current size of the ArrayList.
virtual void clear ()
Removes all of the elements from this collection (optional operation).
virtual bool isEmpty () const
Returns true if this collection contains no elements.
virtual int size () const
Returns the number of elements in this collection.
virtual E set (int index, const E &element)
Replaces the element at the specified position in this list with the specified element.
virtual E get (int index) const
Gets the element contained at position passed.
virtual bool add (const E &value)
Returns true if this collection changed as a result of the call.
virtual void add (int index, const E &element)
Inserts the specified element at the specified position in this list.
virtual bool addAll (const Collection< E > &collection)
Adds all of the elements in the specified collection to this collection.The behavior of this operation is undefined if the specified collection is modified while the operation is in progress. (This implies that the behavior of this call is undefined if the specified collection is this collection, and this collection is nonempty.)
Parameters:
collection The Collection whose elements are added to this one.
Returns:
true if this collection changed as a result of the call
Exceptions:
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
IllegalArgumentException if some property of an element prevents it from being added to this collection
IllegalStateException if an element cannot be added at this time due to insertion restrictions.
This implementation iterates over the specified collection, and adds each object returned by the iterator to this collection, in turn.Note that this implementation will throw an UnsupportedOperationException unless add is overridden (assuming the specified collection is non-empty).
virtual bool addAll (int index, const Collection< E > &collection)
Inserts all of the elements in the specified collection into this list at the specified position (optional operation).
virtual bool remove (const E &value)
Removes a single instance of the specified element from the collection.More formally, removes an element e such that (value == NULL ? e == NULL : value == e), if this collection contains one or more such elements. Returns true if this collection contained the specified element (or equivalently, if this collection changed as a result of the call).
Parameters:
value The reference to the element to remove from this Collection.
Returns:
true if the collection was changed, false otherwise.
Exceptions:
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
This implementation iterates over the collection looking for the specified element. If it finds the element, it removes the element from the collection using the iterator's remove method.Note that this implementation throws an UnsupportedOperationException if the iterator returned by this collection's iterator method does not implement the remove method and this collection contains the specified object.
virtual E removeAt (int index)
Removes the element at the specified position in this list.
virtual bool contains (const E &value) const
Returns true if this collection contains the specified element.More formally, returns true if and only if this collection contains at least one element e such that (value == NULL ? e == NULL : value == e).
Parameters:
value The value to check for presence in the collection.
Returns:
true if there is at least one of the elements in the collection
Exceptions:
NullPointerException if the Collection contains pointers and the Collection does not allow for NULL elements (optional check).
This implementation iterates over the elements in the collection, checking each element in turn for equality with the specified element.
virtual int indexOf (const E &value) const
Returns the index of the first occurrence of the specified element in this list, or -1 if this list does not contain the element.
virtual int lastIndexOf (const E &value) const
Returns the index of the last occurrence of the specified element in this list, or -1 if this list does not contain the element.
virtual std::vector< E > toArray () const
Answers an STL vector containing copies of all elements contained in this Collection.
virtual std::string toString () const
template<typename E>
class decaf::util::ArrayList< E >
Constructor & Destructor Documentation
template<typename E> decaf::util::ArrayList< E >::ArrayList () [inline]
References decaf::util::ArrayList< E >::ensureCapacity().
template<typename E> decaf::util::ArrayList< E >::ArrayList (const Collection< E > & collection) [inline]
References decaf::lang::Iterable< E >::iterator(), and decaf::util::Collection< E >::size().
template<typename E> decaf::util::ArrayList< E >::ArrayList (const ArrayList< E > & arrayList) [inline]
References decaf::util::AbstractList< E >::iterator(), and decaf::util::ArrayList< E >::size().
template<typename E> decaf::util::ArrayList< E >::ArrayList (int initialCapacity) [inline]
template<typename E> virtual decaf::util::ArrayList< E >::~ArrayList () [inline, virtual]
References DECAF_CATCHALL_NOTHROW.
Member Function Documentation
template<typename E> virtual bool decaf::util::ArrayList< E >::add (const E & value) [inline, virtual]
Returns true if this collection changed as a result of the call.
(Returns false if this collection does not permit duplicates and already contains the specified element.)
Collections that support this operation may place limitations on what elements may be added to this collection. In particular, some collections will refuse to add null elements, and others will impose restrictions on the type of elements that may be added. Collection classes should clearly specify in their documentation any restrictions on what elements may be added.
If a collection refuses to add a particular element for any reason other than that it already contains the element, it must throw an exception (rather than returning false). This preserves the invariant that a collection always contains the specified element after this call returns.
For non-pointer values, i.e. class instances or string's the object will be copied into the collection, thus the object must support being copied, must not hide the copy constructor and assignment operator.
Parameters:
value The reference to the element to add to this Collection.
Returns:
true if the element was added to this Collection.
Exceptions:
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
IllegalArgumentException if some property of the element prevents it from being added to this collection
IllegalStateException if the element cannot be added at this time due to insertion restrictions.
Reimplemented from decaf::util::AbstractList< E >.
template<typename E> virtual void decaf::util::ArrayList< E >::add (int index, const E & element) [inline, virtual]
Inserts the specified element at the specified position in this list.
Shifts the element currently at that position (if any) and any subsequent elements to the right (adds one to their indices).
Parameters:
index The index at which the specified element is to be inserted.
element The element to be inserted in this List.
Exceptions:
IndexOutOfBoundsException if the index is greater than size of the List.
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
IllegalArgumentException if some property of the element prevents it from being added to this collection
IllegalStateException if the element cannot be added at this time due to insertion restrictions.
Implements decaf::util::List< E >.
template<typename E> virtual bool decaf::util::ArrayList< E >::addAll (const Collection< E > & collection) [inline, virtual]
Adds all of the elements in the specified collection to this collection.The behavior of this operation is undefined if the specified collection is modified while the operation is in progress. (This implies that the behavior of this call is undefined if the specified collection is this collection, and this collection is nonempty.)
Parameters:
collection The Collection whose elements are added to this one.
Returns:
true if this collection changed as a result of the call
Exceptions:
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
IllegalArgumentException if some property of an element prevents it from being added to this collection
IllegalStateException if an element cannot be added at this time due to insertion restrictions.
This implementation iterates over the specified collection, and adds each object returned by the iterator to this collection, in turn.Note that this implementation will throw an UnsupportedOperationException unless add is overridden (assuming the specified collection is non-empty).
This implementation iterates over the specified collection, and adds each object returned by the iterator to this collection, in turn.
Note that this implementation will throw an UnsupportedOperationException unless add is overridden (assuming the specified collection is non-empty).
Reimplemented from decaf::util::AbstractCollection< E >.
References decaf::util::Collection< E >::size(), and decaf::util::Collection< E >::toArray().
Referenced by decaf::util::ArrayList< E >::operator=().
template<typename E> virtual bool decaf::util::ArrayList< E >::addAll (int index, const Collection< E > & source) [inline, virtual]
Inserts all of the elements in the specified collection into this list at the specified position (optional operation).
Shifts the element currently at that position (if any) and any subsequent elements to the right (increases their indices). The new elements will appear in this list in the order that they are returned by the specified collection's iterator. The behavior of this operation is undefined if the specified collection is modified while the operation is in progress. (Note that this will occur if the specified collection is this list, and it's nonempty.)
Parameters:
index The index at which to insert the first element from the specified collection
source The Collection containing elements to be added to this list
Returns:
true if this list changed as a result of the call
Exceptions:
IndexOutOfBoundsException if the index given is less than zero or greater than the List size.
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
IllegalArgumentException if some property of the element prevents it from being added to this collection
IllegalStateException if the element cannot be added at this time due to insertion restrictions.
Reimplemented from decaf::util::AbstractList< E >.
References decaf::util::Collection< E >::size(), and decaf::util::Collection< E >::toArray().
template<typename E> virtual void decaf::util::ArrayList< E >::clear () [inline, virtual]
Removes all of the elements from this collection (optional operation).
The collection will be empty after this method returns.
This implementation iterates over this collection, removing each element using the Iterator.remove operation. Most implementations will probably choose to override this method for efficiency.
Note that this implementation will throw an UnsupportedOperationException if the iterator returned by this collection's iterator method does not implement the remove method and this collection is non-empty.
Exceptions:
UnsupportedOperationException if the clear operation is not supported by this collection
Reimplemented from decaf::util::AbstractList< E >.
Referenced by decaf::util::ArrayList< E >::operator=().
template<typename E> virtual bool decaf::util::ArrayList< E >::contains (const E & value) const [inline, virtual]
Returns true if this collection contains the specified element.More formally, returns true if and only if this collection contains at least one element e such that (value == NULL ? e == NULL : value == e).
Parameters:
value The value to check for presence in the collection.
Returns:
true if there is at least one of the elements in the collection
Exceptions:
NullPointerException if the Collection contains pointers and the Collection does not allow for NULL elements (optional check).
This implementation iterates over the elements in the collection, checking each element in turn for equality with the specified element.
This implementation iterates over the elements in the collection, checking each element in turn for equality with the specified element.
Reimplemented from decaf::util::AbstractCollection< E >.
References decaf::util::ArrayList< E >::indexOf().
template<typename E> void decaf::util::ArrayList< E >::ensureCapacity (int minimumCapacity) [inline]
Increases the capacity of this ArrayList instance, if necessary, to ensure that it can hold at least the number of elements specified by the minimum capacity argument.
If the capacity is already greater than or equal to the minimum capacity argument then the array is left unchanged.
Parameters:
minimumCapacity The desired minimum capacity for this ArrayList.
References decaf::lang::System::arraycopy().
Referenced by decaf::util::ArrayList< E >::ArrayList().
template<typename E> virtual E decaf::util::ArrayList< E >::get (int index) const [inline, virtual]
Gets the element contained at position passed.
Parameters:
index The position to get.
Returns:
value at index specified.
Exceptions:
IndexOutOfBoundsException if the index given is less than zero or greater than the List size.
Implements decaf::util::List< E >.
template<typename E> virtual int decaf::util::ArrayList< E >::indexOf (const E & value) const [inline, virtual]
Returns the index of the first occurrence of the specified element in this list, or -1 if this list does not contain the element.
More formally, returns the lowest index i such that get(i) == value, or -1 if there is no such index.
Parameters:
value The element to search for in this List.
Returns:
the index of the first occurrence of the specified element in this list,
Exceptions:
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
Reimplemented from decaf::util::AbstractList< E >.
Referenced by decaf::util::ArrayList< E >::contains(), and decaf::util::ArrayList< E >::remove().
template<typename E> virtual bool decaf::util::ArrayList< E >::isEmpty () const [inline, virtual]
Returns true if this collection contains no elements.
This implementation returns size() == 0.
Returns:
true if the size method return 0.
Reimplemented from decaf::util::AbstractCollection< E >.
template<typename E> virtual int decaf::util::ArrayList< E >::lastIndexOf (const E & value) const [inline, virtual]
Returns the index of the last occurrence of the specified element in this list, or -1 if this list does not contain the element.
More formally, returns the highest index i such that get(i) == value or -1 if there is no such index.
Parameters:
value The element to search for in this List.
Returns:
the index of the last occurrence of the specified element in this list.
Exceptions:
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
Reimplemented from decaf::util::AbstractList< E >.
template<typename E> ArrayList<E>& decaf::util::ArrayList< E >::operator= (const Collection< E > & collection) [inline]
References decaf::util::ArrayList< E >::addAll(), and decaf::util::ArrayList< E >::clear().
template<typename E> ArrayList<E>& decaf::util::ArrayList< E >::operator= (const ArrayList< E > & list) [inline]
References decaf::util::ArrayList< E >::addAll(), and decaf::util::ArrayList< E >::clear().
template<typename E> virtual bool decaf::util::ArrayList< E >::remove (const E & value) [inline, virtual]
Removes a single instance of the specified element from the collection.More formally, removes an element e such that (value == NULL ? e == NULL : value == e), if this collection contains one or more such elements. Returns true if this collection contained the specified element (or equivalently, if this collection changed as a result of the call).
Parameters:
value The reference to the element to remove from this Collection.
Returns:
true if the collection was changed, false otherwise.
Exceptions:
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
This implementation iterates over the collection looking for the specified element. If it finds the element, it removes the element from the collection using the iterator's remove method.Note that this implementation throws an UnsupportedOperationException if the iterator returned by this collection's iterator method does not implement the remove method and this collection contains the specified object.
This implementation iterates over the collection looking for the specified element. If it finds the element, it removes the element from the collection using the iterator's remove method.
Note that this implementation throws an UnsupportedOperationException if the iterator returned by this collection's iterator method does not implement the remove method and this collection contains the specified object.
Reimplemented from decaf::util::AbstractCollection< E >.
References decaf::util::ArrayList< E >::indexOf(), and decaf::util::ArrayList< E >::removeAt().
template<typename E> virtual E decaf::util::ArrayList< E >::removeAt (int index) [inline, virtual]
Removes the element at the specified position in this list.
Shifts any subsequent elements to the left (subtracts one from their indices). Returns the element that was removed from the list.
Parameters:
index - the index of the element to be removed.
Returns:
the element previously at the specified position.
Exceptions:
IndexOutOfBoundsException if the index given is less than zero or greater than the List size.
UnsupportedOperationExceptio if this is an unmodifiable collection.
Reimplemented from decaf::util::AbstractList< E >.
References decaf::lang::System::arraycopy().
Referenced by decaf::util::ArrayList< E >::remove().
template<typename E> virtual E decaf::util::ArrayList< E >::set (int index, const E & element) [inline, virtual]
Replaces the element at the specified position in this list with the specified element.
Parameters:
index The index of the element to replace.
element The element to be stored at the specified position.
Returns:
the element previously at the specified position.
Exceptions:
IndexOutOfBoundsException if the index given is less than zero or greater than the List size.
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
IllegalArgumentException if some property of the element prevents it from being added to this collection
IllegalStateException if the element cannot be added at this time due to insertion restrictions.
Implements decaf::util::List< E >.
template<typename E> virtual int decaf::util::ArrayList< E >::size () const [inline, virtual]
Returns the number of elements in this collection.
If this collection contains more than Integer::MAX_VALUE elements, returns Integer::MAX_VALUE.
Returns:
the number of elements in this collection
Implements decaf::util::Collection< E >.
Referenced by decaf::util::ArrayList< E >::ArrayList().
template<typename E> virtual std::vector<E> decaf::util::ArrayList< E >::toArray () const [inline, virtual]
Answers an STL vector containing copies of all elements contained in this Collection.
All the elements in the array will not be referenced by the collection. The elements in the returned array will be sorted to the same order as those returned by the iterator of this collection itself if the collection guarantees the order.
Returns:
an vector of copies of all the elements from this Collection
Reimplemented from decaf::util::AbstractCollection< E >.
template<typename E> virtual std::string decaf::util::ArrayList< E >::toString () const [inline, virtual]
References decaf::lang::Integer::toString().
template<typename E> void decaf::util::ArrayList< E >::trimToSize () [inline]
Trims the internal array to match the current size of the ArrayList.
This compacts the internal array to save storage space used by this ArrayList.
References decaf::lang::System::arraycopy().
The documentation for this class was generated from the following file:
src/main/decaf/util/ArrayList.h