activemq-cpp-3.4.0: decaf::util::StlSet< E > Class Template Reference
decaf::util::StlSet< E > Class Template Reference
Set template that wraps around a std::set to provide a more user-friendly interface and to provide common functions that do not exist in std::set.
#include <src/main/decaf/util/StlSet.h>
Data Structures
class ConstSetIterator
class SetIterator
Public Member Functions
StlSet ()
Default constructor - does nothing.
StlSet (const StlSet &source)
Copy constructor - copies the content of the given set into this one.
StlSet (const Collection< E > &source)
Copy constructor - copies the content of the given set into this one.
virtual ~StlSet ()
Iterator< E > * iterator ()
Returns:
an iterator over a set of elements of type T.
Iterator< E > * iterator () const
virtual bool equals (const Collection< E > &collection) const
Answers true if this Collection and the one given are the same size and if each element contained in the Collection given is equal to an element contained in this collection.
Parameters:
collection - The Collection to be compared to this one.
Returns:
true if this Collection is equal to the one given.
virtual void copy (const Collection< E > &collection)
Renders this Collection as a Copy of the given Collection.The default implementation iterates over the contents of the given collection adding each to this collection after first calling this Collection's clear method.
Parameters:
collection The collection to mirror.
Exceptions:
UnsupportedOperationExceptio if this is an unmodifiable collection.
IllegalStateException if the elements cannot be added at this time due to insertion restrictions.
virtual void clear ()
Removes all of the elements from this collection (optional operation).The collection will be empty after this method returns.This implementation iterates over this collection, removing each element using the Iterator.remove operation. Most implementations will probably choose to override this method for efficiency.Note that this implementation will throw an UnsupportedOperationException if the iterator returned by this collection's iterator method does not implement the remove method and this collection is non-empty.
Exceptions:
UnsupportedOperationException if the clear operation is not supported by this collection
virtual bool contains (const E &value) const
Returns true if this collection contains the specified element.More formally, returns true if and only if this collection contains at least one element e such that (value == NULL ? e == NULL : value == e).
Parameters:
value The value to check for presence in the collection.
Returns:
true if there is at least one of the elements in the collection
Exceptions:
NullPointerException if the Collection contains pointers and the Collection does not allow for NULL elements (optional check).
This implementation iterates over the elements in the collection, checking each element in turn for equality with the specified element.
virtual bool isEmpty () const
virtual int size () const
virtual bool add (const E &value)
Returns true if this collection changed as a result of the call.(Returns false if this collection does not permit duplicates and already contains the specified element.)Collections that support this operation may place limitations on what elements may be added to this collection. In particular, some collections will refuse to add null elements, and others will impose restrictions on the type of elements that may be added. Collection classes should clearly specify in their documentation any restrictions on what elements may be added.If a collection refuses to add a particular element for any reason other than that it already contains the element, it must throw an exception (rather than returning false). This preserves the invariant that a collection always contains the specified element after this call returns.For non-pointer values, i.e. class instances or string's the object will be copied into the collection, thus the object must support being copied, must not hide the copy constructor and assignment operator.
Parameters:
value The reference to the element to add to this Collection.
Returns:
true if the element was added to this Collection.
Exceptions:
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
IllegalArgumentException if some property of the element prevents it from being added to this collection
IllegalStateException if the element cannot be added at this time due to insertion restrictions.
virtual bool remove (const E &value)
Removes a single instance of the specified element from the collection.More formally, removes an element e such that (value == NULL ? e == NULL : value == e), if this collection contains one or more such elements. Returns true if this collection contained the specified element (or equivalently, if this collection changed as a result of the call).
Parameters:
value The reference to the element to remove from this Collection.
Returns:
true if the collection was changed, false otherwise.
Exceptions:
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
This implementation iterates over the collection looking for the specified element. If it finds the element, it removes the element from the collection using the iterator's remove method.Note that this implementation throws an UnsupportedOperationException if the iterator returned by this collection's iterator method does not implement the remove method and this collection contains the specified object.
Detailed Description
template<typename E>
class decaf::util::StlSet< E >
Set template that wraps around a std::set to provide a more user-friendly interface and to provide common functions that do not exist in std::set.
Constructor & Destructor Documentation
template<typename E> decaf::util::StlSet< E >::StlSet () [inline]
Default constructor - does nothing.
template<typename E> decaf::util::StlSet< E >::StlSet (const StlSet< E > & source) [inline]
Copy constructor - copies the content of the given set into this one.
Parameters:
source The source set.
template<typename E> decaf::util::StlSet< E >::StlSet (const Collection< E > & source) [inline]
Copy constructor - copies the content of the given set into this one.
Parameters:
source The source set.
template<typename E> virtual decaf::util::StlSet< E >::~StlSet () [inline, virtual]
Member Function Documentation
template<typename E> virtual bool decaf::util::StlSet< E >::add (const E & value) [inline, virtual]
Returns true if this collection changed as a result of the call.(Returns false if this collection does not permit duplicates and already contains the specified element.)Collections that support this operation may place limitations on what elements may be added to this collection. In particular, some collections will refuse to add null elements, and others will impose restrictions on the type of elements that may be added. Collection classes should clearly specify in their documentation any restrictions on what elements may be added.If a collection refuses to add a particular element for any reason other than that it already contains the element, it must throw an exception (rather than returning false). This preserves the invariant that a collection always contains the specified element after this call returns.For non-pointer values, i.e. class instances or string's the object will be copied into the collection, thus the object must support being copied, must not hide the copy constructor and assignment operator.
Parameters:
value The reference to the element to add to this Collection.
Returns:
true if the element was added to this Collection.
Exceptions:
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
IllegalArgumentException if some property of the element prevents it from being added to this collection
IllegalStateException if the element cannot be added at this time due to insertion restrictions.
Implements decaf::util::Collection< E >.
template<typename E> virtual void decaf::util::StlSet< E >::clear () [inline, virtual]
Removes all of the elements from this collection (optional operation).The collection will be empty after this method returns.This implementation iterates over this collection, removing each element using the Iterator.remove operation. Most implementations will probably choose to override this method for efficiency.Note that this implementation will throw an UnsupportedOperationException if the iterator returned by this collection's iterator method does not implement the remove method and this collection is non-empty.
Exceptions:
UnsupportedOperationException if the clear operation is not supported by this collection
Reimplemented from decaf::util::AbstractCollection< E >.
template<typename E> virtual bool decaf::util::StlSet< E >::contains (const E & value) const [inline, virtual]
Returns true if this collection contains the specified element.More formally, returns true if and only if this collection contains at least one element e such that (value == NULL ? e == NULL : value == e).
Parameters:
value The value to check for presence in the collection.
Returns:
true if there is at least one of the elements in the collection
Exceptions:
NullPointerException if the Collection contains pointers and the Collection does not allow for NULL elements (optional check).
This implementation iterates over the elements in the collection, checking each element in turn for equality with the specified element.
Reimplemented from decaf::util::AbstractCollection< E >.
template<typename E> virtual void decaf::util::StlSet< E >::copy (const Collection< E > & collection) [inline, virtual]
Renders this Collection as a Copy of the given Collection.The default implementation iterates over the contents of the given collection adding each to this collection after first calling this Collection's clear method.
Parameters:
collection The collection to mirror.
Exceptions:
UnsupportedOperationExceptio if this is an unmodifiable collection.
IllegalStateException if the elements cannot be added at this time due to insertion restrictions.
Reimplemented from decaf::util::AbstractCollection< E >.
Referenced by decaf::util::StlSet< Resource * >::copy(), and decaf::util::StlSet< Resource * >::StlSet().
template<typename E> virtual bool decaf::util::StlSet< E >::equals (const Collection< E > & collection) const [inline, virtual]
Answers true if this Collection and the one given are the same size and if each element contained in the Collection given is equal to an element contained in this collection.
Parameters:
collection - The Collection to be compared to this one.
Returns:
true if this Collection is equal to the one given.
Reimplemented from decaf::util::AbstractCollection< E >.
Referenced by decaf::util::StlSet< Resource * >::equals().
template<typename E> virtual bool decaf::util::StlSet< E >::isEmpty () const [inline, virtual]
Returns:
if the set contains any element or not, TRUE or FALSE
Reimplemented from decaf::util::AbstractCollection< E >.
template<typename E> Iterator<E>* decaf::util::StlSet< E >::iterator () const [inline, virtual]
Implements decaf::lang::Iterable< E >.
template<typename E> Iterator<E>* decaf::util::StlSet< E >::iterator () [inline, virtual]
Returns:
an iterator over a set of elements of type T.
Implements decaf::lang::Iterable< E >.
template<typename E> virtual bool decaf::util::StlSet< E >::remove (const E & value) [inline, virtual]
Removes a single instance of the specified element from the collection.More formally, removes an element e such that (value == NULL ? e == NULL : value == e), if this collection contains one or more such elements. Returns true if this collection contained the specified element (or equivalently, if this collection changed as a result of the call).
Parameters:
value The reference to the element to remove from this Collection.
Returns:
true if the collection was changed, false otherwise.
Exceptions:
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
This implementation iterates over the collection looking for the specified element. If it finds the element, it removes the element from the collection using the iterator's remove method.Note that this implementation throws an UnsupportedOperationException if the iterator returned by this collection's iterator method does not implement the remove method and this collection contains the specified object.
Reimplemented from decaf::util::AbstractCollection< E >.
template<typename E> virtual int decaf::util::StlSet< E >::size () const [inline, virtual]
Returns:
The number of elements in this set.
Implements decaf::util::Collection< E >.
The documentation for this class was generated from the following file:
src/main/decaf/util/StlSet.h