activemq-cpp-3.4.0: decaf::util::AbstractQueue< E > Class Template Reference
decaf::util::AbstractQueue< E > Class Template Reference
This class provides skeletal implementations of some Queue operations.
#include <src/main/decaf/util/AbstractQueue.h>
Public Member Functions
AbstractQueue ()
virtual ~AbstractQueue ()
virtual bool add (const E &value)
Returns true if this collection changed as a result of the call.(Returns false if this collection does not permit duplicates and already contains the specified element.)Collections that support this operation may place limitations on what elements may be added to this collection. In particular, some collections will refuse to add null elements, and others will impose restrictions on the type of elements that may be added. Collection classes should clearly specify in their documentation any restrictions on what elements may be added.If a collection refuses to add a particular element for any reason other than that it already contains the element, it must throw an exception (rather than returning false). This preserves the invariant that a collection always contains the specified element after this call returns.For non-pointer values, i.e. class instances or string's the object will be copied into the collection, thus the object must support being copied, must not hide the copy constructor and assignment operator.
Parameters:
value The reference to the element to add to this Collection.
Returns:
true if the element was added to this Collection.
Exceptions:
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
IllegalArgumentException if some property of the element prevents it from being added to this collection
IllegalStateException if the element cannot be added at this time due to insertion restrictions.
virtual bool addAll (const Collection< E > &collection)
Adds all of the elements in the specified collection to this collection.The behavior of this operation is undefined if the specified collection is modified while the operation is in progress. (This implies that the behavior of this call is undefined if the specified collection is this collection, and this collection is nonempty.)
Parameters:
collection The Collection whose elements are added to this one.
Returns:
true if this collection changed as a result of the call
Exceptions:
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
IllegalArgumentException if some property of an element prevents it from being added to this collection
IllegalStateException if an element cannot be added at this time due to insertion restrictions.
This implementation iterates over the specified collection, and adds each object returned by the iterator to this collection, in turn.Note that this implementation will throw an UnsupportedOperationException unless add is overridden (assuming the specified collection is non-empty).
virtual E remove ()
Gets and removes the element in the head of the queue.Throws a NoSuchElementException if there is no element in the queue.
Returns:
the element in the head of the queue.
Exceptions:
NoSuchElementException if there is no element in the queue.
virtual E element () const
Gets but not removes the element in the head of the queue.Throws a NoSuchElementException if there is no element in the queue.
Returns:
the element in the head of the queue.
Exceptions:
NoSuchElementException if there is no element in the queue.
virtual void clear ()
Removes all of the elements from this collection (optional operation).The collection will be empty after this method returns.This implementation iterates over this collection, removing each element using the Iterator.remove operation. Most implementations will probably choose to override this method for efficiency.Note that this implementation will throw an UnsupportedOperationException if the iterator returned by this collection's iterator method does not implement the remove method and this collection is non-empty.
Exceptions:
UnsupportedOperationException if the clear operation is not supported by this collection
Detailed Description
template<typename E>
class decaf::util::AbstractQueue< E >
This class provides skeletal implementations of some Queue operations.
Methods add, remove, and element are based on offer, poll, and peek, respectively.
A Queue implementation that extends this class must minimally define a method Queue. offer(E) which does not permit insertion of null elements, along with methods Queue. peek(), Queue.poll(), Collection.size(), and a Collection.iterator() supporting Iterator.remove(). Typically, additional methods will be overridden as well. If these requirements cannot be met, consider instead subclassing AbstractCollection.
Since:
1.0
Constructor & Destructor Documentation
template<typename E > decaf::util::AbstractQueue< E >::AbstractQueue () [inline]
template<typename E > virtual decaf::util::AbstractQueue< E >::~AbstractQueue () [inline, virtual]
Member Function Documentation
template<typename E > virtual bool decaf::util::AbstractQueue< E >::add (const E & value) [inline, virtual]
Returns true if this collection changed as a result of the call.(Returns false if this collection does not permit duplicates and already contains the specified element.)Collections that support this operation may place limitations on what elements may be added to this collection. In particular, some collections will refuse to add null elements, and others will impose restrictions on the type of elements that may be added. Collection classes should clearly specify in their documentation any restrictions on what elements may be added.If a collection refuses to add a particular element for any reason other than that it already contains the element, it must throw an exception (rather than returning false). This preserves the invariant that a collection always contains the specified element after this call returns.For non-pointer values, i.e. class instances or string's the object will be copied into the collection, thus the object must support being copied, must not hide the copy constructor and assignment operator.
Parameters:
value The reference to the element to add to this Collection.
Returns:
true if the element was added to this Collection.
Exceptions:
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
IllegalArgumentException if some property of the element prevents it from being added to this collection
IllegalStateException if the element cannot be added at this time due to insertion restrictions.
This implementation returns true if offer succeeds, else throws an IllegalStateException.
Implements decaf::util::Collection< E >.
Reimplemented in decaf::util::PriorityQueue< E >.
References decaf::util::Queue< E >::offer().
template<typename E > virtual bool decaf::util::AbstractQueue< E >::addAll (const Collection< E > & collection) [inline, virtual]
Adds all of the elements in the specified collection to this collection.The behavior of this operation is undefined if the specified collection is modified while the operation is in progress. (This implies that the behavior of this call is undefined if the specified collection is this collection, and this collection is nonempty.)
Parameters:
collection The Collection whose elements are added to this one.
Returns:
true if this collection changed as a result of the call
Exceptions:
UnsupportedOperationExceptio if this is an unmodifiable collection.
NullPointerException if the Collection is a container of pointers and does not allow NULL values.
IllegalArgumentException if some property of an element prevents it from being added to this collection
IllegalStateException if an element cannot be added at this time due to insertion restrictions.
This implementation iterates over the specified collection, and adds each object returned by the iterator to this collection, in turn.Note that this implementation will throw an UnsupportedOperationException unless add is overridden (assuming the specified collection is non-empty).
This implementation checks to see if the Queue is being added to itself and throws an IllegalArgumentException if so, otherwise it delegates the add to the AbstractCollection's addAll implementation.
Reimplemented from decaf::util::AbstractCollection< E >.
Referenced by decaf::util::concurrent::LinkedBlockingQueue< E >::operator=().
template<typename E > virtual void decaf::util::AbstractQueue< E >::clear () [inline, virtual]
Removes all of the elements from this collection (optional operation).The collection will be empty after this method returns.This implementation iterates over this collection, removing each element using the Iterator.remove operation. Most implementations will probably choose to override this method for efficiency.Note that this implementation will throw an UnsupportedOperationException if the iterator returned by this collection's iterator method does not implement the remove method and this collection is non-empty.
Exceptions:
UnsupportedOperationException if the clear operation is not supported by this collection
This implementation repeatedly invokes poll until it returns false.
Reimplemented from decaf::util::AbstractCollection< E >.
Reimplemented in decaf::util::concurrent::LinkedBlockingQueue< E >, decaf::util::concurrent::SynchronousQueue< E >, and decaf::util::PriorityQueue< E >.
References decaf::util::AbstractCollection< E >::isEmpty(), and decaf::util::Queue< E >::poll().
template<typename E > virtual E decaf::util::AbstractQueue< E >::element () const [inline, virtual]
Gets but not removes the element in the head of the queue.Throws a NoSuchElementException if there is no element in the queue.
Returns:
the element in the head of the queue.
Exceptions:
NoSuchElementException if there is no element in the queue.
This implementation returns the result of peek unless the queue is empty otherwise it throws a NoSuchElementException.
Implements decaf::util::Queue< E >.
References decaf::util::Queue< E >::peek().
Referenced by decaf::util::concurrent::SynchronousQueue< E >::drainTo().
template<typename E > virtual E decaf::util::AbstractQueue< E >::remove () [inline, virtual]
Gets and removes the element in the head of the queue.Throws a NoSuchElementException if there is no element in the queue.
Returns:
the element in the head of the queue.
Exceptions:
NoSuchElementException if there is no element in the queue.
This implementation returns the result of poll unless the queue is empty.
Implements decaf::util::Queue< E >.
Reimplemented in decaf::util::PriorityQueue< E >.
References decaf::util::Queue< E >::poll().
The documentation for this class was generated from the following file:
src/main/decaf/util/AbstractQueue.h